/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#if defined(SUPPORT_DM_PURE181) || defined(SUPPORT_DM_DETECT)

#include "mdm_types.h"
#include "rcl.h"
#include "stl.h"


#pragma weak oidInfoArray_dev2
#pragma weak cnt_oidInfoArray_dev2
#pragma weak mdm_getPtrs_oidInfoArray_dev2

const MdmOidInfoEntry oidInfoArray_dev2[]= { 
{1000, "Device.", 
NULL, rcl_dev2DeviceObject, NULL, stl_dev2DeviceObject, NULL},

#if defined(DMP_X_BROADCOM_COM_GPON_1)
{2000, "Device.X_BROADCOM_COM_AppCfg.OmcidCfg.", 
NULL, rcl_omcidCfgObject, NULL, stl_omcidCfgObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1)
{2100, "Device.X_BROADCOM_COM_OMCI.", 
NULL, rcl_bcmOmciObject, NULL, stl_bcmOmciObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2101, "Device.X_BROADCOM_COM_OMCI.RunTimeData.", 
NULL, rcl_bcmOmciRtdObject, NULL, stl_bcmOmciRtdObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2102, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Multicast.", 
NULL, rcl_bcmOmciRtdMcastObject, NULL, stl_bcmOmciRtdMcastObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2103, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.", 
NULL, rcl_bcmOmciRtdLayer3Object, NULL, stl_bcmOmciRtdLayer3Object, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2104, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.IpHostConfigData.{i}.", 
NULL, rcl_bcmOmciRtdIpHostConfigDataObject, NULL, stl_bcmOmciRtdIpHostConfigDataObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2105, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.IpHostConfigDataExt.{i}.", 
NULL, rcl_bcmOmciRtdIpHostConfigDataExtObject, NULL, stl_bcmOmciRtdIpHostConfigDataExtObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2106, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.Ipv6HostConfigData.{i}.", 
NULL, rcl_bcmOmciRtdIpv6HostConfigDataObject, NULL, stl_bcmOmciRtdIpv6HostConfigDataObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2107, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}.", 
NULL, rcl_bcmOmciRtdIpv6CurrentAddressTableObject, NULL, stl_bcmOmciRtdIpv6CurrentAddressTableObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2108, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}.", 
NULL, rcl_bcmOmciRtdIpv6CurrentDefaultRouterTableObject, NULL, stl_bcmOmciRtdIpv6CurrentDefaultRouterTableObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2109, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}.", 
NULL, rcl_bcmOmciRtdIpv6CurrentDnsTableObject, NULL, stl_bcmOmciRtdIpv6CurrentDnsTableObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2110, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}.", 
NULL, rcl_bcmOmciRtdIpv6CurrentOnlinkPrefixTableObject, NULL, stl_bcmOmciRtdIpv6CurrentOnlinkPrefixTableObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2111, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.Ipv6HostConfigDataExt.{i}.", 
NULL, rcl_bcmOmciRtdIpv6HostConfigDataExtObject, NULL, stl_bcmOmciRtdIpv6HostConfigDataExtObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2112, "Device.X_BROADCOM_COM_OMCI.RunTimeData.Layer3.TcpUdpConfigData.{i}.", 
NULL, rcl_bcmOmciRtdTcpUdpConfigDataObject, NULL, stl_bcmOmciRtdTcpUdpConfigDataObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2113, "Device.X_BROADCOM_COM_OMCI.Debug.", 
NULL, rcl_bcmOmciDebugObject, NULL, stl_bcmOmciDebugObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2114, "Device.X_BROADCOM_COM_OMCI.Config.", 
NULL, rcl_bcmOmciConfigObject, NULL, stl_bcmOmciConfigObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2115, "Device.X_BROADCOM_COM_OMCI.Config.OmciSystemCfg.", 
NULL, rcl_bcmOmciConfigSystemObject, NULL, stl_bcmOmciConfigSystemObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2116, "Device.X_BROADCOM_COM_OMCI.Stats.", 
NULL, rcl_bcmOmciStatsObject, NULL, stl_bcmOmciStatsObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2117, "Device.X_BROADCOM_COM_OMCI.Stats.GponOmciStats.", 
NULL, rcl_bcmOmciStatsGponOmciStatsObject, NULL, stl_bcmOmciStatsGponOmciStatsObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1)
{2200, "Device.X_BROADCOM_COM_GPON.", 
NULL, rcl_bcmGponObject, NULL, stl_bcmGponObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2201, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.", 
NULL, rcl_gponPhysicalMediaObject, NULL, stl_gponPhysicalMediaObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2202, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.RxPower.", 
NULL, rcl_gponPhysicalMediaRxPowerObject, NULL, stl_gponPhysicalMediaRxPowerObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2203, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.TxPower.", 
NULL, rcl_gponPhysicalMediaTxPowerObject, NULL, stl_gponPhysicalMediaTxPowerObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2204, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.Voltage.", 
NULL, rcl_gponPhysicalMediaVoltageObject, NULL, stl_gponPhysicalMediaVoltageObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2205, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.Bias.", 
NULL, rcl_gponPhysicalMediaBiasObject, NULL, stl_gponPhysicalMediaBiasObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2206, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.Temp.", 
NULL, rcl_gponPhysicalMediaTempObject, NULL, stl_gponPhysicalMediaTempObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2207, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.WaveLength.", 
NULL, rcl_gponPhysicalMediaWaveLengthObject, NULL, stl_gponPhysicalMediaWaveLengthObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2208, "Device.X_BROADCOM_COM_GPON.PhysicalMedia.{i}.Alarms.", 
NULL, rcl_gponPhysicalMediaAlarmsObject, NULL, stl_gponPhysicalMediaAlarmsObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2209, "Device.X_BROADCOM_COM_GPON.GTC.", 
NULL, rcl_gponGtcObject, NULL, stl_gponGtcObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2210, "Device.X_BROADCOM_COM_GPON.Ploam.", 
NULL, rcl_gponPloamObject, NULL, stl_gponPloamObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2211, "Device.X_BROADCOM_COM_GPON.Omci.", 
NULL, rcl_gponOmciObject, NULL, stl_gponOmciObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2212, "Device.X_BROADCOM_COM_GPON.TcLayerStatus.{i}.", 
NULL, rcl_gponTcLayerStatusObject, NULL, stl_gponTcLayerStatusObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2213, "Device.X_BROADCOM_COM_GPON.WanLinkStatus.{i}.", 
NULL, rcl_gponWanLinkStatusObject, NULL, stl_gponWanLinkStatusObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2214, "Device.X_BROADCOM_COM_GPON.Veip.{i}.", 
NULL, rcl_gponVeipObject, NULL, stl_gponVeipObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2215, "Device.X_BROADCOM_COM_GPON.Tr069ManagementServer.{i}.", 
NULL, rcl_gponTr069MgmtServerObject, NULL, stl_gponTr069MgmtServerObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2216, "Device.X_BROADCOM_COM_GPON.Stats.", 
NULL, rcl_gponStatsObject, NULL, stl_gponStatsObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2217, "Device.X_BROADCOM_COM_GPON.GponVeipStats.{i}.", 
NULL, rcl_gponVeipStatObject, NULL, stl_gponVeipStatObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
{2218, "Device.X_BROADCOM_COM_GPON.GemStats.{i}.", 
NULL, rcl_gponGemStatObject, NULL, stl_gponGemStatObject, NULL},
#endif

{3130, "Device.X_BROADCOM_COM_AppCfg.", 
NULL, rcl_appCfgObject, NULL, stl_appCfgObject, NULL},

#if defined(DMP_X_BROADCOM_COM_GPON_1)
{3325, "Device.X_BROADCOM_COM_AppCfg.GponMdCfg.", 
NULL, rcl_gponMdCfgObject, NULL, stl_gponMdCfgObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_GPON_1)
{3326, "Device.X_BROADCOM_COM_AppCfg.GponHalThreadCfg.", 
NULL, rcl_gponHalThreadCfgObject, NULL, stl_gponHalThreadCfgObject, NULL},
#endif

{3339, "Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg.", 
NULL, rcl_bcmMsgdCfgObject, NULL, stl_bcmMsgdCfgObject, NULL},


};

int cnt_oidInfoArray_dev2 = (sizeof(oidInfoArray_dev2) / sizeof(MdmOidInfoEntry));

void mdm_getPtrs_oidInfoArray_dev2(const MdmOidInfoEntry **begin, const MdmOidInfoEntry **end)
{
   *begin = oidInfoArray_dev2;
   *end = &(oidInfoArray_dev2 [cnt_oidInfoArray_dev2 - 1]);
}
#endif  /* defined(SUPPORT_DM_PURE181) || defined(SUPPORT_DM_DETECT) */ 
