/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_start_task_initialization_task        (0x388)
#define image_0_initialization_task        (0x388)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0x3120)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0x3120)
#define image_0_start_task_processing_wakeup_request        (0x4c0)
#define image_0_processing_wakeup_request        (0x4c0)
#define image_0_start_task_tx_task_1st_wakeup_request        (0x35a8)
#define image_0_tx_task_1st_wakeup_request        (0x35a8)
#define image_0_start_task_timer_common_task_wakeup_request        (0x3e00)
#define image_0_timer_common_task_wakeup_request        (0x3e00)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x3988)
#define image_0_budget_allocator_1st_wakeup_request        (0x3988)
#define image_0_start_task_debug_routine        (0x3f4)
#define image_0_debug_routine        (0x3f4)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x3f60)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x3f60)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x41a8)
#define image_0_service_queues_tx_task_wakeup_request        (0x41a8)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x4370)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x4370)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dynamic_code_section        (0x8)
#define image_0_dynamic_code_section_proc0        (0x8)
#define image_0_dynamic_code_section_proc1        (0x78)
#define image_0_dynamic_code_section_proc2        (0xe8)
#define image_0_dynamic_code_section_proc3        (0x158)
#define image_0_dynamic_code_section_proc4        (0x1c8)
#define image_0_dynamic_code_section_proc5        (0x238)
#define image_0_dynamic_code_section_proc6        (0x2a8)
#define image_0_dynamic_code_section_proc7        (0x318)
#define image_0_processing_check_wlan_llcsnap        (0xd98)
#define image_0_processing_write_header_done        (0xd98)
#define image_0_processing_done        (0xdf4)
#define image_0_action_gpe        (0x2218)
#define image_0_action_exception        (0x2220)
#define image_0_gpe_sop_push_replace_ddr_sram_32        (0x2258)
#define image_0_gpe_sop_push_replace_sram_32_64        (0x22a0)
#define image_0_gpe_sop_push_replace_sram_64        (0x22b8)
#define image_0_gpe_sop_push_replace_sram_64_32        (0x22d0)
#define image_0_gpe_sop_pull_replace_ddr_sram_32        (0x22e8)
#define image_0_gpe_sop_pull_replace_sram_32_64        (0x2330)
#define image_0_gpe_sop_pull_replace_sram_64        (0x2378)
#define image_0_gpe_sop_pull_replace_sram_64_32        (0x23b8)
#define image_0_gpe_replace_pointer_32_sram        (0x2400)
#define image_0_gpe_replace_pointer_64_sram        (0x2428)
#define image_0_gpe_replace_16        (0x2450)
#define image_0_gpe_replace_32        (0x2488)
#define image_0_gpe_replace_bits_16        (0x24b0)
#define image_0_gpe_copy_add_16_cl        (0x24e0)
#define image_0_gpe_copy_add_16_sram        (0x24f0)
#define image_0_gpe_copy_bits_16_cl        (0x2538)
#define image_0_gpe_copy_bits_16_sram        (0x2548)
#define image_0_gpe_insert_16        (0x2590)
#define image_0_gpe_delete_16        (0x25f8)
#define image_0_gpe_decrement_8        (0x2638)
#define image_0_gpe_apply_icsum_16        (0x2658)
#define image_0_gpe_apply_icsum_nz_16        (0x2678)
#define image_0_gpe_compute_csum_16_cl        (0x26a8)
#define image_0_gpe_compute_csum_16_sram        (0x26b8)
#define image_0_gpe_buffer_copy_16_sram        (0x26f8)
#define image_0_gpe_buffer_copy_16_ddr        (0x2728)
#define image_0_gpe_replace_add_packet_length_cl        (0x2750)
#define image_0_tcam_cmd_ic_submit        (0x2794)

#else

#define image_0_start_task_initialization_task        (0xe2)
#define image_0_initialization_task        (0xe2)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0xc48)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0xc48)
#define image_0_start_task_processing_wakeup_request        (0x130)
#define image_0_processing_wakeup_request        (0x130)
#define image_0_start_task_tx_task_1st_wakeup_request        (0xd6a)
#define image_0_tx_task_1st_wakeup_request        (0xd6a)
#define image_0_start_task_timer_common_task_wakeup_request        (0xf80)
#define image_0_timer_common_task_wakeup_request        (0xf80)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0xe62)
#define image_0_budget_allocator_1st_wakeup_request        (0xe62)
#define image_0_start_task_debug_routine        (0xfd)
#define image_0_debug_routine        (0xfd)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0xfd8)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0xfd8)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x106a)
#define image_0_service_queues_tx_task_wakeup_request        (0x106a)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x10dc)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x10dc)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dynamic_code_section        (0x2)
#define image_0_dynamic_code_section_proc0        (0x2)
#define image_0_dynamic_code_section_proc1        (0x1e)
#define image_0_dynamic_code_section_proc2        (0x3a)
#define image_0_dynamic_code_section_proc3        (0x56)
#define image_0_dynamic_code_section_proc4        (0x72)
#define image_0_dynamic_code_section_proc5        (0x8e)
#define image_0_dynamic_code_section_proc6        (0xaa)
#define image_0_dynamic_code_section_proc7        (0xc6)
#define image_0_processing_check_wlan_llcsnap        (0x366)
#define image_0_processing_write_header_done        (0x366)
#define image_0_processing_done        (0x37d)
#define image_0_action_gpe        (0x886)
#define image_0_action_exception        (0x888)
#define image_0_gpe_sop_push_replace_ddr_sram_32        (0x896)
#define image_0_gpe_sop_push_replace_sram_32_64        (0x8a8)
#define image_0_gpe_sop_push_replace_sram_64        (0x8ae)
#define image_0_gpe_sop_push_replace_sram_64_32        (0x8b4)
#define image_0_gpe_sop_pull_replace_ddr_sram_32        (0x8ba)
#define image_0_gpe_sop_pull_replace_sram_32_64        (0x8cc)
#define image_0_gpe_sop_pull_replace_sram_64        (0x8de)
#define image_0_gpe_sop_pull_replace_sram_64_32        (0x8ee)
#define image_0_gpe_replace_pointer_32_sram        (0x900)
#define image_0_gpe_replace_pointer_64_sram        (0x90a)
#define image_0_gpe_replace_16        (0x914)
#define image_0_gpe_replace_32        (0x922)
#define image_0_gpe_replace_bits_16        (0x92c)
#define image_0_gpe_copy_add_16_cl        (0x938)
#define image_0_gpe_copy_add_16_sram        (0x93c)
#define image_0_gpe_copy_bits_16_cl        (0x94e)
#define image_0_gpe_copy_bits_16_sram        (0x952)
#define image_0_gpe_insert_16        (0x964)
#define image_0_gpe_delete_16        (0x97e)
#define image_0_gpe_decrement_8        (0x98e)
#define image_0_gpe_apply_icsum_16        (0x996)
#define image_0_gpe_apply_icsum_nz_16        (0x99e)
#define image_0_gpe_compute_csum_16_cl        (0x9aa)
#define image_0_gpe_compute_csum_16_sram        (0x9ae)
#define image_0_gpe_buffer_copy_16_sram        (0x9be)
#define image_0_gpe_buffer_copy_16_ddr        (0x9ca)
#define image_0_gpe_replace_add_packet_length_cl        (0x9d4)
#define image_0_tcam_cmd_ic_submit        (0x9e5)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_start_task_initialization_task        (0x388)
#define image_1_initialization_task        (0x388)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x4470)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x4470)
#define image_1_start_task_processing_wakeup_request        (0x4c0)
#define image_1_processing_wakeup_request        (0x4c0)
#define image_1_start_task_tx_task_1st_wakeup_request        (0x3a20)
#define image_1_tx_task_1st_wakeup_request        (0x3a20)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x4018)
#define image_1_budget_allocator_1st_wakeup_request        (0x4018)
#define image_1_start_task_debug_routine        (0x3b0)
#define image_1_debug_routine        (0x3b0)
#define image_1_start_task_pfc_direct_wakeup_request        (0x3780)
#define image_1_pfc_direct_wakeup_request        (0x3780)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x4358)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x4358)
#define image_1_start_task_dhd_tx_complete_wakeup_request        (0x3128)
#define image_1_dhd_tx_complete_wakeup_request        (0x3128)
#define image_1_start_task_dhd_rx_complete_wakeup_request        (0x3440)
#define image_1_dhd_rx_complete_wakeup_request        (0x3440)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dynamic_code_section        (0x8)
#define image_1_dynamic_code_section_proc0        (0x8)
#define image_1_dynamic_code_section_proc1        (0x78)
#define image_1_dynamic_code_section_proc2        (0xe8)
#define image_1_dynamic_code_section_proc3        (0x158)
#define image_1_dynamic_code_section_proc4        (0x1c8)
#define image_1_dynamic_code_section_proc5        (0x238)
#define image_1_dynamic_code_section_proc6        (0x2a8)
#define image_1_dynamic_code_section_proc7        (0x318)
#define image_1_processing_check_wlan_llcsnap        (0xd98)
#define image_1_processing_write_header_done        (0xd98)
#define image_1_processing_done        (0xdf4)
#define image_1_action_gpe        (0x2220)
#define image_1_action_exception        (0x2228)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x2260)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x22a8)
#define image_1_gpe_sop_push_replace_sram_64        (0x22c0)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x22d8)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x22f0)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x2338)
#define image_1_gpe_sop_pull_replace_sram_64        (0x2380)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x23c0)
#define image_1_gpe_replace_pointer_32_sram        (0x2408)
#define image_1_gpe_replace_pointer_64_sram        (0x2430)
#define image_1_gpe_replace_16        (0x2458)
#define image_1_gpe_replace_32        (0x2490)
#define image_1_gpe_replace_bits_16        (0x24b8)
#define image_1_gpe_copy_add_16_cl        (0x24e8)
#define image_1_gpe_copy_add_16_sram        (0x24f8)
#define image_1_gpe_copy_bits_16_cl        (0x2540)
#define image_1_gpe_copy_bits_16_sram        (0x2550)
#define image_1_gpe_insert_16        (0x2598)
#define image_1_gpe_delete_16        (0x2600)
#define image_1_gpe_decrement_8        (0x2640)
#define image_1_gpe_apply_icsum_16        (0x2660)
#define image_1_gpe_apply_icsum_nz_16        (0x2680)
#define image_1_gpe_compute_csum_16_cl        (0x26b0)
#define image_1_gpe_compute_csum_16_sram        (0x26c0)
#define image_1_gpe_buffer_copy_16_sram        (0x2700)
#define image_1_gpe_buffer_copy_16_ddr        (0x2730)
#define image_1_gpe_replace_add_packet_length_cl        (0x2758)
#define image_1_tcam_cmd_ic_submit        (0x279c)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x478c)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x478c)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x4abc)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x4abc)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x46c8)
#define image_1_dhd_send_entry_to_cpu_ring        (0x46c8)

#else

#define image_1_start_task_initialization_task        (0xe2)
#define image_1_initialization_task        (0xe2)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x111c)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x111c)
#define image_1_start_task_processing_wakeup_request        (0x130)
#define image_1_processing_wakeup_request        (0x130)
#define image_1_start_task_tx_task_1st_wakeup_request        (0xe88)
#define image_1_tx_task_1st_wakeup_request        (0xe88)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x1006)
#define image_1_budget_allocator_1st_wakeup_request        (0x1006)
#define image_1_start_task_debug_routine        (0xec)
#define image_1_debug_routine        (0xec)
#define image_1_start_task_pfc_direct_wakeup_request        (0xde0)
#define image_1_pfc_direct_wakeup_request        (0xde0)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x10d6)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x10d6)
#define image_1_start_task_dhd_tx_complete_wakeup_request        (0xc4a)
#define image_1_dhd_tx_complete_wakeup_request        (0xc4a)
#define image_1_start_task_dhd_rx_complete_wakeup_request        (0xd10)
#define image_1_dhd_rx_complete_wakeup_request        (0xd10)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dynamic_code_section        (0x2)
#define image_1_dynamic_code_section_proc0        (0x2)
#define image_1_dynamic_code_section_proc1        (0x1e)
#define image_1_dynamic_code_section_proc2        (0x3a)
#define image_1_dynamic_code_section_proc3        (0x56)
#define image_1_dynamic_code_section_proc4        (0x72)
#define image_1_dynamic_code_section_proc5        (0x8e)
#define image_1_dynamic_code_section_proc6        (0xaa)
#define image_1_dynamic_code_section_proc7        (0xc6)
#define image_1_processing_check_wlan_llcsnap        (0x366)
#define image_1_processing_write_header_done        (0x366)
#define image_1_processing_done        (0x37d)
#define image_1_action_gpe        (0x888)
#define image_1_action_exception        (0x88a)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x898)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x8aa)
#define image_1_gpe_sop_push_replace_sram_64        (0x8b0)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x8b6)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x8bc)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x8ce)
#define image_1_gpe_sop_pull_replace_sram_64        (0x8e0)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x8f0)
#define image_1_gpe_replace_pointer_32_sram        (0x902)
#define image_1_gpe_replace_pointer_64_sram        (0x90c)
#define image_1_gpe_replace_16        (0x916)
#define image_1_gpe_replace_32        (0x924)
#define image_1_gpe_replace_bits_16        (0x92e)
#define image_1_gpe_copy_add_16_cl        (0x93a)
#define image_1_gpe_copy_add_16_sram        (0x93e)
#define image_1_gpe_copy_bits_16_cl        (0x950)
#define image_1_gpe_copy_bits_16_sram        (0x954)
#define image_1_gpe_insert_16        (0x966)
#define image_1_gpe_delete_16        (0x980)
#define image_1_gpe_decrement_8        (0x990)
#define image_1_gpe_apply_icsum_16        (0x998)
#define image_1_gpe_apply_icsum_nz_16        (0x9a0)
#define image_1_gpe_compute_csum_16_cl        (0x9ac)
#define image_1_gpe_compute_csum_16_sram        (0x9b0)
#define image_1_gpe_buffer_copy_16_sram        (0x9c0)
#define image_1_gpe_buffer_copy_16_ddr        (0x9cc)
#define image_1_gpe_replace_add_packet_length_cl        (0x9d6)
#define image_1_tcam_cmd_ic_submit        (0x9e7)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x11e3)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x11e3)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x12af)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x12af)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x11b2)
#define image_1_dhd_send_entry_to_cpu_ring        (0x11b2)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_start_task_initialization_task        (0x388)
#define image_2_initialization_task        (0x388)
#define image_2_start_task_processing_wakeup_request        (0x4c0)
#define image_2_processing_wakeup_request        (0x4c0)
#define image_2_start_task_cpu_tx_wakeup_request        (0x3120)
#define image_2_cpu_tx_wakeup_request        (0x3120)
#define image_2_cpu_tx_read_ring_indices        (0x3120)
#define image_2_start_task_debug_routine        (0x3b0)
#define image_2_debug_routine        (0x3b0)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x37b0)
#define image_2_cpu_recycle_wakeup_request        (0x37b0)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x3900)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x3900)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dynamic_code_section        (0x8)
#define image_2_dynamic_code_section_proc0        (0x8)
#define image_2_dynamic_code_section_proc1        (0x78)
#define image_2_dynamic_code_section_proc2        (0xe8)
#define image_2_dynamic_code_section_proc3        (0x158)
#define image_2_dynamic_code_section_proc4        (0x1c8)
#define image_2_dynamic_code_section_proc5        (0x238)
#define image_2_dynamic_code_section_proc6        (0x2a8)
#define image_2_dynamic_code_section_proc7        (0x318)
#define image_2_processing_check_wlan_llcsnap        (0xd98)
#define image_2_processing_write_header_done        (0xd98)
#define image_2_processing_done        (0xdf4)
#define image_2_action_gpe        (0x2218)
#define image_2_action_exception        (0x2220)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x2258)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x22a0)
#define image_2_gpe_sop_push_replace_sram_64        (0x22b8)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x22d0)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x22e8)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x2330)
#define image_2_gpe_sop_pull_replace_sram_64        (0x2378)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x23b8)
#define image_2_gpe_replace_pointer_32_sram        (0x2400)
#define image_2_gpe_replace_pointer_64_sram        (0x2428)
#define image_2_gpe_replace_16        (0x2450)
#define image_2_gpe_replace_32        (0x2488)
#define image_2_gpe_replace_bits_16        (0x24b0)
#define image_2_gpe_copy_add_16_cl        (0x24e0)
#define image_2_gpe_copy_add_16_sram        (0x24f0)
#define image_2_gpe_copy_bits_16_cl        (0x2538)
#define image_2_gpe_copy_bits_16_sram        (0x2548)
#define image_2_gpe_insert_16        (0x2590)
#define image_2_gpe_delete_16        (0x25f8)
#define image_2_gpe_decrement_8        (0x2638)
#define image_2_gpe_apply_icsum_16        (0x2658)
#define image_2_gpe_apply_icsum_nz_16        (0x2678)
#define image_2_gpe_compute_csum_16_cl        (0x26a8)
#define image_2_gpe_compute_csum_16_sram        (0x26b8)
#define image_2_gpe_buffer_copy_16_sram        (0x26f8)
#define image_2_gpe_buffer_copy_16_ddr        (0x2728)
#define image_2_gpe_replace_add_packet_length_cl        (0x2750)
#define image_2_tcam_cmd_ic_submit        (0x2794)

#else

#define image_2_start_task_initialization_task        (0xe2)
#define image_2_initialization_task        (0xe2)
#define image_2_start_task_processing_wakeup_request        (0x130)
#define image_2_processing_wakeup_request        (0x130)
#define image_2_start_task_cpu_tx_wakeup_request        (0xc48)
#define image_2_cpu_tx_wakeup_request        (0xc48)
#define image_2_cpu_tx_read_ring_indices        (0xc48)
#define image_2_start_task_debug_routine        (0xec)
#define image_2_debug_routine        (0xec)
#define image_2_start_task_cpu_recycle_wakeup_request        (0xdec)
#define image_2_cpu_recycle_wakeup_request        (0xdec)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0xe40)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0xe40)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dynamic_code_section        (0x2)
#define image_2_dynamic_code_section_proc0        (0x2)
#define image_2_dynamic_code_section_proc1        (0x1e)
#define image_2_dynamic_code_section_proc2        (0x3a)
#define image_2_dynamic_code_section_proc3        (0x56)
#define image_2_dynamic_code_section_proc4        (0x72)
#define image_2_dynamic_code_section_proc5        (0x8e)
#define image_2_dynamic_code_section_proc6        (0xaa)
#define image_2_dynamic_code_section_proc7        (0xc6)
#define image_2_processing_check_wlan_llcsnap        (0x366)
#define image_2_processing_write_header_done        (0x366)
#define image_2_processing_done        (0x37d)
#define image_2_action_gpe        (0x886)
#define image_2_action_exception        (0x888)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x896)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x8a8)
#define image_2_gpe_sop_push_replace_sram_64        (0x8ae)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x8b4)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x8ba)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x8cc)
#define image_2_gpe_sop_pull_replace_sram_64        (0x8de)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x8ee)
#define image_2_gpe_replace_pointer_32_sram        (0x900)
#define image_2_gpe_replace_pointer_64_sram        (0x90a)
#define image_2_gpe_replace_16        (0x914)
#define image_2_gpe_replace_32        (0x922)
#define image_2_gpe_replace_bits_16        (0x92c)
#define image_2_gpe_copy_add_16_cl        (0x938)
#define image_2_gpe_copy_add_16_sram        (0x93c)
#define image_2_gpe_copy_bits_16_cl        (0x94e)
#define image_2_gpe_copy_bits_16_sram        (0x952)
#define image_2_gpe_insert_16        (0x964)
#define image_2_gpe_delete_16        (0x97e)
#define image_2_gpe_decrement_8        (0x98e)
#define image_2_gpe_apply_icsum_16        (0x996)
#define image_2_gpe_apply_icsum_nz_16        (0x99e)
#define image_2_gpe_compute_csum_16_cl        (0x9aa)
#define image_2_gpe_compute_csum_16_sram        (0x9ae)
#define image_2_gpe_buffer_copy_16_sram        (0x9be)
#define image_2_gpe_buffer_copy_16_ddr        (0x9ca)
#define image_2_gpe_replace_add_packet_length_cl        (0x9d4)
#define image_2_tcam_cmd_ic_submit        (0x9e5)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_start_task_initialization_task        (0x388)
#define image_3_initialization_task        (0x388)
#define image_3_start_task_processing_wakeup_request        (0x3b0)
#define image_3_processing_wakeup_request        (0x3b0)
#define image_3_start_task_debug_routine        (0x3018)
#define image_3_debug_routine        (0x3018)
#define image_3_start_task_cpu_rx_wakeup_request        (0x3e40)
#define image_3_cpu_rx_wakeup_request        (0x3e40)
#define image_3_start_task_cpu_recycle_wakeup_request        (0x4220)
#define image_3_cpu_recycle_wakeup_request        (0x4220)
#define image_3_start_task_interrupt_coalescing_1st_wakeup_request        (0x4370)
#define image_3_interrupt_coalescing_1st_wakeup_request        (0x4370)
#define image_3_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4170)
#define image_3_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4170)
#define image_3_start_task_cpu_rx_copy_wakeup_request        (0x30e4)
#define image_3_cpu_rx_copy_wakeup_request        (0x30e4)
#define image_3_start_task_spdsvc_gen_wakeup_request        (0x52f0)
#define image_3_spdsvc_gen_wakeup_request        (0x52f0)
#define image_3_start_task_common_reprocessing_wakeup_request        (0x5550)
#define image_3_common_reprocessing_wakeup_request        (0x5550)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dynamic_code_section        (0x8)
#define image_3_dynamic_code_section_proc0        (0x8)
#define image_3_dynamic_code_section_proc1        (0x78)
#define image_3_dynamic_code_section_proc2        (0xe8)
#define image_3_dynamic_code_section_proc3        (0x158)
#define image_3_dynamic_code_section_proc4        (0x1c8)
#define image_3_dynamic_code_section_proc5        (0x238)
#define image_3_dynamic_code_section_proc6        (0x2a8)
#define image_3_dynamic_code_section_proc7        (0x318)
#define image_3_processing_check_wlan_llcsnap        (0xc88)
#define image_3_processing_write_header_done        (0xc88)
#define image_3_processing_done        (0xce4)
#define image_3_action_gpe        (0x2110)
#define image_3_action_exception        (0x2118)
#define image_3_gpe_sop_push_replace_ddr_sram_32        (0x2150)
#define image_3_gpe_sop_push_replace_sram_32_64        (0x2198)
#define image_3_gpe_sop_push_replace_sram_64        (0x21b0)
#define image_3_gpe_sop_push_replace_sram_64_32        (0x21c8)
#define image_3_gpe_sop_pull_replace_ddr_sram_32        (0x21e0)
#define image_3_gpe_sop_pull_replace_sram_32_64        (0x2228)
#define image_3_gpe_sop_pull_replace_sram_64        (0x2270)
#define image_3_gpe_sop_pull_replace_sram_64_32        (0x22b0)
#define image_3_gpe_replace_pointer_32_sram        (0x22f8)
#define image_3_gpe_replace_pointer_64_sram        (0x2320)
#define image_3_gpe_replace_16        (0x2348)
#define image_3_gpe_replace_32        (0x2380)
#define image_3_gpe_replace_bits_16        (0x23a8)
#define image_3_gpe_copy_add_16_cl        (0x23d8)
#define image_3_gpe_copy_add_16_sram        (0x23e8)
#define image_3_gpe_copy_bits_16_cl        (0x2430)
#define image_3_gpe_copy_bits_16_sram        (0x2440)
#define image_3_gpe_insert_16        (0x2488)
#define image_3_gpe_delete_16        (0x24f0)
#define image_3_gpe_decrement_8        (0x2530)
#define image_3_gpe_apply_icsum_16        (0x2550)
#define image_3_gpe_apply_icsum_nz_16        (0x2570)
#define image_3_gpe_compute_csum_16_cl        (0x25a0)
#define image_3_gpe_compute_csum_16_sram        (0x25b0)
#define image_3_gpe_buffer_copy_16_sram        (0x25f0)
#define image_3_gpe_buffer_copy_16_ddr        (0x2620)
#define image_3_gpe_replace_add_packet_length_cl        (0x2648)
#define image_3_tcam_cmd_ic_submit        (0x268c)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x5a58)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x5a58)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x56e4)
#define image_3_c_cpu_rx_wakeup_request        (0x56e4)

#else

#define image_3_start_task_initialization_task        (0xe2)
#define image_3_initialization_task        (0xe2)
#define image_3_start_task_processing_wakeup_request        (0xec)
#define image_3_processing_wakeup_request        (0xec)
#define image_3_start_task_debug_routine        (0xc06)
#define image_3_debug_routine        (0xc06)
#define image_3_start_task_cpu_rx_wakeup_request        (0xf90)
#define image_3_cpu_rx_wakeup_request        (0xf90)
#define image_3_start_task_cpu_recycle_wakeup_request        (0x1088)
#define image_3_cpu_recycle_wakeup_request        (0x1088)
#define image_3_start_task_interrupt_coalescing_1st_wakeup_request        (0x10dc)
#define image_3_interrupt_coalescing_1st_wakeup_request        (0x10dc)
#define image_3_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x105c)
#define image_3_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x105c)
#define image_3_start_task_cpu_rx_copy_wakeup_request        (0xc39)
#define image_3_cpu_rx_copy_wakeup_request        (0xc39)
#define image_3_start_task_spdsvc_gen_wakeup_request        (0x14bc)
#define image_3_spdsvc_gen_wakeup_request        (0x14bc)
#define image_3_start_task_common_reprocessing_wakeup_request        (0x1554)
#define image_3_common_reprocessing_wakeup_request        (0x1554)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dynamic_code_section        (0x2)
#define image_3_dynamic_code_section_proc0        (0x2)
#define image_3_dynamic_code_section_proc1        (0x1e)
#define image_3_dynamic_code_section_proc2        (0x3a)
#define image_3_dynamic_code_section_proc3        (0x56)
#define image_3_dynamic_code_section_proc4        (0x72)
#define image_3_dynamic_code_section_proc5        (0x8e)
#define image_3_dynamic_code_section_proc6        (0xaa)
#define image_3_dynamic_code_section_proc7        (0xc6)
#define image_3_processing_check_wlan_llcsnap        (0x322)
#define image_3_processing_write_header_done        (0x322)
#define image_3_processing_done        (0x339)
#define image_3_action_gpe        (0x844)
#define image_3_action_exception        (0x846)
#define image_3_gpe_sop_push_replace_ddr_sram_32        (0x854)
#define image_3_gpe_sop_push_replace_sram_32_64        (0x866)
#define image_3_gpe_sop_push_replace_sram_64        (0x86c)
#define image_3_gpe_sop_push_replace_sram_64_32        (0x872)
#define image_3_gpe_sop_pull_replace_ddr_sram_32        (0x878)
#define image_3_gpe_sop_pull_replace_sram_32_64        (0x88a)
#define image_3_gpe_sop_pull_replace_sram_64        (0x89c)
#define image_3_gpe_sop_pull_replace_sram_64_32        (0x8ac)
#define image_3_gpe_replace_pointer_32_sram        (0x8be)
#define image_3_gpe_replace_pointer_64_sram        (0x8c8)
#define image_3_gpe_replace_16        (0x8d2)
#define image_3_gpe_replace_32        (0x8e0)
#define image_3_gpe_replace_bits_16        (0x8ea)
#define image_3_gpe_copy_add_16_cl        (0x8f6)
#define image_3_gpe_copy_add_16_sram        (0x8fa)
#define image_3_gpe_copy_bits_16_cl        (0x90c)
#define image_3_gpe_copy_bits_16_sram        (0x910)
#define image_3_gpe_insert_16        (0x922)
#define image_3_gpe_delete_16        (0x93c)
#define image_3_gpe_decrement_8        (0x94c)
#define image_3_gpe_apply_icsum_16        (0x954)
#define image_3_gpe_apply_icsum_nz_16        (0x95c)
#define image_3_gpe_compute_csum_16_cl        (0x968)
#define image_3_gpe_compute_csum_16_sram        (0x96c)
#define image_3_gpe_buffer_copy_16_sram        (0x97c)
#define image_3_gpe_buffer_copy_16_ddr        (0x988)
#define image_3_gpe_replace_add_packet_length_cl        (0x992)
#define image_3_tcam_cmd_ic_submit        (0x9a3)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x1696)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x1696)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x15b9)
#define image_3_c_cpu_rx_wakeup_request        (0x15b9)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_start_task_initialization_task        (0x388)
#define image_4_initialization_task        (0x388)
#define image_4_start_task_processing_wakeup_request        (0x3b0)
#define image_4_processing_wakeup_request        (0x3b0)
#define image_4_start_task_debug_routine        (0x3010)
#define image_4_debug_routine        (0x3010)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0x3b80)
#define image_4_dhd_tx_post_wakeup_request        (0x3b80)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x3b30)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0x3b30)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0x39b8)
#define image_4_dhd_timer_1st_wakeup_request        (0x39b8)
#define image_4_start_task_dhd_mcast_wakeup_request        (0x33c0)
#define image_4_dhd_mcast_wakeup_request        (0x33c0)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dynamic_code_section        (0x8)
#define image_4_dynamic_code_section_proc0        (0x8)
#define image_4_dynamic_code_section_proc1        (0x78)
#define image_4_dynamic_code_section_proc2        (0xe8)
#define image_4_dynamic_code_section_proc3        (0x158)
#define image_4_dynamic_code_section_proc4        (0x1c8)
#define image_4_dynamic_code_section_proc5        (0x238)
#define image_4_dynamic_code_section_proc6        (0x2a8)
#define image_4_dynamic_code_section_proc7        (0x318)
#define image_4_processing_check_wlan_llcsnap        (0xc88)
#define image_4_processing_write_header_done        (0xc88)
#define image_4_processing_done        (0xce4)
#define image_4_action_gpe        (0x2108)
#define image_4_action_exception        (0x2110)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x2148)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x2190)
#define image_4_gpe_sop_push_replace_sram_64        (0x21a8)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x21c0)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x21d8)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x2220)
#define image_4_gpe_sop_pull_replace_sram_64        (0x2268)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x22a8)
#define image_4_gpe_replace_pointer_32_sram        (0x22f0)
#define image_4_gpe_replace_pointer_64_sram        (0x2318)
#define image_4_gpe_replace_16        (0x2340)
#define image_4_gpe_replace_32        (0x2378)
#define image_4_gpe_replace_bits_16        (0x23a0)
#define image_4_gpe_copy_add_16_cl        (0x23d0)
#define image_4_gpe_copy_add_16_sram        (0x23e0)
#define image_4_gpe_copy_bits_16_cl        (0x2428)
#define image_4_gpe_copy_bits_16_sram        (0x2438)
#define image_4_gpe_insert_16        (0x2480)
#define image_4_gpe_delete_16        (0x24e8)
#define image_4_gpe_decrement_8        (0x2528)
#define image_4_gpe_apply_icsum_16        (0x2548)
#define image_4_gpe_apply_icsum_nz_16        (0x2568)
#define image_4_gpe_compute_csum_16_cl        (0x2598)
#define image_4_gpe_compute_csum_16_sram        (0x25a8)
#define image_4_gpe_buffer_copy_16_sram        (0x25e8)
#define image_4_gpe_buffer_copy_16_ddr        (0x2618)
#define image_4_gpe_replace_add_packet_length_cl        (0x2640)
#define image_4_tcam_cmd_ic_submit        (0x2684)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x49e0)
#define image_4_c_dhd_timer_wakeup_request        (0x49e0)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x4b34)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x4b34)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x4b7c)
#define image_4_c_dhd_tx_post_wakeup_request        (0x4b7c)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x491c)
#define image_4_dhd_send_entry_to_cpu_ring        (0x491c)
#define image_4_start_task_dhd_tx_get_bq_index        (0x58c4)
#define image_4_dhd_tx_get_bq_index        (0x58c4)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x57e0)
#define image_4_dhd_tx_post_drop_packet        (0x57e0)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x5624)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x5624)
#define image_4_start_task_dhd_tx_put_bq_index        (0x5938)
#define image_4_dhd_tx_put_bq_index        (0x5938)

#else

#define image_4_start_task_initialization_task        (0xe2)
#define image_4_initialization_task        (0xe2)
#define image_4_start_task_processing_wakeup_request        (0xec)
#define image_4_processing_wakeup_request        (0xec)
#define image_4_start_task_debug_routine        (0xc04)
#define image_4_debug_routine        (0xc04)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0xee0)
#define image_4_dhd_tx_post_wakeup_request        (0xee0)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0xecc)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0xecc)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0xe6e)
#define image_4_dhd_timer_1st_wakeup_request        (0xe6e)
#define image_4_start_task_dhd_mcast_wakeup_request        (0xcf0)
#define image_4_dhd_mcast_wakeup_request        (0xcf0)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dynamic_code_section        (0x2)
#define image_4_dynamic_code_section_proc0        (0x2)
#define image_4_dynamic_code_section_proc1        (0x1e)
#define image_4_dynamic_code_section_proc2        (0x3a)
#define image_4_dynamic_code_section_proc3        (0x56)
#define image_4_dynamic_code_section_proc4        (0x72)
#define image_4_dynamic_code_section_proc5        (0x8e)
#define image_4_dynamic_code_section_proc6        (0xaa)
#define image_4_dynamic_code_section_proc7        (0xc6)
#define image_4_processing_check_wlan_llcsnap        (0x322)
#define image_4_processing_write_header_done        (0x322)
#define image_4_processing_done        (0x339)
#define image_4_action_gpe        (0x842)
#define image_4_action_exception        (0x844)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x852)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x864)
#define image_4_gpe_sop_push_replace_sram_64        (0x86a)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x870)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x876)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x888)
#define image_4_gpe_sop_pull_replace_sram_64        (0x89a)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x8aa)
#define image_4_gpe_replace_pointer_32_sram        (0x8bc)
#define image_4_gpe_replace_pointer_64_sram        (0x8c6)
#define image_4_gpe_replace_16        (0x8d0)
#define image_4_gpe_replace_32        (0x8de)
#define image_4_gpe_replace_bits_16        (0x8e8)
#define image_4_gpe_copy_add_16_cl        (0x8f4)
#define image_4_gpe_copy_add_16_sram        (0x8f8)
#define image_4_gpe_copy_bits_16_cl        (0x90a)
#define image_4_gpe_copy_bits_16_sram        (0x90e)
#define image_4_gpe_insert_16        (0x920)
#define image_4_gpe_delete_16        (0x93a)
#define image_4_gpe_decrement_8        (0x94a)
#define image_4_gpe_apply_icsum_16        (0x952)
#define image_4_gpe_apply_icsum_nz_16        (0x95a)
#define image_4_gpe_compute_csum_16_cl        (0x966)
#define image_4_gpe_compute_csum_16_sram        (0x96a)
#define image_4_gpe_buffer_copy_16_sram        (0x97a)
#define image_4_gpe_buffer_copy_16_ddr        (0x986)
#define image_4_gpe_replace_add_packet_length_cl        (0x990)
#define image_4_tcam_cmd_ic_submit        (0x9a1)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x1278)
#define image_4_c_dhd_timer_wakeup_request        (0x1278)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x12cd)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x12cd)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x12df)
#define image_4_c_dhd_tx_post_wakeup_request        (0x12df)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x1247)
#define image_4_dhd_send_entry_to_cpu_ring        (0x1247)
#define image_4_start_task_dhd_tx_get_bq_index        (0x1631)
#define image_4_dhd_tx_get_bq_index        (0x1631)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x15f8)
#define image_4_dhd_tx_post_drop_packet        (0x15f8)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x1589)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x1589)
#define image_4_start_task_dhd_tx_put_bq_index        (0x164e)
#define image_4_dhd_tx_put_bq_index        (0x164e)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND

#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {0x2794, 0x279c, 0x2794, 0x268c, 0x2684}

#else

#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {0x9e5, 0x9e7, 0x9e5, 0x9a3, 0x9a1}

#endif


#endif

