#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1C80)
#define runner_d_timer_scheduler_set		(0x1C80)
#define runner_d_start_task_flow_cache_wakeup_request		(0xDDC)
#define runner_d_flow_cache_wakeup_request		(0xDDC)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x1A60)
#define runner_d_lan_dispatch_wakeup_request		(0x1A60)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_lan_normal_wakeup_request		(0x1A8)
#define runner_d_lan_normal_wakeup_request		(0x1A8)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1DFC)
#define runner_d_free_skb_index_wakeup_request		(0x1DFC)
#define runner_d_free_skb_index_tx_abs_done		(0x1DFC)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1F74)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1F74)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x13E8)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x145C)
#define runner_d_gpe_sop_push_replace_sram_64		(0x1470)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1484)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1498)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x150C)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x155C)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x1598)
#define runner_d_gpe_replace_pointer_32_ddr		(0x15E8)
#define runner_d_gpe_replace_pointer_32_sram		(0x160C)
#define runner_d_gpe_replace_pointer_64_sram		(0x1630)
#define runner_d_gpe_replace_16		(0x1654)
#define runner_d_gpe_replace_32		(0x1688)
#define runner_d_gpe_replace_bits_16		(0x16AC)
#define runner_d_gpe_copy_add_16_cl		(0x16D8)
#define runner_d_gpe_copy_add_16_sram		(0x16E4)
#define runner_d_gpe_copy_bits_16_cl		(0x172C)
#define runner_d_gpe_copy_bits_16_sram		(0x1738)
#define runner_d_gpe_insert_16		(0x1780)
#define runner_d_gpe_delete_16		(0x17E8)
#define runner_d_gpe_decrement_8		(0x1828)
#define runner_d_gpe_apply_icsum_16		(0x184C)
#define runner_d_gpe_apply_icsum_nz_16		(0x1870)
#define runner_d_gpe_compute_csum_16_cl		(0x18AC)
#define runner_d_gpe_compute_csum_16_sram		(0x18B8)
#define runner_d_gpe_buffer_copy_16_sram		(0x18F8)
#define runner_d_gpe_buffer_copy_16_ddr		(0x1920)
#define runner_d_gpe_replace_add_packet_length_cl		(0x194C)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1D00)
#define runner_d_upstream_quasi_budget_allocate		(0x1D80)
#define runner_d_schedule_free_skb_index		(0x1DE0)

#endif
