/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_start_task_initialization_task        (0x8)
#define image_0_initialization_task        (0x8)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0xc1c)
#define image_0_ghost_reporting_1st_wakeup_request        (0xc1c)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x664)
#define image_0_budget_allocator_1st_wakeup_request        (0x664)
#define image_0_start_task_debug_routine        (0x84)
#define image_0_debug_routine        (0x84)
#define image_0_start_task_ds_tx_task_wakeup_request        (0x334)
#define image_0_ds_tx_task_wakeup_request        (0x334)
#define image_0_start_task_flush_task_1st_wakeup_request        (0x978)
#define image_0_flush_task_1st_wakeup_request        (0x978)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x1028)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x1028)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x12b0)
#define image_0_service_queues_tx_task_wakeup_request        (0x12b0)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x149c)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x149c)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x150)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x150)
#define image_0_debug_routine_handler        (0x4)

#else

#define image_0_start_task_initialization_task        (0x2)
#define image_0_initialization_task        (0x2)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0x307)
#define image_0_ghost_reporting_1st_wakeup_request        (0x307)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x199)
#define image_0_budget_allocator_1st_wakeup_request        (0x199)
#define image_0_start_task_debug_routine        (0x21)
#define image_0_debug_routine        (0x21)
#define image_0_start_task_ds_tx_task_wakeup_request        (0xcd)
#define image_0_ds_tx_task_wakeup_request        (0xcd)
#define image_0_start_task_flush_task_1st_wakeup_request        (0x25e)
#define image_0_flush_task_1st_wakeup_request        (0x25e)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x40a)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x40a)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x4ac)
#define image_0_service_queues_tx_task_wakeup_request        (0x4ac)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x527)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x527)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x54)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x54)
#define image_0_debug_routine_handler        (0x1)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_start_task_initialization_task        (0x8)
#define image_1_initialization_task        (0x8)
#define image_1_start_task_processing_wakeup_request        (0x44)
#define image_1_processing_wakeup_request        (0x44)
#define image_1_start_task_debug_routine        (0x3098)
#define image_1_debug_routine        (0x3098)
#define image_1_start_task_cpu_rx_wakeup_request        (0x3fe8)
#define image_1_cpu_rx_wakeup_request        (0x3fe8)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x43f8)
#define image_1_cpu_recycle_wakeup_request        (0x43f8)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x454c)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x454c)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4338)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4338)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0x3164)
#define image_1_cpu_rx_copy_wakeup_request        (0x3164)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x55f0)
#define image_1_spdsvc_gen_wakeup_request        (0x55f0)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x5880)
#define image_1_common_reprocessing_wakeup_request        (0x5880)
#define image_1_debug_routine_handler        (0x4)
#define image_1_processing_check_wlan_llcsnap        (0x8e0)
#define image_1_processing_done        (0xa74)
#define image_1_action_gpe        (0x2200)
#define image_1_action_exception        (0x2214)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x2254)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x2298)
#define image_1_gpe_sop_push_replace_sram_64        (0x22ac)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x22c0)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x22d4)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x2318)
#define image_1_gpe_sop_pull_replace_sram_64        (0x2368)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x23a4)
#define image_1_gpe_replace_pointer_32_sram        (0x23f4)
#define image_1_gpe_replace_pointer_64_sram        (0x2418)
#define image_1_gpe_replace_16        (0x243c)
#define image_1_gpe_replace_32        (0x2470)
#define image_1_gpe_replace_bits_16        (0x2494)
#define image_1_gpe_copy_add_16_cl        (0x24c0)
#define image_1_gpe_copy_add_16_sram        (0x24cc)
#define image_1_gpe_copy_bits_16_cl        (0x2514)
#define image_1_gpe_copy_bits_16_sram        (0x2520)
#define image_1_gpe_insert_16        (0x2568)
#define image_1_gpe_delete_16        (0x25d0)
#define image_1_gpe_decrement_8        (0x2610)
#define image_1_gpe_apply_icsum_16        (0x2634)
#define image_1_gpe_apply_icsum_nz_16        (0x2658)
#define image_1_gpe_compute_csum_16_cl        (0x2694)
#define image_1_gpe_compute_csum_16_sram        (0x26a0)
#define image_1_gpe_buffer_copy_16_sram        (0x26e0)
#define image_1_gpe_buffer_copy_16_ddr        (0x270c)
#define image_1_gpe_replace_add_packet_length_cl        (0x273c)
#define image_1_tcam_cmd_ic_submit        (0x2790)
#define image_1_tcam_cmd_outer_tpid        (0x27d4)
#define image_1_tcam_cmd_inner_tpid        (0x27ec)
#define image_1_tcam_cmd_ethertype        (0x2804)
#define image_1_tcam_cmd_outer_vid        (0x281c)
#define image_1_tcam_cmd_inner_vid        (0x2834)
#define image_1_tcam_cmd_outer_pbit        (0x284c)
#define image_1_tcam_cmd_inner_pbit        (0x2864)
#define image_1_tcam_cmd_vlan_num        (0x287c)
#define image_1_tcam_cmd_ip_protocol        (0x2894)
#define image_1_tcam_cmd_l3_protocol        (0x28ac)
#define image_1_tcam_cmd_tos        (0x28c4)
#define image_1_tcam_cmd_network_layer        (0x28dc)
#define image_1_tcam_cmd_ingress_port        (0x28fc)
#define image_1_tcam_cmd_gem_flow        (0x2914)
#define image_1_tcam_cmd_ipv6_label        (0x292c)
#define image_1_tcam_cmd_src_ip        (0x2960)
#define image_1_tcam_cmd_src_ipv6_masked        (0x29bc)
#define image_1_tcam_cmd_dst_ip        (0x29f8)
#define image_1_tcam_cmd_dst_ipv6_masked        (0x2a54)
#define image_1_tcam_cmd_src_port        (0x2a90)
#define image_1_tcam_cmd_dst_port        (0x2aa8)
#define image_1_tcam_cmd_src_mac        (0x2ac0)
#define image_1_tcam_cmd_dst_mac        (0x2aec)
#define image_1_tcam_cmd_generic_l2        (0x2b18)
#define image_1_tcam_cmd_generic_l3        (0x2b4c)
#define image_1_tcam_cmd_generic_l4        (0x2b88)

#else

#define image_1_start_task_initialization_task        (0x2)
#define image_1_initialization_task        (0x2)
#define image_1_start_task_processing_wakeup_request        (0x11)
#define image_1_processing_wakeup_request        (0x11)
#define image_1_start_task_debug_routine        (0xc26)
#define image_1_debug_routine        (0xc26)
#define image_1_start_task_cpu_rx_wakeup_request        (0xffa)
#define image_1_cpu_rx_wakeup_request        (0xffa)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x10fe)
#define image_1_cpu_recycle_wakeup_request        (0x10fe)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x1153)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x1153)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x10ce)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x10ce)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0xc59)
#define image_1_cpu_rx_copy_wakeup_request        (0xc59)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x157c)
#define image_1_spdsvc_gen_wakeup_request        (0x157c)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x1620)
#define image_1_common_reprocessing_wakeup_request        (0x1620)
#define image_1_debug_routine_handler        (0x1)
#define image_1_processing_check_wlan_llcsnap        (0x238)
#define image_1_processing_done        (0x29d)
#define image_1_action_gpe        (0x880)
#define image_1_action_exception        (0x885)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x895)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x8a6)
#define image_1_gpe_sop_push_replace_sram_64        (0x8ab)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x8b0)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x8b5)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x8c6)
#define image_1_gpe_sop_pull_replace_sram_64        (0x8da)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x8e9)
#define image_1_gpe_replace_pointer_32_sram        (0x8fd)
#define image_1_gpe_replace_pointer_64_sram        (0x906)
#define image_1_gpe_replace_16        (0x90f)
#define image_1_gpe_replace_32        (0x91c)
#define image_1_gpe_replace_bits_16        (0x925)
#define image_1_gpe_copy_add_16_cl        (0x930)
#define image_1_gpe_copy_add_16_sram        (0x933)
#define image_1_gpe_copy_bits_16_cl        (0x945)
#define image_1_gpe_copy_bits_16_sram        (0x948)
#define image_1_gpe_insert_16        (0x95a)
#define image_1_gpe_delete_16        (0x974)
#define image_1_gpe_decrement_8        (0x984)
#define image_1_gpe_apply_icsum_16        (0x98d)
#define image_1_gpe_apply_icsum_nz_16        (0x996)
#define image_1_gpe_compute_csum_16_cl        (0x9a5)
#define image_1_gpe_compute_csum_16_sram        (0x9a8)
#define image_1_gpe_buffer_copy_16_sram        (0x9b8)
#define image_1_gpe_buffer_copy_16_ddr        (0x9c3)
#define image_1_gpe_replace_add_packet_length_cl        (0x9cf)
#define image_1_tcam_cmd_ic_submit        (0x9e4)
#define image_1_tcam_cmd_outer_tpid        (0x9f5)
#define image_1_tcam_cmd_inner_tpid        (0x9fb)
#define image_1_tcam_cmd_ethertype        (0xa01)
#define image_1_tcam_cmd_outer_vid        (0xa07)
#define image_1_tcam_cmd_inner_vid        (0xa0d)
#define image_1_tcam_cmd_outer_pbit        (0xa13)
#define image_1_tcam_cmd_inner_pbit        (0xa19)
#define image_1_tcam_cmd_vlan_num        (0xa1f)
#define image_1_tcam_cmd_ip_protocol        (0xa25)
#define image_1_tcam_cmd_l3_protocol        (0xa2b)
#define image_1_tcam_cmd_tos        (0xa31)
#define image_1_tcam_cmd_network_layer        (0xa37)
#define image_1_tcam_cmd_ingress_port        (0xa3f)
#define image_1_tcam_cmd_gem_flow        (0xa45)
#define image_1_tcam_cmd_ipv6_label        (0xa4b)
#define image_1_tcam_cmd_src_ip        (0xa58)
#define image_1_tcam_cmd_src_ipv6_masked        (0xa6f)
#define image_1_tcam_cmd_dst_ip        (0xa7e)
#define image_1_tcam_cmd_dst_ipv6_masked        (0xa95)
#define image_1_tcam_cmd_src_port        (0xaa4)
#define image_1_tcam_cmd_dst_port        (0xaaa)
#define image_1_tcam_cmd_src_mac        (0xab0)
#define image_1_tcam_cmd_dst_mac        (0xabb)
#define image_1_tcam_cmd_generic_l2        (0xac6)
#define image_1_tcam_cmd_generic_l3        (0xad3)
#define image_1_tcam_cmd_generic_l4        (0xae2)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_start_task_initialization_task        (0x8)
#define image_2_initialization_task        (0x8)
#define image_2_start_task_processing_wakeup_request        (0x150)
#define image_2_processing_wakeup_request        (0x150)
#define image_2_start_task_cpu_tx_wakeup_request        (0x31a4)
#define image_2_cpu_tx_wakeup_request        (0x31a4)
#define image_2_cpu_tx_read_ring_indices        (0x31a4)
#define image_2_start_task_debug_routine        (0x44)
#define image_2_debug_routine        (0x44)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x38a4)
#define image_2_cpu_recycle_wakeup_request        (0x38a4)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x39f8)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x39f8)
#define image_2_debug_routine_handler        (0x4)
#define image_2_processing_check_wlan_llcsnap        (0x9ec)
#define image_2_processing_done        (0xb80)
#define image_2_action_gpe        (0x230c)
#define image_2_action_exception        (0x2320)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x2360)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x23a4)
#define image_2_gpe_sop_push_replace_sram_64        (0x23b8)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x23cc)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x23e0)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x2424)
#define image_2_gpe_sop_pull_replace_sram_64        (0x2474)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x24b0)
#define image_2_gpe_replace_pointer_32_sram        (0x2500)
#define image_2_gpe_replace_pointer_64_sram        (0x2524)
#define image_2_gpe_replace_16        (0x2548)
#define image_2_gpe_replace_32        (0x257c)
#define image_2_gpe_replace_bits_16        (0x25a0)
#define image_2_gpe_copy_add_16_cl        (0x25cc)
#define image_2_gpe_copy_add_16_sram        (0x25d8)
#define image_2_gpe_copy_bits_16_cl        (0x2620)
#define image_2_gpe_copy_bits_16_sram        (0x262c)
#define image_2_gpe_insert_16        (0x2674)
#define image_2_gpe_delete_16        (0x26dc)
#define image_2_gpe_decrement_8        (0x271c)
#define image_2_gpe_apply_icsum_16        (0x2740)
#define image_2_gpe_apply_icsum_nz_16        (0x2764)
#define image_2_gpe_compute_csum_16_cl        (0x27a0)
#define image_2_gpe_compute_csum_16_sram        (0x27ac)
#define image_2_gpe_buffer_copy_16_sram        (0x27ec)
#define image_2_gpe_buffer_copy_16_ddr        (0x2818)
#define image_2_gpe_replace_add_packet_length_cl        (0x2848)
#define image_2_tcam_cmd_ic_submit        (0x289c)
#define image_2_tcam_cmd_outer_tpid        (0x28e0)
#define image_2_tcam_cmd_inner_tpid        (0x28f8)
#define image_2_tcam_cmd_ethertype        (0x2910)
#define image_2_tcam_cmd_outer_vid        (0x2928)
#define image_2_tcam_cmd_inner_vid        (0x2940)
#define image_2_tcam_cmd_outer_pbit        (0x2958)
#define image_2_tcam_cmd_inner_pbit        (0x2970)
#define image_2_tcam_cmd_vlan_num        (0x2988)
#define image_2_tcam_cmd_ip_protocol        (0x29a0)
#define image_2_tcam_cmd_l3_protocol        (0x29b8)
#define image_2_tcam_cmd_tos        (0x29d0)
#define image_2_tcam_cmd_network_layer        (0x29e8)
#define image_2_tcam_cmd_ingress_port        (0x2a08)
#define image_2_tcam_cmd_gem_flow        (0x2a20)
#define image_2_tcam_cmd_ipv6_label        (0x2a38)
#define image_2_tcam_cmd_src_ip        (0x2a6c)
#define image_2_tcam_cmd_src_ipv6_masked        (0x2ac8)
#define image_2_tcam_cmd_dst_ip        (0x2b04)
#define image_2_tcam_cmd_dst_ipv6_masked        (0x2b60)
#define image_2_tcam_cmd_src_port        (0x2b9c)
#define image_2_tcam_cmd_dst_port        (0x2bb4)
#define image_2_tcam_cmd_src_mac        (0x2bcc)
#define image_2_tcam_cmd_dst_mac        (0x2bf8)
#define image_2_tcam_cmd_generic_l2        (0x2c24)
#define image_2_tcam_cmd_generic_l3        (0x2c58)
#define image_2_tcam_cmd_generic_l4        (0x2c94)

#else

#define image_2_start_task_initialization_task        (0x2)
#define image_2_initialization_task        (0x2)
#define image_2_start_task_processing_wakeup_request        (0x54)
#define image_2_processing_wakeup_request        (0x54)
#define image_2_start_task_cpu_tx_wakeup_request        (0xc69)
#define image_2_cpu_tx_wakeup_request        (0xc69)
#define image_2_cpu_tx_read_ring_indices        (0xc69)
#define image_2_start_task_debug_routine        (0x11)
#define image_2_debug_routine        (0x11)
#define image_2_start_task_cpu_recycle_wakeup_request        (0xe29)
#define image_2_cpu_recycle_wakeup_request        (0xe29)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0xe7e)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0xe7e)
#define image_2_debug_routine_handler        (0x1)
#define image_2_processing_check_wlan_llcsnap        (0x27b)
#define image_2_processing_done        (0x2e0)
#define image_2_action_gpe        (0x8c3)
#define image_2_action_exception        (0x8c8)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x8d8)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x8e9)
#define image_2_gpe_sop_push_replace_sram_64        (0x8ee)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x8f3)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x8f8)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x909)
#define image_2_gpe_sop_pull_replace_sram_64        (0x91d)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x92c)
#define image_2_gpe_replace_pointer_32_sram        (0x940)
#define image_2_gpe_replace_pointer_64_sram        (0x949)
#define image_2_gpe_replace_16        (0x952)
#define image_2_gpe_replace_32        (0x95f)
#define image_2_gpe_replace_bits_16        (0x968)
#define image_2_gpe_copy_add_16_cl        (0x973)
#define image_2_gpe_copy_add_16_sram        (0x976)
#define image_2_gpe_copy_bits_16_cl        (0x988)
#define image_2_gpe_copy_bits_16_sram        (0x98b)
#define image_2_gpe_insert_16        (0x99d)
#define image_2_gpe_delete_16        (0x9b7)
#define image_2_gpe_decrement_8        (0x9c7)
#define image_2_gpe_apply_icsum_16        (0x9d0)
#define image_2_gpe_apply_icsum_nz_16        (0x9d9)
#define image_2_gpe_compute_csum_16_cl        (0x9e8)
#define image_2_gpe_compute_csum_16_sram        (0x9eb)
#define image_2_gpe_buffer_copy_16_sram        (0x9fb)
#define image_2_gpe_buffer_copy_16_ddr        (0xa06)
#define image_2_gpe_replace_add_packet_length_cl        (0xa12)
#define image_2_tcam_cmd_ic_submit        (0xa27)
#define image_2_tcam_cmd_outer_tpid        (0xa38)
#define image_2_tcam_cmd_inner_tpid        (0xa3e)
#define image_2_tcam_cmd_ethertype        (0xa44)
#define image_2_tcam_cmd_outer_vid        (0xa4a)
#define image_2_tcam_cmd_inner_vid        (0xa50)
#define image_2_tcam_cmd_outer_pbit        (0xa56)
#define image_2_tcam_cmd_inner_pbit        (0xa5c)
#define image_2_tcam_cmd_vlan_num        (0xa62)
#define image_2_tcam_cmd_ip_protocol        (0xa68)
#define image_2_tcam_cmd_l3_protocol        (0xa6e)
#define image_2_tcam_cmd_tos        (0xa74)
#define image_2_tcam_cmd_network_layer        (0xa7a)
#define image_2_tcam_cmd_ingress_port        (0xa82)
#define image_2_tcam_cmd_gem_flow        (0xa88)
#define image_2_tcam_cmd_ipv6_label        (0xa8e)
#define image_2_tcam_cmd_src_ip        (0xa9b)
#define image_2_tcam_cmd_src_ipv6_masked        (0xab2)
#define image_2_tcam_cmd_dst_ip        (0xac1)
#define image_2_tcam_cmd_dst_ipv6_masked        (0xad8)
#define image_2_tcam_cmd_src_port        (0xae7)
#define image_2_tcam_cmd_dst_port        (0xaed)
#define image_2_tcam_cmd_src_mac        (0xaf3)
#define image_2_tcam_cmd_dst_mac        (0xafe)
#define image_2_tcam_cmd_generic_l2        (0xb09)
#define image_2_tcam_cmd_generic_l3        (0xb16)
#define image_2_tcam_cmd_generic_l4        (0xb25)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_start_task_initialization_task        (0x8)
#define image_3_initialization_task        (0x8)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x1320)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x1320)
#define image_3_start_task_tx_task_1st_wakeup_request        (0x4d8)
#define image_3_tx_task_1st_wakeup_request        (0x4d8)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x15b0)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x15b0)
#define image_3_start_task_epon_tx_task_wakeup_request        (0xa1c)
#define image_3_epon_tx_task_wakeup_request        (0xa1c)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0xcfc)
#define image_3_budget_allocator_1st_wakeup_request        (0xcfc)
#define image_3_start_task_debug_routine        (0xcc)
#define image_3_debug_routine        (0xcc)
#define image_3_start_task_gpon_control_wakeup_request        (0x198)
#define image_3_gpon_control_wakeup_request        (0x198)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x1060)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x1060)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x116c)
#define image_3_flush_task_1st_wakeup_request        (0x116c)
#define image_3_start_task_wan_tx_ddr_read_1st_wakeup_request        (0x111c)
#define image_3_wan_tx_ddr_read_1st_wakeup_request        (0x111c)
#define image_3_start_task_wan_tx_psram_write_1st_wakeup_request        (0x1144)
#define image_3_wan_tx_psram_write_1st_wakeup_request        (0x1144)
#define image_3_debug_routine_handler        (0x4)

#else

#define image_3_start_task_initialization_task        (0x2)
#define image_3_initialization_task        (0x2)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x4c8)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x4c8)
#define image_3_start_task_tx_task_1st_wakeup_request        (0x136)
#define image_3_tx_task_1st_wakeup_request        (0x136)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x56c)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x56c)
#define image_3_start_task_epon_tx_task_wakeup_request        (0x287)
#define image_3_epon_tx_task_wakeup_request        (0x287)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0x33f)
#define image_3_budget_allocator_1st_wakeup_request        (0x33f)
#define image_3_start_task_debug_routine        (0x33)
#define image_3_debug_routine        (0x33)
#define image_3_start_task_gpon_control_wakeup_request        (0x66)
#define image_3_gpon_control_wakeup_request        (0x66)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x418)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x418)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x45b)
#define image_3_flush_task_1st_wakeup_request        (0x45b)
#define image_3_start_task_wan_tx_ddr_read_1st_wakeup_request        (0x447)
#define image_3_wan_tx_ddr_read_1st_wakeup_request        (0x447)
#define image_3_start_task_wan_tx_psram_write_1st_wakeup_request        (0x451)
#define image_3_wan_tx_psram_write_1st_wakeup_request        (0x451)
#define image_3_debug_routine_handler        (0x1)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_start_task_initialization_task        (0x8)
#define image_4_initialization_task        (0x8)
#define image_4_start_task_processing_wakeup_request        (0x44)
#define image_4_processing_wakeup_request        (0x44)
#define image_4_start_task_debug_routine        (0x3098)
#define image_4_debug_routine        (0x3098)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0x3d10)
#define image_4_dhd_tx_post_wakeup_request        (0x3d10)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x3cb8)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0x3cb8)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0x3b28)
#define image_4_dhd_timer_1st_wakeup_request        (0x3b28)
#define image_4_start_task_dhd_mcast_wakeup_request        (0x3504)
#define image_4_dhd_mcast_wakeup_request        (0x3504)
#define image_4_debug_routine_handler        (0x4)
#define image_4_processing_check_wlan_llcsnap        (0x8e0)
#define image_4_processing_done        (0xa74)
#define image_4_action_gpe        (0x2200)
#define image_4_action_exception        (0x2214)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x2254)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x2298)
#define image_4_gpe_sop_push_replace_sram_64        (0x22ac)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x22c0)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x22d4)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x2318)
#define image_4_gpe_sop_pull_replace_sram_64        (0x2368)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x23a4)
#define image_4_gpe_replace_pointer_32_sram        (0x23f4)
#define image_4_gpe_replace_pointer_64_sram        (0x2418)
#define image_4_gpe_replace_16        (0x243c)
#define image_4_gpe_replace_32        (0x2470)
#define image_4_gpe_replace_bits_16        (0x2494)
#define image_4_gpe_copy_add_16_cl        (0x24c0)
#define image_4_gpe_copy_add_16_sram        (0x24cc)
#define image_4_gpe_copy_bits_16_cl        (0x2514)
#define image_4_gpe_copy_bits_16_sram        (0x2520)
#define image_4_gpe_insert_16        (0x2568)
#define image_4_gpe_delete_16        (0x25d0)
#define image_4_gpe_decrement_8        (0x2610)
#define image_4_gpe_apply_icsum_16        (0x2634)
#define image_4_gpe_apply_icsum_nz_16        (0x2658)
#define image_4_gpe_compute_csum_16_cl        (0x2694)
#define image_4_gpe_compute_csum_16_sram        (0x26a0)
#define image_4_gpe_buffer_copy_16_sram        (0x26e0)
#define image_4_gpe_buffer_copy_16_ddr        (0x270c)
#define image_4_gpe_replace_add_packet_length_cl        (0x273c)
#define image_4_tcam_cmd_ic_submit        (0x2790)
#define image_4_tcam_cmd_outer_tpid        (0x27d4)
#define image_4_tcam_cmd_inner_tpid        (0x27ec)
#define image_4_tcam_cmd_ethertype        (0x2804)
#define image_4_tcam_cmd_outer_vid        (0x281c)
#define image_4_tcam_cmd_inner_vid        (0x2834)
#define image_4_tcam_cmd_outer_pbit        (0x284c)
#define image_4_tcam_cmd_inner_pbit        (0x2864)
#define image_4_tcam_cmd_vlan_num        (0x287c)
#define image_4_tcam_cmd_ip_protocol        (0x2894)
#define image_4_tcam_cmd_l3_protocol        (0x28ac)
#define image_4_tcam_cmd_tos        (0x28c4)
#define image_4_tcam_cmd_network_layer        (0x28dc)
#define image_4_tcam_cmd_ingress_port        (0x28fc)
#define image_4_tcam_cmd_gem_flow        (0x2914)
#define image_4_tcam_cmd_ipv6_label        (0x292c)
#define image_4_tcam_cmd_src_ip        (0x2960)
#define image_4_tcam_cmd_src_ipv6_masked        (0x29bc)
#define image_4_tcam_cmd_dst_ip        (0x29f8)
#define image_4_tcam_cmd_dst_ipv6_masked        (0x2a54)
#define image_4_tcam_cmd_src_port        (0x2a90)
#define image_4_tcam_cmd_dst_port        (0x2aa8)
#define image_4_tcam_cmd_src_mac        (0x2ac0)
#define image_4_tcam_cmd_dst_mac        (0x2aec)
#define image_4_tcam_cmd_generic_l2        (0x2b18)
#define image_4_tcam_cmd_generic_l3        (0x2b4c)
#define image_4_tcam_cmd_generic_l4        (0x2b88)

#else

#define image_4_start_task_initialization_task        (0x2)
#define image_4_initialization_task        (0x2)
#define image_4_start_task_processing_wakeup_request        (0x11)
#define image_4_processing_wakeup_request        (0x11)
#define image_4_start_task_debug_routine        (0xc26)
#define image_4_debug_routine        (0xc26)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0xf44)
#define image_4_dhd_tx_post_wakeup_request        (0xf44)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0xf2e)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0xf2e)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0xeca)
#define image_4_dhd_timer_1st_wakeup_request        (0xeca)
#define image_4_start_task_dhd_mcast_wakeup_request        (0xd41)
#define image_4_dhd_mcast_wakeup_request        (0xd41)
#define image_4_debug_routine_handler        (0x1)
#define image_4_processing_check_wlan_llcsnap        (0x238)
#define image_4_processing_done        (0x29d)
#define image_4_action_gpe        (0x880)
#define image_4_action_exception        (0x885)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x895)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x8a6)
#define image_4_gpe_sop_push_replace_sram_64        (0x8ab)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x8b0)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x8b5)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x8c6)
#define image_4_gpe_sop_pull_replace_sram_64        (0x8da)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x8e9)
#define image_4_gpe_replace_pointer_32_sram        (0x8fd)
#define image_4_gpe_replace_pointer_64_sram        (0x906)
#define image_4_gpe_replace_16        (0x90f)
#define image_4_gpe_replace_32        (0x91c)
#define image_4_gpe_replace_bits_16        (0x925)
#define image_4_gpe_copy_add_16_cl        (0x930)
#define image_4_gpe_copy_add_16_sram        (0x933)
#define image_4_gpe_copy_bits_16_cl        (0x945)
#define image_4_gpe_copy_bits_16_sram        (0x948)
#define image_4_gpe_insert_16        (0x95a)
#define image_4_gpe_delete_16        (0x974)
#define image_4_gpe_decrement_8        (0x984)
#define image_4_gpe_apply_icsum_16        (0x98d)
#define image_4_gpe_apply_icsum_nz_16        (0x996)
#define image_4_gpe_compute_csum_16_cl        (0x9a5)
#define image_4_gpe_compute_csum_16_sram        (0x9a8)
#define image_4_gpe_buffer_copy_16_sram        (0x9b8)
#define image_4_gpe_buffer_copy_16_ddr        (0x9c3)
#define image_4_gpe_replace_add_packet_length_cl        (0x9cf)
#define image_4_tcam_cmd_ic_submit        (0x9e4)
#define image_4_tcam_cmd_outer_tpid        (0x9f5)
#define image_4_tcam_cmd_inner_tpid        (0x9fb)
#define image_4_tcam_cmd_ethertype        (0xa01)
#define image_4_tcam_cmd_outer_vid        (0xa07)
#define image_4_tcam_cmd_inner_vid        (0xa0d)
#define image_4_tcam_cmd_outer_pbit        (0xa13)
#define image_4_tcam_cmd_inner_pbit        (0xa19)
#define image_4_tcam_cmd_vlan_num        (0xa1f)
#define image_4_tcam_cmd_ip_protocol        (0xa25)
#define image_4_tcam_cmd_l3_protocol        (0xa2b)
#define image_4_tcam_cmd_tos        (0xa31)
#define image_4_tcam_cmd_network_layer        (0xa37)
#define image_4_tcam_cmd_ingress_port        (0xa3f)
#define image_4_tcam_cmd_gem_flow        (0xa45)
#define image_4_tcam_cmd_ipv6_label        (0xa4b)
#define image_4_tcam_cmd_src_ip        (0xa58)
#define image_4_tcam_cmd_src_ipv6_masked        (0xa6f)
#define image_4_tcam_cmd_dst_ip        (0xa7e)
#define image_4_tcam_cmd_dst_ipv6_masked        (0xa95)
#define image_4_tcam_cmd_src_port        (0xaa4)
#define image_4_tcam_cmd_dst_port        (0xaaa)
#define image_4_tcam_cmd_src_mac        (0xab0)
#define image_4_tcam_cmd_dst_mac        (0xabb)
#define image_4_tcam_cmd_generic_l2        (0xac6)
#define image_4_tcam_cmd_generic_l3        (0xad3)
#define image_4_tcam_cmd_generic_l4        (0xae2)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5_start_task_initialization_task        (0x8)
#define image_5_initialization_task        (0x8)
#define image_5_start_task_processing_wakeup_request        (0x44)
#define image_5_processing_wakeup_request        (0x44)
#define image_5_start_task_debug_routine        (0x3098)
#define image_5_debug_routine        (0x3098)
#define image_5_start_task_dhd_tx_complete_wakeup_request        (0x3244)
#define image_5_dhd_tx_complete_wakeup_request        (0x3244)
#define image_5_start_task_dhd_rx_complete_wakeup_request        (0x358c)
#define image_5_dhd_rx_complete_wakeup_request        (0x358c)
#define image_5_debug_routine_handler        (0x4)
#define image_5_processing_check_wlan_llcsnap        (0x8e0)
#define image_5_processing_done        (0xa74)
#define image_5_action_gpe        (0x2200)
#define image_5_action_exception        (0x2214)
#define image_5_gpe_sop_push_replace_ddr_sram_32        (0x2254)
#define image_5_gpe_sop_push_replace_sram_32_64        (0x2298)
#define image_5_gpe_sop_push_replace_sram_64        (0x22ac)
#define image_5_gpe_sop_push_replace_sram_64_32        (0x22c0)
#define image_5_gpe_sop_pull_replace_ddr_sram_32        (0x22d4)
#define image_5_gpe_sop_pull_replace_sram_32_64        (0x2318)
#define image_5_gpe_sop_pull_replace_sram_64        (0x2368)
#define image_5_gpe_sop_pull_replace_sram_64_32        (0x23a4)
#define image_5_gpe_replace_pointer_32_sram        (0x23f4)
#define image_5_gpe_replace_pointer_64_sram        (0x2418)
#define image_5_gpe_replace_16        (0x243c)
#define image_5_gpe_replace_32        (0x2470)
#define image_5_gpe_replace_bits_16        (0x2494)
#define image_5_gpe_copy_add_16_cl        (0x24c0)
#define image_5_gpe_copy_add_16_sram        (0x24cc)
#define image_5_gpe_copy_bits_16_cl        (0x2514)
#define image_5_gpe_copy_bits_16_sram        (0x2520)
#define image_5_gpe_insert_16        (0x2568)
#define image_5_gpe_delete_16        (0x25d0)
#define image_5_gpe_decrement_8        (0x2610)
#define image_5_gpe_apply_icsum_16        (0x2634)
#define image_5_gpe_apply_icsum_nz_16        (0x2658)
#define image_5_gpe_compute_csum_16_cl        (0x2694)
#define image_5_gpe_compute_csum_16_sram        (0x26a0)
#define image_5_gpe_buffer_copy_16_sram        (0x26e0)
#define image_5_gpe_buffer_copy_16_ddr        (0x270c)
#define image_5_gpe_replace_add_packet_length_cl        (0x273c)
#define image_5_tcam_cmd_ic_submit        (0x2790)
#define image_5_tcam_cmd_outer_tpid        (0x27d4)
#define image_5_tcam_cmd_inner_tpid        (0x27ec)
#define image_5_tcam_cmd_ethertype        (0x2804)
#define image_5_tcam_cmd_outer_vid        (0x281c)
#define image_5_tcam_cmd_inner_vid        (0x2834)
#define image_5_tcam_cmd_outer_pbit        (0x284c)
#define image_5_tcam_cmd_inner_pbit        (0x2864)
#define image_5_tcam_cmd_vlan_num        (0x287c)
#define image_5_tcam_cmd_ip_protocol        (0x2894)
#define image_5_tcam_cmd_l3_protocol        (0x28ac)
#define image_5_tcam_cmd_tos        (0x28c4)
#define image_5_tcam_cmd_network_layer        (0x28dc)
#define image_5_tcam_cmd_ingress_port        (0x28fc)
#define image_5_tcam_cmd_gem_flow        (0x2914)
#define image_5_tcam_cmd_ipv6_label        (0x292c)
#define image_5_tcam_cmd_src_ip        (0x2960)
#define image_5_tcam_cmd_src_ipv6_masked        (0x29bc)
#define image_5_tcam_cmd_dst_ip        (0x29f8)
#define image_5_tcam_cmd_dst_ipv6_masked        (0x2a54)
#define image_5_tcam_cmd_src_port        (0x2a90)
#define image_5_tcam_cmd_dst_port        (0x2aa8)
#define image_5_tcam_cmd_src_mac        (0x2ac0)
#define image_5_tcam_cmd_dst_mac        (0x2aec)
#define image_5_tcam_cmd_generic_l2        (0x2b18)
#define image_5_tcam_cmd_generic_l3        (0x2b4c)
#define image_5_tcam_cmd_generic_l4        (0x2b88)

#else

#define image_5_start_task_initialization_task        (0x2)
#define image_5_initialization_task        (0x2)
#define image_5_start_task_processing_wakeup_request        (0x11)
#define image_5_processing_wakeup_request        (0x11)
#define image_5_start_task_debug_routine        (0xc26)
#define image_5_debug_routine        (0xc26)
#define image_5_start_task_dhd_tx_complete_wakeup_request        (0xc91)
#define image_5_dhd_tx_complete_wakeup_request        (0xc91)
#define image_5_start_task_dhd_rx_complete_wakeup_request        (0xd63)
#define image_5_dhd_rx_complete_wakeup_request        (0xd63)
#define image_5_debug_routine_handler        (0x1)
#define image_5_processing_check_wlan_llcsnap        (0x238)
#define image_5_processing_done        (0x29d)
#define image_5_action_gpe        (0x880)
#define image_5_action_exception        (0x885)
#define image_5_gpe_sop_push_replace_ddr_sram_32        (0x895)
#define image_5_gpe_sop_push_replace_sram_32_64        (0x8a6)
#define image_5_gpe_sop_push_replace_sram_64        (0x8ab)
#define image_5_gpe_sop_push_replace_sram_64_32        (0x8b0)
#define image_5_gpe_sop_pull_replace_ddr_sram_32        (0x8b5)
#define image_5_gpe_sop_pull_replace_sram_32_64        (0x8c6)
#define image_5_gpe_sop_pull_replace_sram_64        (0x8da)
#define image_5_gpe_sop_pull_replace_sram_64_32        (0x8e9)
#define image_5_gpe_replace_pointer_32_sram        (0x8fd)
#define image_5_gpe_replace_pointer_64_sram        (0x906)
#define image_5_gpe_replace_16        (0x90f)
#define image_5_gpe_replace_32        (0x91c)
#define image_5_gpe_replace_bits_16        (0x925)
#define image_5_gpe_copy_add_16_cl        (0x930)
#define image_5_gpe_copy_add_16_sram        (0x933)
#define image_5_gpe_copy_bits_16_cl        (0x945)
#define image_5_gpe_copy_bits_16_sram        (0x948)
#define image_5_gpe_insert_16        (0x95a)
#define image_5_gpe_delete_16        (0x974)
#define image_5_gpe_decrement_8        (0x984)
#define image_5_gpe_apply_icsum_16        (0x98d)
#define image_5_gpe_apply_icsum_nz_16        (0x996)
#define image_5_gpe_compute_csum_16_cl        (0x9a5)
#define image_5_gpe_compute_csum_16_sram        (0x9a8)
#define image_5_gpe_buffer_copy_16_sram        (0x9b8)
#define image_5_gpe_buffer_copy_16_ddr        (0x9c3)
#define image_5_gpe_replace_add_packet_length_cl        (0x9cf)
#define image_5_tcam_cmd_ic_submit        (0x9e4)
#define image_5_tcam_cmd_outer_tpid        (0x9f5)
#define image_5_tcam_cmd_inner_tpid        (0x9fb)
#define image_5_tcam_cmd_ethertype        (0xa01)
#define image_5_tcam_cmd_outer_vid        (0xa07)
#define image_5_tcam_cmd_inner_vid        (0xa0d)
#define image_5_tcam_cmd_outer_pbit        (0xa13)
#define image_5_tcam_cmd_inner_pbit        (0xa19)
#define image_5_tcam_cmd_vlan_num        (0xa1f)
#define image_5_tcam_cmd_ip_protocol        (0xa25)
#define image_5_tcam_cmd_l3_protocol        (0xa2b)
#define image_5_tcam_cmd_tos        (0xa31)
#define image_5_tcam_cmd_network_layer        (0xa37)
#define image_5_tcam_cmd_ingress_port        (0xa3f)
#define image_5_tcam_cmd_gem_flow        (0xa45)
#define image_5_tcam_cmd_ipv6_label        (0xa4b)
#define image_5_tcam_cmd_src_ip        (0xa58)
#define image_5_tcam_cmd_src_ipv6_masked        (0xa6f)
#define image_5_tcam_cmd_dst_ip        (0xa7e)
#define image_5_tcam_cmd_dst_ipv6_masked        (0xa95)
#define image_5_tcam_cmd_src_port        (0xaa4)
#define image_5_tcam_cmd_dst_port        (0xaaa)
#define image_5_tcam_cmd_src_mac        (0xab0)
#define image_5_tcam_cmd_dst_mac        (0xabb)
#define image_5_tcam_cmd_generic_l2        (0xac6)
#define image_5_tcam_cmd_generic_l3        (0xad3)
#define image_5_tcam_cmd_generic_l4        (0xae2)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x29f8, 0x2b04, INVALID_LABEL_ADDRESS, 0x29f8, 0x29f8}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2a54, 0x2b60, INVALID_LABEL_ADDRESS, 0x2a54, 0x2a54}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2aec, 0x2bf8, INVALID_LABEL_ADDRESS, 0x2aec, 0x2aec}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2aa8, 0x2bb4, INVALID_LABEL_ADDRESS, 0x2aa8, 0x2aa8}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2804, 0x2910, INVALID_LABEL_ADDRESS, 0x2804, 0x2804}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2914, 0x2a20, INVALID_LABEL_ADDRESS, 0x2914, 0x2914}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b18, 0x2c24, INVALID_LABEL_ADDRESS, 0x2b18, 0x2b18}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b4c, 0x2c58, INVALID_LABEL_ADDRESS, 0x2b4c, 0x2b4c}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2b88, 0x2c94, INVALID_LABEL_ADDRESS, 0x2b88, 0x2b88}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2790, 0x289c, INVALID_LABEL_ADDRESS, 0x2790, 0x2790}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28fc, 0x2a08, INVALID_LABEL_ADDRESS, 0x28fc, 0x28fc}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2864, 0x2970, INVALID_LABEL_ADDRESS, 0x2864, 0x2864}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x27ec, 0x28f8, INVALID_LABEL_ADDRESS, 0x27ec, 0x27ec}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2834, 0x2940, INVALID_LABEL_ADDRESS, 0x2834, 0x2834}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2894, 0x29a0, INVALID_LABEL_ADDRESS, 0x2894, 0x2894}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x292c, 0x2a38, INVALID_LABEL_ADDRESS, 0x292c, 0x292c}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28ac, 0x29b8, INVALID_LABEL_ADDRESS, 0x28ac, 0x28ac}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28dc, 0x29e8, INVALID_LABEL_ADDRESS, 0x28dc, 0x28dc}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x284c, 0x2958, INVALID_LABEL_ADDRESS, 0x284c, 0x284c}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x27d4, 0x28e0, INVALID_LABEL_ADDRESS, 0x27d4, 0x27d4}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x281c, 0x2928, INVALID_LABEL_ADDRESS, 0x281c, 0x281c}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2960, 0x2a6c, INVALID_LABEL_ADDRESS, 0x2960, 0x2960}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x29bc, 0x2ac8, INVALID_LABEL_ADDRESS, 0x29bc, 0x29bc}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2ac0, 0x2bcc, INVALID_LABEL_ADDRESS, 0x2ac0, 0x2ac0}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2a90, 0x2b9c, INVALID_LABEL_ADDRESS, 0x2a90, 0x2a90}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x28c4, 0x29d0, INVALID_LABEL_ADDRESS, 0x28c4, 0x28c4}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x287c, 0x2988, INVALID_LABEL_ADDRESS, 0x287c, 0x287c}

#else

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa7e, 0xac1, INVALID_LABEL_ADDRESS, 0xa7e, 0xa7e}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa95, 0xad8, INVALID_LABEL_ADDRESS, 0xa95, 0xa95}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xabb, 0xafe, INVALID_LABEL_ADDRESS, 0xabb, 0xabb}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xaaa, 0xaed, INVALID_LABEL_ADDRESS, 0xaaa, 0xaaa}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa01, 0xa44, INVALID_LABEL_ADDRESS, 0xa01, 0xa01}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa45, 0xa88, INVALID_LABEL_ADDRESS, 0xa45, 0xa45}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xac6, 0xb09, INVALID_LABEL_ADDRESS, 0xac6, 0xac6}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xad3, 0xb16, INVALID_LABEL_ADDRESS, 0xad3, 0xad3}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xae2, 0xb25, INVALID_LABEL_ADDRESS, 0xae2, 0xae2}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x9e4, 0xa27, INVALID_LABEL_ADDRESS, 0x9e4, 0x9e4}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa3f, 0xa82, INVALID_LABEL_ADDRESS, 0xa3f, 0xa3f}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa19, 0xa5c, INVALID_LABEL_ADDRESS, 0xa19, 0xa19}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x9fb, 0xa3e, INVALID_LABEL_ADDRESS, 0x9fb, 0x9fb}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa0d, 0xa50, INVALID_LABEL_ADDRESS, 0xa0d, 0xa0d}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa25, 0xa68, INVALID_LABEL_ADDRESS, 0xa25, 0xa25}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa4b, 0xa8e, INVALID_LABEL_ADDRESS, 0xa4b, 0xa4b}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa2b, 0xa6e, INVALID_LABEL_ADDRESS, 0xa2b, 0xa2b}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa37, 0xa7a, INVALID_LABEL_ADDRESS, 0xa37, 0xa37}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa13, 0xa56, INVALID_LABEL_ADDRESS, 0xa13, 0xa13}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x9f5, 0xa38, INVALID_LABEL_ADDRESS, 0x9f5, 0x9f5}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa07, 0xa4a, INVALID_LABEL_ADDRESS, 0xa07, 0xa07}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa58, 0xa9b, INVALID_LABEL_ADDRESS, 0xa58, 0xa58}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa6f, 0xab2, INVALID_LABEL_ADDRESS, 0xa6f, 0xa6f}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xab0, 0xaf3, INVALID_LABEL_ADDRESS, 0xab0, 0xab0}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xaa4, 0xae7, INVALID_LABEL_ADDRESS, 0xaa4, 0xaa4}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa31, 0xa74, INVALID_LABEL_ADDRESS, 0xa31, 0xa31}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xa1f, 0xa62, INVALID_LABEL_ADDRESS, 0xa1f, 0xa1f}

#endif


#endif

