language: c
dist: trusty

sudo: true

cache: ccache

# Everything except samba and ctdb (long tests)
env:
  - TASK=samba-xc
  - TASK=samba-ctdb
  - TASK=samba-libs
  - TASK=samba-static
  - TASK=ldb
  - TASK=tdb
  - TASK=talloc
  - TASK=replace
  - TASK=tevent
  - TASK=pidl

# Fail everything after the first job fails
matrix:
  fast_finish: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --assume-yes screen git build-essential libacl1-dev libattr1-dev libblkid-dev libgnutls-dev libreadline-dev python-dev libpam0g-dev python-dnspython gdb pkg-config libpopt-dev libldap2-dev dnsutils libbsd-dev attr krb5-user docbook-xsl libcups2-dev acl bison debhelper docbook-xml docbook-xsl flex libaio-dev libbsd-dev libcap-dev libcups2-dev libncurses5-dev libpam0g-dev libpopt-dev libreadline-dev perl perl-modules libparse-yapp-perl pkg-config python-all-dev python-dnspython xsltproc zlib1g-dev autoconf

script:
 - git fetch --unshallow
 - ./script/autobuild.py --tail --testbase=/tmp $TASK
