/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#if defined(SUPPORT_DM_PURE181) || defined(SUPPORT_DM_DETECT)

#include "mdm_types.h"
#include "rcl.h"
#include "stl.h"


#pragma weak oidInfoArray_dev2
#pragma weak cnt_oidInfoArray_dev2
#pragma weak mdm_getPtrs_oidInfoArray_dev2

const MdmOidInfoEntry oidInfoArray_dev2[]= { 
{1000, "Device.", 
NULL, rcl_dev2DeviceObject, NULL, stl_dev2DeviceObject, NULL},

#if defined(DMP_X_BROADCOM_COM_EPON_1)
{2010, "Device.X_BROADCOM_COM_EPON.", 
NULL, rcl_eponObject, NULL, stl_eponObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_DPOE_1)
{2020, "Device.X_BROADCOM_COM_DPoE.", 
NULL, rcl_dPoEObject, NULL, stl_dPoEObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_DPOE_1) && defined(DMP_X_BROADCOM_COM_DPOE_1)
{2021, "Device.X_BROADCOM_COM_DPoE.DPoE_FirmwareInfo.", 
NULL, rcl_dPoEFirmwareInfoObject, NULL, stl_dPoEFirmwareInfoObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_DPOE_1) && defined(DMP_X_BROADCOM_COM_DPOE_1)
{2022, "Device.X_BROADCOM_COM_DPoE.DPoE_ChipInfo.", 
NULL, rcl_dPoEChipInfoObject, NULL, stl_dPoEChipInfoObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_DPOE_1) && defined(DMP_X_BROADCOM_COM_DPOE_1)
{2023, "Device.X_BROADCOM_COM_DPoE.DPoE_OnuLinkStatistics.{i}.", 
NULL, rcl_dPoEOnuLinkStatisticsObject, NULL, stl_dPoEOnuLinkStatisticsObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_EPON_1)
{2500, "Device.X_BROADCOM_COM_AppCfg.EponappCfg.", 
NULL, rcl_eponappCfgObject, NULL, stl_eponappCfgObject, NULL},
#endif

{3130, "Device.X_BROADCOM_COM_AppCfg.", 
NULL, rcl_appCfgObject, NULL, stl_appCfgObject, NULL},

#if defined(DMP_X_BROADCOM_COM_EPON_1)
{3327, "Device.X_BROADCOM_COM_AppCfg.EponMdCfg.", 
NULL, rcl_eponMdCfgObject, NULL, stl_eponMdCfgObject, NULL},
#endif

#if defined(DMP_X_BROADCOM_COM_EPON_1)
{3328, "Device.X_BROADCOM_COM_AppCfg.EponHalThreadCfg.", 
NULL, rcl_eponHalThreadCfgObject, NULL, stl_eponHalThreadCfgObject, NULL},
#endif

{3339, "Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg.", 
NULL, rcl_bcmMsgdCfgObject, NULL, stl_bcmMsgdCfgObject, NULL},


};

int cnt_oidInfoArray_dev2 = (sizeof(oidInfoArray_dev2) / sizeof(MdmOidInfoEntry));

void mdm_getPtrs_oidInfoArray_dev2(const MdmOidInfoEntry **begin, const MdmOidInfoEntry **end)
{
   *begin = oidInfoArray_dev2;
   *end = &(oidInfoArray_dev2 [cnt_oidInfoArray_dev2 - 1]);
}
#endif  /* defined(SUPPORT_DM_PURE181) || defined(SUPPORT_DM_DETECT) */ 
