# Copyright 2020  Hon Hai Precision Ind. Co. Ltd.
#  All Rights Reserved.

TARGET_PLATFORM_ARCH := arm
TARGET_PLATFORM_CROSS_COMPILE_USER := arm-buildroot-linux-gnueabi-
TOOLCHAIN_PATH_USER := /opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin
TOOLCHAIN_PATH_KERN := /opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin
BCMDRIVER_WL_IMPL := impl63
KERNEL_PATH := $(BUILD_DIR)/kernel/linux-4.1
#KERNELRELEASE := 4.1.52
LIB_OPENSSLDIR := $(BUILD_DIR)/userspace/public/libs/openssl/openssl-1.1.1b

BCA_HNDROUTER=y
CONFIG_PPTP=n
#CONFIG_BPA=y
CONFIG_RIP=n
CONFIG_NEW_WANDETECT=y
CONFIG_SINGLE_PROCESS_PPPOE=n
MPOE_ENABLE_FLAG=n
CONFIG_STATIC_PPPOE=n
IPV6RD_ENABLE_FLAG=y
INCLUDE_IPV6_FLAG=y
CONFIG_PPTP=y
CONFIG_RIP=y
CONFIG_SINGLE_PROCESS_PPPOE=y
MPOE_ENABLE_FLAG=y
CONFIG_STATIC_PPPOE=y
SAMBA_ENABLE_FLAG=n
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y
FTP_ACCESS_USB_FLAG=n
CONFIG_DLNA=n
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=n
CONFIG_KERNEL_2_6_36=n
CONFIG_OPENVPN=n
CONFIG_TCPDUMP=n
CONFIG_DOWNLOADER=n
CONFIG_KWILT=n
CONFIG_LINK_AGG=n
CONFIG_PORTTRUNKING_SUPPORT=n
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=n
CONFIG_LIGHTTPD=n
CONFIG_DAL=y
CONFIG_DAL_FOR_DIL=y
CONFIG_CIRCLEV2_PARENTAL_CONTROL=n
#Note: Funjsq and CircleV2 all need ipset tool.
CONFIG_IPSET=n
CONFIG_WGET=y
IPERF_ENABLE_FLAG=n
CONFIG_CLOUD_XAGENT_CONF=y
CONFIG_NETATALK_3_1_8=n
CONFIG_CIRCLE_PARENTAL_CONTROL=n
