/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_start_task_initialization_task        (0x388)
#define image_0_initialization_task        (0x388)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0x550)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0x550)
#define image_0_start_task_tx_task_1st_wakeup_request        (0x9d8)
#define image_0_tx_task_1st_wakeup_request        (0x9d8)
#define image_0_start_task_timer_common_task_wakeup_request        (0x1318)
#define image_0_timer_common_task_wakeup_request        (0x1318)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0xea0)
#define image_0_budget_allocator_1st_wakeup_request        (0xea0)
#define image_0_start_task_debug_routine        (0x3f4)
#define image_0_debug_routine        (0x3f4)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x13c0)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x13c0)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x1608)
#define image_0_service_queues_tx_task_wakeup_request        (0x1608)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x17d0)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x17d0)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dynamic_code_section        (0x8)
#define image_0_dynamic_code_section_proc0        (0x8)
#define image_0_dynamic_code_section_proc1        (0x78)
#define image_0_dynamic_code_section_proc2        (0xe8)
#define image_0_dynamic_code_section_proc3        (0x158)
#define image_0_dynamic_code_section_proc4        (0x1c8)
#define image_0_dynamic_code_section_proc5        (0x238)
#define image_0_dynamic_code_section_proc6        (0x2a8)
#define image_0_dynamic_code_section_proc7        (0x318)
#define image_0_start_task_iptv_handler        (0x3138)
#define image_0_iptv_handler        (0x3138)
#define image_0_start_task_mcast_flow_lkp_and_fwd        (0x3028)
#define image_0_mcast_flow_lkp_and_fwd        (0x3028)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x1afc)
#define image_0_memcpy_abs_to_sbpm        (0x1afc)
#define image_0_start_task_processing_wakeup_request        (0x1ce8)
#define image_0_processing_wakeup_request        (0x1ce8)

#else

#define image_0_start_task_initialization_task        (0xe2)
#define image_0_initialization_task        (0xe2)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0x154)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0x154)
#define image_0_start_task_tx_task_1st_wakeup_request        (0x276)
#define image_0_tx_task_1st_wakeup_request        (0x276)
#define image_0_start_task_timer_common_task_wakeup_request        (0x4c6)
#define image_0_timer_common_task_wakeup_request        (0x4c6)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x3a8)
#define image_0_budget_allocator_1st_wakeup_request        (0x3a8)
#define image_0_start_task_debug_routine        (0xfd)
#define image_0_debug_routine        (0xfd)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x4f0)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x4f0)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x582)
#define image_0_service_queues_tx_task_wakeup_request        (0x582)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x5f4)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x5f4)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dynamic_code_section        (0x2)
#define image_0_dynamic_code_section_proc0        (0x2)
#define image_0_dynamic_code_section_proc1        (0x1e)
#define image_0_dynamic_code_section_proc2        (0x3a)
#define image_0_dynamic_code_section_proc3        (0x56)
#define image_0_dynamic_code_section_proc4        (0x72)
#define image_0_dynamic_code_section_proc5        (0x8e)
#define image_0_dynamic_code_section_proc6        (0xaa)
#define image_0_dynamic_code_section_proc7        (0xc6)
#define image_0_start_task_iptv_handler        (0xc4e)
#define image_0_iptv_handler        (0xc4e)
#define image_0_start_task_mcast_flow_lkp_and_fwd        (0xc0a)
#define image_0_mcast_flow_lkp_and_fwd        (0xc0a)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x6bf)
#define image_0_memcpy_abs_to_sbpm        (0x6bf)
#define image_0_start_task_processing_wakeup_request        (0x73a)
#define image_0_processing_wakeup_request        (0x73a)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_start_task_initialization_task        (0x388)
#define image_1_initialization_task        (0x388)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x18a0)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x18a0)
#define image_1_start_task_tx_task_1st_wakeup_request        (0xe50)
#define image_1_tx_task_1st_wakeup_request        (0xe50)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x1448)
#define image_1_budget_allocator_1st_wakeup_request        (0x1448)
#define image_1_start_task_debug_routine        (0x3b0)
#define image_1_debug_routine        (0x3b0)
#define image_1_start_task_pfc_direct_wakeup_request        (0xbb0)
#define image_1_pfc_direct_wakeup_request        (0xbb0)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x1788)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x1788)
#define image_1_start_task_dhd_tx_complete_wakeup_request        (0x550)
#define image_1_dhd_tx_complete_wakeup_request        (0x550)
#define image_1_start_task_dhd_rx_complete_wakeup_request        (0x868)
#define image_1_dhd_rx_complete_wakeup_request        (0x868)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dynamic_code_section        (0x8)
#define image_1_dynamic_code_section_proc0        (0x8)
#define image_1_dynamic_code_section_proc1        (0x78)
#define image_1_dynamic_code_section_proc2        (0xe8)
#define image_1_dynamic_code_section_proc3        (0x158)
#define image_1_dynamic_code_section_proc4        (0x1c8)
#define image_1_dynamic_code_section_proc5        (0x238)
#define image_1_dynamic_code_section_proc6        (0x2a8)
#define image_1_dynamic_code_section_proc7        (0x318)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x1e8c)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x1e8c)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x21b4)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x21b4)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x1dc8)
#define image_1_dhd_send_entry_to_cpu_ring        (0x1dc8)
#define image_1_start_task_iptv_handler        (0x386c)
#define image_1_iptv_handler        (0x386c)
#define image_1_start_task_mcast_flow_lkp_and_fwd        (0x375c)
#define image_1_mcast_flow_lkp_and_fwd        (0x375c)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x1bdc)
#define image_1_memcpy_abs_to_sbpm        (0x1bdc)
#define image_1_start_task_processing_wakeup_request        (0x241c)
#define image_1_processing_wakeup_request        (0x241c)

#else

#define image_1_start_task_initialization_task        (0xe2)
#define image_1_initialization_task        (0xe2)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x628)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x628)
#define image_1_start_task_tx_task_1st_wakeup_request        (0x394)
#define image_1_tx_task_1st_wakeup_request        (0x394)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x512)
#define image_1_budget_allocator_1st_wakeup_request        (0x512)
#define image_1_start_task_debug_routine        (0xec)
#define image_1_debug_routine        (0xec)
#define image_1_start_task_pfc_direct_wakeup_request        (0x2ec)
#define image_1_pfc_direct_wakeup_request        (0x2ec)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x5e2)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x5e2)
#define image_1_start_task_dhd_tx_complete_wakeup_request        (0x154)
#define image_1_dhd_tx_complete_wakeup_request        (0x154)
#define image_1_start_task_dhd_rx_complete_wakeup_request        (0x21a)
#define image_1_dhd_rx_complete_wakeup_request        (0x21a)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dynamic_code_section        (0x2)
#define image_1_dynamic_code_section_proc0        (0x2)
#define image_1_dynamic_code_section_proc1        (0x1e)
#define image_1_dynamic_code_section_proc2        (0x3a)
#define image_1_dynamic_code_section_proc3        (0x56)
#define image_1_dynamic_code_section_proc4        (0x72)
#define image_1_dynamic_code_section_proc5        (0x8e)
#define image_1_dynamic_code_section_proc6        (0xaa)
#define image_1_dynamic_code_section_proc7        (0xc6)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x7a3)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x7a3)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x86d)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x86d)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x772)
#define image_1_dhd_send_entry_to_cpu_ring        (0x772)
#define image_1_start_task_iptv_handler        (0xe1b)
#define image_1_iptv_handler        (0xe1b)
#define image_1_start_task_mcast_flow_lkp_and_fwd        (0xdd7)
#define image_1_mcast_flow_lkp_and_fwd        (0xdd7)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x6f7)
#define image_1_memcpy_abs_to_sbpm        (0x6f7)
#define image_1_start_task_processing_wakeup_request        (0x907)
#define image_1_processing_wakeup_request        (0x907)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_start_task_initialization_task        (0x388)
#define image_2_initialization_task        (0x388)
#define image_2_start_task_cpu_tx_wakeup_request        (0x550)
#define image_2_cpu_tx_wakeup_request        (0x550)
#define image_2_cpu_tx_read_ring_indices        (0x550)
#define image_2_start_task_debug_routine        (0x3b0)
#define image_2_debug_routine        (0x3b0)
#define image_2_start_task_cpu_recycle_wakeup_request        (0xbe0)
#define image_2_cpu_recycle_wakeup_request        (0xbe0)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0xd30)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0xd30)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dynamic_code_section        (0x8)
#define image_2_dynamic_code_section_proc0        (0x8)
#define image_2_dynamic_code_section_proc1        (0x78)
#define image_2_dynamic_code_section_proc2        (0xe8)
#define image_2_dynamic_code_section_proc3        (0x158)
#define image_2_dynamic_code_section_proc4        (0x1c8)
#define image_2_dynamic_code_section_proc5        (0x238)
#define image_2_dynamic_code_section_proc6        (0x2a8)
#define image_2_dynamic_code_section_proc7        (0x318)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x1154)
#define image_2_c_cpu_tx_wakeup_request        (0x1154)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x150c)
#define image_2_cpu_tx_send_pd_to_recycle        (0x150c)
#define image_2_start_task_iptv_handler        (0x29c0)
#define image_2_iptv_handler        (0x29c0)
#define image_2_start_task_mcast_flow_lkp_and_fwd        (0x28b0)
#define image_2_mcast_flow_lkp_and_fwd        (0x28b0)
#define image_2_start_task_memcpy_abs_to_fpm        (0xf88)
#define image_2_memcpy_abs_to_fpm        (0xf88)
#define image_2_start_task_memcpy_abs_to_sbpm        (0xd9c)
#define image_2_memcpy_abs_to_sbpm        (0xd9c)
#define image_2_start_task_processing_wakeup_request        (0x1570)
#define image_2_processing_wakeup_request        (0x1570)

#else

#define image_2_start_task_initialization_task        (0xe2)
#define image_2_initialization_task        (0xe2)
#define image_2_start_task_cpu_tx_wakeup_request        (0x154)
#define image_2_cpu_tx_wakeup_request        (0x154)
#define image_2_cpu_tx_read_ring_indices        (0x154)
#define image_2_start_task_debug_routine        (0xec)
#define image_2_debug_routine        (0xec)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x2f8)
#define image_2_cpu_recycle_wakeup_request        (0x2f8)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x34c)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x34c)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dynamic_code_section        (0x2)
#define image_2_dynamic_code_section_proc0        (0x2)
#define image_2_dynamic_code_section_proc1        (0x1e)
#define image_2_dynamic_code_section_proc2        (0x3a)
#define image_2_dynamic_code_section_proc3        (0x56)
#define image_2_dynamic_code_section_proc4        (0x72)
#define image_2_dynamic_code_section_proc5        (0x8e)
#define image_2_dynamic_code_section_proc6        (0xaa)
#define image_2_dynamic_code_section_proc7        (0xc6)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x455)
#define image_2_c_cpu_tx_wakeup_request        (0x455)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x543)
#define image_2_cpu_tx_send_pd_to_recycle        (0x543)
#define image_2_start_task_iptv_handler        (0xa70)
#define image_2_iptv_handler        (0xa70)
#define image_2_start_task_mcast_flow_lkp_and_fwd        (0xa2c)
#define image_2_mcast_flow_lkp_and_fwd        (0xa2c)
#define image_2_start_task_memcpy_abs_to_fpm        (0x3e2)
#define image_2_memcpy_abs_to_fpm        (0x3e2)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x367)
#define image_2_memcpy_abs_to_sbpm        (0x367)
#define image_2_start_task_processing_wakeup_request        (0x55c)
#define image_2_processing_wakeup_request        (0x55c)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_start_task_initialization_task        (0x388)
#define image_3_initialization_task        (0x388)
#define image_3_start_task_debug_routine        (0x3b0)
#define image_3_debug_routine        (0x3b0)
#define image_3_start_task_cpu_rx_wakeup_request        (0x1260)
#define image_3_cpu_rx_wakeup_request        (0x1260)
#define image_3_start_task_cpu_recycle_wakeup_request        (0x1640)
#define image_3_cpu_recycle_wakeup_request        (0x1640)
#define image_3_start_task_interrupt_coalescing_1st_wakeup_request        (0x1790)
#define image_3_interrupt_coalescing_1st_wakeup_request        (0x1790)
#define image_3_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x1590)
#define image_3_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x1590)
#define image_3_start_task_cpu_rx_copy_wakeup_request        (0x508)
#define image_3_cpu_rx_copy_wakeup_request        (0x508)
#define image_3_start_task_spdsvc_gen_wakeup_request        (0x2710)
#define image_3_spdsvc_gen_wakeup_request        (0x2710)
#define image_3_start_task_common_reprocessing_wakeup_request        (0x2970)
#define image_3_common_reprocessing_wakeup_request        (0x2970)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dynamic_code_section        (0x8)
#define image_3_dynamic_code_section_proc0        (0x8)
#define image_3_dynamic_code_section_proc1        (0x78)
#define image_3_dynamic_code_section_proc2        (0xe8)
#define image_3_dynamic_code_section_proc3        (0x158)
#define image_3_dynamic_code_section_proc4        (0x1c8)
#define image_3_dynamic_code_section_proc5        (0x238)
#define image_3_dynamic_code_section_proc6        (0x2a8)
#define image_3_dynamic_code_section_proc7        (0x318)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x4604)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x4604)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x4290)
#define image_3_c_cpu_rx_wakeup_request        (0x4290)
#define image_3_start_task_iptv_handler        (0x4140)
#define image_3_iptv_handler        (0x4140)
#define image_3_start_task_mcast_flow_lkp_and_fwd        (0x4030)
#define image_3_mcast_flow_lkp_and_fwd        (0x4030)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x2b04)
#define image_3_memcpy_abs_to_sbpm        (0x2b04)
#define image_3_start_task_processing_wakeup_request        (0x2cf0)
#define image_3_processing_wakeup_request        (0x2cf0)

#else

#define image_3_start_task_initialization_task        (0xe2)
#define image_3_initialization_task        (0xe2)
#define image_3_start_task_debug_routine        (0xec)
#define image_3_debug_routine        (0xec)
#define image_3_start_task_cpu_rx_wakeup_request        (0x498)
#define image_3_cpu_rx_wakeup_request        (0x498)
#define image_3_start_task_cpu_recycle_wakeup_request        (0x590)
#define image_3_cpu_recycle_wakeup_request        (0x590)
#define image_3_start_task_interrupt_coalescing_1st_wakeup_request        (0x5e4)
#define image_3_interrupt_coalescing_1st_wakeup_request        (0x5e4)
#define image_3_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x564)
#define image_3_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x564)
#define image_3_start_task_cpu_rx_copy_wakeup_request        (0x142)
#define image_3_cpu_rx_copy_wakeup_request        (0x142)
#define image_3_start_task_spdsvc_gen_wakeup_request        (0x9c4)
#define image_3_spdsvc_gen_wakeup_request        (0x9c4)
#define image_3_start_task_common_reprocessing_wakeup_request        (0xa5c)
#define image_3_common_reprocessing_wakeup_request        (0xa5c)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dynamic_code_section        (0x2)
#define image_3_dynamic_code_section_proc0        (0x2)
#define image_3_dynamic_code_section_proc1        (0x1e)
#define image_3_dynamic_code_section_proc2        (0x3a)
#define image_3_dynamic_code_section_proc3        (0x56)
#define image_3_dynamic_code_section_proc4        (0x72)
#define image_3_dynamic_code_section_proc5        (0x8e)
#define image_3_dynamic_code_section_proc6        (0xaa)
#define image_3_dynamic_code_section_proc7        (0xc6)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x1181)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x1181)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x10a4)
#define image_3_c_cpu_rx_wakeup_request        (0x10a4)
#define image_3_start_task_iptv_handler        (0x1050)
#define image_3_iptv_handler        (0x1050)
#define image_3_start_task_mcast_flow_lkp_and_fwd        (0x100c)
#define image_3_mcast_flow_lkp_and_fwd        (0x100c)
#define image_3_start_task_memcpy_abs_to_sbpm        (0xac1)
#define image_3_memcpy_abs_to_sbpm        (0xac1)
#define image_3_start_task_processing_wakeup_request        (0xb3c)
#define image_3_processing_wakeup_request        (0xb3c)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_start_task_initialization_task        (0x388)
#define image_4_initialization_task        (0x388)
#define image_4_start_task_debug_routine        (0x3b0)
#define image_4_debug_routine        (0x3b0)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0xfb0)
#define image_4_dhd_tx_post_wakeup_request        (0xfb0)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0xf60)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0xf60)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0xde8)
#define image_4_dhd_timer_1st_wakeup_request        (0xde8)
#define image_4_start_task_dhd_mcast_wakeup_request        (0x7f0)
#define image_4_dhd_mcast_wakeup_request        (0x7f0)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dynamic_code_section        (0x8)
#define image_4_dynamic_code_section_proc0        (0x8)
#define image_4_dynamic_code_section_proc1        (0x78)
#define image_4_dynamic_code_section_proc2        (0xe8)
#define image_4_dynamic_code_section_proc3        (0x158)
#define image_4_dynamic_code_section_proc4        (0x1c8)
#define image_4_dynamic_code_section_proc5        (0x238)
#define image_4_dynamic_code_section_proc6        (0x2a8)
#define image_4_dynamic_code_section_proc7        (0x318)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x2144)
#define image_4_c_dhd_timer_wakeup_request        (0x2144)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x229c)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x229c)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x22e4)
#define image_4_c_dhd_tx_post_wakeup_request        (0x22e4)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x2080)
#define image_4_dhd_send_entry_to_cpu_ring        (0x2080)
#define image_4_start_task_dhd_tx_get_bq_index        (0x30b8)
#define image_4_dhd_tx_get_bq_index        (0x30b8)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x2fd4)
#define image_4_dhd_tx_post_drop_packet        (0x2fd4)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x2e14)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x2e14)
#define image_4_start_task_dhd_tx_put_bq_index        (0x312c)
#define image_4_dhd_tx_put_bq_index        (0x312c)
#define image_4_start_task_iptv_handler        (0x45d8)
#define image_4_iptv_handler        (0x45d8)
#define image_4_start_task_mcast_flow_lkp_and_fwd        (0x44c8)
#define image_4_mcast_flow_lkp_and_fwd        (0x44c8)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x1e94)
#define image_4_memcpy_abs_to_sbpm        (0x1e94)
#define image_4_start_task_processing_wakeup_request        (0x3188)
#define image_4_processing_wakeup_request        (0x3188)
#define image_4_start_task_tx_mirror        (0x4728)
#define image_4_tx_mirror        (0x4728)

#else

#define image_4_start_task_initialization_task        (0xe2)
#define image_4_initialization_task        (0xe2)
#define image_4_start_task_debug_routine        (0xec)
#define image_4_debug_routine        (0xec)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0x3ec)
#define image_4_dhd_tx_post_wakeup_request        (0x3ec)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x3d8)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0x3d8)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0x37a)
#define image_4_dhd_timer_1st_wakeup_request        (0x37a)
#define image_4_start_task_dhd_mcast_wakeup_request        (0x1fc)
#define image_4_dhd_mcast_wakeup_request        (0x1fc)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dynamic_code_section        (0x2)
#define image_4_dynamic_code_section_proc0        (0x2)
#define image_4_dynamic_code_section_proc1        (0x1e)
#define image_4_dynamic_code_section_proc2        (0x3a)
#define image_4_dynamic_code_section_proc3        (0x56)
#define image_4_dynamic_code_section_proc4        (0x72)
#define image_4_dynamic_code_section_proc5        (0x8e)
#define image_4_dynamic_code_section_proc6        (0xaa)
#define image_4_dynamic_code_section_proc7        (0xc6)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x851)
#define image_4_c_dhd_timer_wakeup_request        (0x851)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x8a7)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x8a7)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x8b9)
#define image_4_c_dhd_tx_post_wakeup_request        (0x8b9)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x820)
#define image_4_dhd_send_entry_to_cpu_ring        (0x820)
#define image_4_start_task_dhd_tx_get_bq_index        (0xc2e)
#define image_4_dhd_tx_get_bq_index        (0xc2e)
#define image_4_start_task_dhd_tx_post_drop_packet        (0xbf5)
#define image_4_dhd_tx_post_drop_packet        (0xbf5)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0xb85)
#define image_4_dhd_tx_post_flow_ring_get_info        (0xb85)
#define image_4_start_task_dhd_tx_put_bq_index        (0xc4b)
#define image_4_dhd_tx_put_bq_index        (0xc4b)
#define image_4_start_task_iptv_handler        (0x1176)
#define image_4_iptv_handler        (0x1176)
#define image_4_start_task_mcast_flow_lkp_and_fwd        (0x1132)
#define image_4_mcast_flow_lkp_and_fwd        (0x1132)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x7a5)
#define image_4_memcpy_abs_to_sbpm        (0x7a5)
#define image_4_start_task_processing_wakeup_request        (0xc62)
#define image_4_processing_wakeup_request        (0xc62)
#define image_4_start_task_tx_mirror        (0x11ca)
#define image_4_tx_mirror        (0x11ca)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

