/* soapClient.c
   Generated by gSOAP 2.7.11 from LeafNets.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.11 2008-09-23 03:08:37 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__vrfyLogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__vrfyLoginResponse *_param_1)
{	struct ns1__vrfyLogin soap_tmp_ns1__vrfyLogin;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__vrfyLogin(soap, &soap_tmp_ns1__vrfyLogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__vrfyLogin(soap, &soap_tmp_ns1__vrfyLogin, "ns1:vrfyLogin", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__vrfyLogin(soap, &soap_tmp_ns1__vrfyLogin, "ns1:vrfyLogin", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__vrfyLoginResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__vrfyLoginResponse(soap, _param_1, "ns1:vrfyLoginResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, struct ns1__deleteUserResponse *_param_2)
{	struct ns1__deleteUser soap_tmp_ns1__deleteUser;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteUser._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteUser(soap, &soap_tmp_ns1__deleteUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteUser(soap, &soap_tmp_ns1__deleteUser, "ns1:deleteUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteUser(soap, &soap_tmp_ns1__deleteUser, "ns1:deleteUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns1__deleteUserResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__deleteUserResponse(soap, _param_2, "ns1:deleteUserResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__changePassword(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, char *_in1, struct ns1__changePasswordResponse *_param_3)
{	struct ns1__changePassword soap_tmp_ns1__changePassword;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__changePassword._in0 = _in0;
	soap_tmp_ns1__changePassword._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__changePassword(soap, &soap_tmp_ns1__changePassword);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__changePassword(soap, &soap_tmp_ns1__changePassword, "ns1:changePassword", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__changePassword(soap, &soap_tmp_ns1__changePassword, "ns1:changePassword", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_3)
		return soap_closesock(soap);
	soap_default_ns1__changePasswordResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__changePasswordResponse(soap, _param_3, "ns1:changePasswordResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__updateContact(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__Contact *_in0, struct ns1__updateContactResponse *_param_4)
{	struct ns1__updateContact soap_tmp_ns1__updateContact;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__updateContact._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__updateContact(soap, &soap_tmp_ns1__updateContact);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__updateContact(soap, &soap_tmp_ns1__updateContact, "ns1:updateContact", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__updateContact(soap, &soap_tmp_ns1__updateContact, "ns1:updateContact", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_4)
		return soap_closesock(soap);
	soap_default_ns1__updateContactResponse(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__updateContactResponse(soap, _param_4, "ns1:updateContactResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getContact(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, struct ns1__getContactResponse *_param_5)
{	struct ns1__getContact soap_tmp_ns1__getContact;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getContact._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getContact(soap, &soap_tmp_ns1__getContact);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getContact(soap, &soap_tmp_ns1__getContact, "ns1:getContact", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getContact(soap, &soap_tmp_ns1__getContact, "ns1:getContact", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_5)
		return soap_closesock(soap);
	soap_default_ns1__getContactResponse(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getContactResponse(soap, _param_5, "ns1:getContactResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__lookupContacts(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__Contact *_in0, struct ns1__lookupContactsResponse *_param_6)
{	struct ns1__lookupContacts soap_tmp_ns1__lookupContacts;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__lookupContacts._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__lookupContacts(soap, &soap_tmp_ns1__lookupContacts);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__lookupContacts(soap, &soap_tmp_ns1__lookupContacts, "ns1:lookupContacts", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__lookupContacts(soap, &soap_tmp_ns1__lookupContacts, "ns1:lookupContacts", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_6)
		return soap_closesock(soap);
	soap_default_ns1__lookupContactsResponse(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__lookupContactsResponse(soap, _param_6, "ns1:lookupContactsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__addNetwork(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, char *_in1, struct ArrayOf_USCORExsd_USCOREanyType *_in2, struct ns1__addNetworkResponse *_param_7)
{	struct ns1__addNetwork soap_tmp_ns1__addNetwork;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__addNetwork._in0 = _in0;
	soap_tmp_ns1__addNetwork._in1 = _in1;
	soap_tmp_ns1__addNetwork._in2 = _in2;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__addNetwork(soap, &soap_tmp_ns1__addNetwork);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__addNetwork(soap, &soap_tmp_ns1__addNetwork, "ns1:addNetwork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__addNetwork(soap, &soap_tmp_ns1__addNetwork, "ns1:addNetwork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_7)
		return soap_closesock(soap);
	soap_default_ns1__addNetworkResponse(soap, _param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__addNetworkResponse(soap, _param_7, "ns1:addNetworkResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteNetwork(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, struct ns1__deleteNetworkResponse *_param_8)
{	struct ns1__deleteNetwork soap_tmp_ns1__deleteNetwork;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteNetwork._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteNetwork(soap, &soap_tmp_ns1__deleteNetwork);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteNetwork(soap, &soap_tmp_ns1__deleteNetwork, "ns1:deleteNetwork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteNetwork(soap, &soap_tmp_ns1__deleteNetwork, "ns1:deleteNetwork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_8)
		return soap_closesock(soap);
	soap_default_ns1__deleteNetworkResponse(soap, _param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__deleteNetworkResponse(soap, _param_8, "ns1:deleteNetworkResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__inviteNetworkMember(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, char *_in1, struct ns1__inviteNetworkMemberResponse *_param_9)
{	struct ns1__inviteNetworkMember soap_tmp_ns1__inviteNetworkMember;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__inviteNetworkMember._in0 = _in0;
	soap_tmp_ns1__inviteNetworkMember._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__inviteNetworkMember(soap, &soap_tmp_ns1__inviteNetworkMember);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__inviteNetworkMember(soap, &soap_tmp_ns1__inviteNetworkMember, "ns1:inviteNetworkMember", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__inviteNetworkMember(soap, &soap_tmp_ns1__inviteNetworkMember, "ns1:inviteNetworkMember", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_9)
		return soap_closesock(soap);
	soap_default_ns1__inviteNetworkMemberResponse(soap, _param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__inviteNetworkMemberResponse(soap, _param_9, "ns1:inviteNetworkMemberResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__inviteNetworkMemberByEmail(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, char *_in1, struct ns1__inviteNetworkMemberByEmailResponse *_param_10)
{	struct ns1__inviteNetworkMemberByEmail soap_tmp_ns1__inviteNetworkMemberByEmail;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__inviteNetworkMemberByEmail._in0 = _in0;
	soap_tmp_ns1__inviteNetworkMemberByEmail._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__inviteNetworkMemberByEmail(soap, &soap_tmp_ns1__inviteNetworkMemberByEmail);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__inviteNetworkMemberByEmail(soap, &soap_tmp_ns1__inviteNetworkMemberByEmail, "ns1:inviteNetworkMemberByEmail", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__inviteNetworkMemberByEmail(soap, &soap_tmp_ns1__inviteNetworkMemberByEmail, "ns1:inviteNetworkMemberByEmail", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_10)
		return soap_closesock(soap);
	soap_default_ns1__inviteNetworkMemberByEmailResponse(soap, _param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__inviteNetworkMemberByEmailResponse(soap, _param_10, "ns1:inviteNetworkMemberByEmailResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__inviteNetworkMemberByUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, struct ns2__User *_in1, struct ns2__Contact *_in2, struct ns1__inviteNetworkMemberByUserResponse *_param_11)
{	struct ns1__inviteNetworkMemberByUser soap_tmp_ns1__inviteNetworkMemberByUser;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__inviteNetworkMemberByUser._in0 = _in0;
	soap_tmp_ns1__inviteNetworkMemberByUser._in1 = _in1;
	soap_tmp_ns1__inviteNetworkMemberByUser._in2 = _in2;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__inviteNetworkMemberByUser(soap, &soap_tmp_ns1__inviteNetworkMemberByUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__inviteNetworkMemberByUser(soap, &soap_tmp_ns1__inviteNetworkMemberByUser, "ns1:inviteNetworkMemberByUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__inviteNetworkMemberByUser(soap, &soap_tmp_ns1__inviteNetworkMemberByUser, "ns1:inviteNetworkMemberByUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_11)
		return soap_closesock(soap);
	soap_default_ns1__inviteNetworkMemberByUserResponse(soap, _param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__inviteNetworkMemberByUserResponse(soap, _param_11, "ns1:inviteNetworkMemberByUserResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__acceptNetworkInvite(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, char *_in1, struct ns1__acceptNetworkInviteResponse *_param_12)
{	struct ns1__acceptNetworkInvite soap_tmp_ns1__acceptNetworkInvite;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__acceptNetworkInvite._in0 = _in0;
	soap_tmp_ns1__acceptNetworkInvite._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__acceptNetworkInvite(soap, &soap_tmp_ns1__acceptNetworkInvite);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__acceptNetworkInvite(soap, &soap_tmp_ns1__acceptNetworkInvite, "ns1:acceptNetworkInvite", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__acceptNetworkInvite(soap, &soap_tmp_ns1__acceptNetworkInvite, "ns1:acceptNetworkInvite", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_12)
		return soap_closesock(soap);
	soap_default_ns1__acceptNetworkInviteResponse(soap, _param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__acceptNetworkInviteResponse(soap, _param_12, "ns1:acceptNetworkInviteResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__declineNetworkInvite(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, char *_in1, struct ns1__declineNetworkInviteResponse *_param_13)
{	struct ns1__declineNetworkInvite soap_tmp_ns1__declineNetworkInvite;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__declineNetworkInvite._in0 = _in0;
	soap_tmp_ns1__declineNetworkInvite._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__declineNetworkInvite(soap, &soap_tmp_ns1__declineNetworkInvite);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__declineNetworkInvite(soap, &soap_tmp_ns1__declineNetworkInvite, "ns1:declineNetworkInvite", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__declineNetworkInvite(soap, &soap_tmp_ns1__declineNetworkInvite, "ns1:declineNetworkInvite", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_13)
		return soap_closesock(soap);
	soap_default_ns1__declineNetworkInviteResponse(soap, _param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__declineNetworkInviteResponse(soap, _param_13, "ns1:declineNetworkInviteResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteNetworkMember(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, char *_in1, struct ns1__deleteNetworkMemberResponse *_param_14)
{	struct ns1__deleteNetworkMember soap_tmp_ns1__deleteNetworkMember;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteNetworkMember._in0 = _in0;
	soap_tmp_ns1__deleteNetworkMember._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteNetworkMember(soap, &soap_tmp_ns1__deleteNetworkMember);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteNetworkMember(soap, &soap_tmp_ns1__deleteNetworkMember, "ns1:deleteNetworkMember", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteNetworkMember(soap, &soap_tmp_ns1__deleteNetworkMember, "ns1:deleteNetworkMember", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_14)
		return soap_closesock(soap);
	soap_default_ns1__deleteNetworkMemberResponse(soap, _param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__deleteNetworkMemberResponse(soap, _param_14, "ns1:deleteNetworkMemberResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__leaveNetwork(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, char *_in1, struct ns1__leaveNetworkResponse *_param_15)
{	struct ns1__leaveNetwork soap_tmp_ns1__leaveNetwork;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__leaveNetwork._in0 = _in0;
	soap_tmp_ns1__leaveNetwork._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__leaveNetwork(soap, &soap_tmp_ns1__leaveNetwork);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__leaveNetwork(soap, &soap_tmp_ns1__leaveNetwork, "ns1:leaveNetwork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__leaveNetwork(soap, &soap_tmp_ns1__leaveNetwork, "ns1:leaveNetwork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_15)
		return soap_closesock(soap);
	soap_default_ns1__leaveNetworkResponse(soap, _param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__leaveNetworkResponse(soap, _param_15, "ns1:leaveNetworkResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getNetworks(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, struct ns1__getNetworksResponse *_param_16)
{	struct ns1__getNetworks soap_tmp_ns1__getNetworks;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getNetworks._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getNetworks(soap, &soap_tmp_ns1__getNetworks);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getNetworks(soap, &soap_tmp_ns1__getNetworks, "ns1:getNetworks", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getNetworks(soap, &soap_tmp_ns1__getNetworks, "ns1:getNetworks", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_16)
		return soap_closesock(soap);
	soap_default_ns1__getNetworksResponse(soap, _param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getNetworksResponse(soap, _param_16, "ns1:getNetworksResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getNetwork(struct soap *soap, const char *soap_endpoint, const char *soap_action, LONG64 _in0, struct ns1__getNetworkResponse *_param_17)
{	struct ns1__getNetwork soap_tmp_ns1__getNetwork;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getNetwork._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getNetwork(soap, &soap_tmp_ns1__getNetwork);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getNetwork(soap, &soap_tmp_ns1__getNetwork, "ns1:getNetwork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getNetwork(soap, &soap_tmp_ns1__getNetwork, "ns1:getNetwork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_17)
		return soap_closesock(soap);
	soap_default_ns1__getNetworkResponse(soap, _param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getNetworkResponse(soap, _param_17, "ns1:getNetworkResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getNotifications(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, struct ns1__getNotificationsResponse *_param_18)
{	struct ns1__getNotifications soap_tmp_ns1__getNotifications;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getNotifications._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getNotifications(soap, &soap_tmp_ns1__getNotifications);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getNotifications(soap, &soap_tmp_ns1__getNotifications, "ns1:getNotifications", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getNotifications(soap, &soap_tmp_ns1__getNotifications, "ns1:getNotifications", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_18)
		return soap_closesock(soap);
	soap_default_ns1__getNotificationsResponse(soap, _param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getNotificationsResponse(soap, _param_18, "ns1:getNotificationsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getSystemNotifications(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getSystemNotificationsResponse *_param_19)
{	struct ns1__getSystemNotifications soap_tmp_ns1__getSystemNotifications;
	if (!soap_endpoint)
		soap_endpoint = "http://peerserver.leafnetworks.net:8080/axis/services/LeafNetsWebService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getSystemNotifications(soap, &soap_tmp_ns1__getSystemNotifications);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getSystemNotifications(soap, &soap_tmp_ns1__getSystemNotifications, "ns1:getSystemNotifications", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getSystemNotifications(soap, &soap_tmp_ns1__getSystemNotifications, "ns1:getSystemNotifications", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_19)
		return soap_closesock(soap);
	soap_default_ns1__getSystemNotificationsResponse(soap, _param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getSystemNotificationsResponse(soap, _param_19, "ns1:getSystemNotificationsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
