/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifdef DMP_DEVICE2_BASELINE_1

#include "cms.h"
#include "mdm_types.h"
#include "rcl.h"
#include "stl.h"
#include "validstrings.c"
#include "X_BROADCOM_COM_Gpon_1.c"
/* params for Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg. */
/* in profile Unspecified */
MdmParamNode bcmMsgdCfgParamArray[] = {
   { "LoggingLevel",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "Error", /* default val */
     NULL, /* suggested val */
     { LoggingLevelValues, (void *) 0}  /* validator data */
   },
   { "LoggingDestinationMask",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "1", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};


/* child objects of Device.X_BROADCOM_COM_AppCfg. */
/* in profile Unspecified */
MdmObjectNode appCfgChildObjArray[] = { 
   { 3339, /* Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg. */
     0, /* lockZone */
     "BcmMsgdCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg.", /* generic fullpath */
     "Unspecified", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(bcmMsgdCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     bcmMsgdCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
#ifdef DMP_X_BROADCOM_COM_GPON_1
   { 2000, /* Device.X_BROADCOM_COM_AppCfg.OmcidCfg. */
     9, /* lockZone */
     "OmcidCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.OmcidCfg.", /* generic fullpath */
     "X_BROADCOM_COM_Gpon:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(omcidCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     omcidCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
   { 3325, /* Device.X_BROADCOM_COM_AppCfg.GponMdCfg. */
     0, /* lockZone */
     "GponMdCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.GponMdCfg.", /* generic fullpath */
     "X_BROADCOM_COM_Gpon:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(gponMdCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     gponMdCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
   { 3326, /* Device.X_BROADCOM_COM_AppCfg.GponHalThreadCfg. */
     0, /* lockZone */
     "GponHalThreadCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.GponHalThreadCfg.", /* generic fullpath */
     "X_BROADCOM_COM_Gpon:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(gponHalThreadCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     gponHalThreadCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   }
#endif /* DMP_X_BROADCOM_COM_GPON_1 */
};

/* params for Device. */
/* in profile Device2_Baseline:1 */
MdmParamNode dev2DeviceParamArray[] = {
#ifdef DMP_DEVICE2_BASELINE_3
   { "RootDataModelVersion",
     "Device2_Baseline:3", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     0, 0, /* node flags, offset in obj */
     "2.12", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 32}  /* validator data */
   },
#endif
   { "InterfaceStackNumberOfEntries",
     "Device2_Baseline:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_ALWAYS_WRITE_TO_CONFIG_FILE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};


/* child objects of Device. */
/* in profile Device2_Baseline:1 */
MdmObjectNode dev2DeviceChildObjArray[] = { 
   { 3130, /* Device.X_BROADCOM_COM_AppCfg. */
     7, /* lockZone */
     "X_BROADCOM_COM_AppCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.", /* generic fullpath */
     "Unspecified", /* profile name */
     0, OBN_MULTI_COMP_OBJ, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     0, /* num param nodes */
     sizeof(appCfgChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     NULL, /* param nodes array */
     appCfgChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
#ifdef DMP_X_BROADCOM_COM_GPON_1
   { 2100, /* Device.X_BROADCOM_COM_OMCI. */
     9, /* lockZone */
     "X_BROADCOM_COM_OMCI", /* object name */
     "Device.X_BROADCOM_COM_OMCI.", /* generic fullpath */
     "X_BROADCOM_COM_Gpon:1", /* profile name */
     0, OBN_HIDE_OBJECT_FROM_ACS, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     0, /* num param nodes */
     sizeof(bcmOmciChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     NULL, /* param nodes array */
     bcmOmciChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
   { 2200, /* Device.X_BROADCOM_COM_GPON. */
     9, /* lockZone */
     "X_BROADCOM_COM_GPON", /* object name */
     "Device.X_BROADCOM_COM_GPON.", /* generic fullpath */
     "X_BROADCOM_COM_Gpon:1", /* profile name */
     0, OBN_HIDE_OBJECT_FROM_ACS, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     0, /* num param nodes */
     sizeof(bcmGponChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     NULL, /* param nodes array */
     bcmGponChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   }
#endif /* DMP_X_BROADCOM_COM_GPON_1 */
};

MdmObjectNode igdRootObjNode = 
   { 1000, /* Device. */
     0, /* lockZone */
     "Device", /* object name */
     "Device.", /* generic fullpath */
     "Device2_Baseline:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(dev2DeviceParamArray)/sizeof(MdmParamNode), /* num param nodes */
     sizeof(dev2DeviceChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     dev2DeviceParamArray, /* param nodes array */
     dev2DeviceChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   };



#endif
