/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


const char * minimumSingleVsaValues[] = {
"IgnoreThis",
NULL
};

const char * LoggingLevelValues[] = {
"Error",
"Notice",
"Debug",
NULL
};

const char * LoggingDestinationValues[] = {
"Standard Error",
"Syslog",
"Telnet",
NULL
};

const char * PhysicalMediaCage[] = {
"SFP",
"BOB",
NULL
};

const char * PhysicalMediaPonMode[] = {
"GPON",
"XG-PON",
"XGS-PON",
"NG-PON2",
NULL
};

const char * PhysicalMediaConnector[] = {
"LC",
"SC",
"ST",
"FC",
"MT-RJ",
NULL
};

const char * OnuRegistrationState[] = {
"O1",
"O2",
"O3",
"O4",
"O5",
"O6",
"O7",
"O8",
"O9",
NULL
};

const char * TcLayerOperStatusValues[] = {
"Up",
"Down",
"Unknown",
"Dormant",
"NotPresent",
"LowerLayerDown",
"Error",
NULL
};

const char * OmciLayerOperStatusValues[] = {
"Up",
"Down",
NULL
};

const char * CounterDirectionValues[] = {
"upstream",
"downstream",
NULL
};

const char * GemDirectionValues[] = {
"upstream",
"downstream",
"bidirectional",
NULL
};

const char * GemPortTypeValues[] = {
"Unicast",
"Multicast",
"Broadcast",
NULL
};

