/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifdef DMP_DEVICE2_BASELINE_1

#include "cms.h"
#include "mdm_types.h"
#include "rcl.h"
#include "stl.h"
#include "validstrings.c"
#include "X_BROADCOM_COM_DPOE_1.c"
#include "X_BROADCOM_COM_Epon_1.c"
#include "X_BROADCOM_COM_EPON_1.c"
/* params for Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg. */
/* in profile Unspecified */
MdmParamNode bcmMsgdCfgParamArray[] = {
   { "LoggingLevel",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "Error", /* default val */
     NULL, /* suggested val */
     { LoggingLevelValues, (void *) 0}  /* validator data */
   },
   { "LoggingDestinationMask",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "1", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};


/* child objects of Device.X_BROADCOM_COM_AppCfg. */
/* in profile Unspecified */
MdmObjectNode appCfgChildObjArray[] = { 
   { 3339, /* Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg. */
     0, /* lockZone */
     "BcmMsgdCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.BcmMsgdCfg.", /* generic fullpath */
     "Unspecified", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(bcmMsgdCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     bcmMsgdCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
#ifdef DMP_X_BROADCOM_COM_EPON_1
   { 3327, /* Device.X_BROADCOM_COM_AppCfg.EponMdCfg. */
     0, /* lockZone */
     "EponMdCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.EponMdCfg.", /* generic fullpath */
     "X_BROADCOM_COM_EPON:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(eponMdCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     eponMdCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
   { 3328, /* Device.X_BROADCOM_COM_AppCfg.EponHalThreadCfg. */
     0, /* lockZone */
     "EponHalThreadCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.EponHalThreadCfg.", /* generic fullpath */
     "X_BROADCOM_COM_EPON:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(eponHalThreadCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     eponHalThreadCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
#endif /* DMP_X_BROADCOM_COM_EPON_1 */
#ifdef DMP_X_BROADCOM_COM_EPON_1
   { 2500, /* Device.X_BROADCOM_COM_AppCfg.EponappCfg. */
     9, /* lockZone */
     "EponappCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.EponappCfg.", /* generic fullpath */
     "X_BROADCOM_COM_Epon:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(eponappCfgParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     eponappCfgParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   }
#endif /* DMP_X_BROADCOM_COM_EPON_1 */
};

/* params for Device. */
/* in profile Device2_Baseline:1 */
MdmParamNode dev2DeviceParamArray[] = {
#ifdef DMP_DEVICE2_BASELINE_3
   { "RootDataModelVersion",
     "Device2_Baseline:3", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     0, 0, /* node flags, offset in obj */
     "2.12", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 32}  /* validator data */
   },
#endif
   { "InterfaceStackNumberOfEntries",
     "Device2_Baseline:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_ALWAYS_WRITE_TO_CONFIG_FILE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};


/* child objects of Device. */
/* in profile Device2_Baseline:1 */
MdmObjectNode dev2DeviceChildObjArray[] = { 
   { 3130, /* Device.X_BROADCOM_COM_AppCfg. */
     7, /* lockZone */
     "X_BROADCOM_COM_AppCfg", /* object name */
     "Device.X_BROADCOM_COM_AppCfg.", /* generic fullpath */
     "Unspecified", /* profile name */
     0, OBN_MULTI_COMP_OBJ, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     0, /* num param nodes */
     sizeof(appCfgChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     NULL, /* param nodes array */
     appCfgChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
#ifdef DMP_X_BROADCOM_COM_EPON_1
   { 2010, /* Device.X_BROADCOM_COM_EPON. */
     9, /* lockZone */
     "X_BROADCOM_COM_EPON", /* object name */
     "Device.X_BROADCOM_COM_EPON.", /* generic fullpath */
     "X_BROADCOM_COM_EPON:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(eponParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     eponParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
#endif /* DMP_X_BROADCOM_COM_EPON_1 */
#ifdef DMP_X_BROADCOM_COM_DPOE_1
   { 2020, /* Device.X_BROADCOM_COM_DPoE. */
     9, /* lockZone */
     "X_BROADCOM_COM_DPoE", /* object name */
     "Device.X_BROADCOM_COM_DPoE.", /* generic fullpath */
     "X_BROADCOM_COM_DPOE:1", /* profile name */
     0, OBN_HIDE_OBJECT_FROM_ACS, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     0, /* num param nodes */
     sizeof(dPoEChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     NULL, /* param nodes array */
     dPoEChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   }
#endif /* DMP_X_BROADCOM_COM_DPOE_1 */
};

MdmObjectNode igdRootObjNode = 
   { 1000, /* Device. */
     0, /* lockZone */
     "Device", /* object name */
     "Device.", /* generic fullpath */
     "Device2_Baseline:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(dev2DeviceParamArray)/sizeof(MdmParamNode), /* num param nodes */
     sizeof(dev2DeviceChildObjArray)/sizeof(MdmObjectNode), /* num obj nodes */
     dev2DeviceParamArray, /* param nodes array */
     dev2DeviceChildObjArray, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   };



#endif
