/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


const char * minimumSingleVsaValues[] = {
"IgnoreThis",
NULL
};

const char * LoggingLevelValues[] = {
"Error",
"Notice",
"Debug",
NULL
};

const char * LoggingDestinationValues[] = {
"Standard Error",
"Syslog",
"Telnet",
NULL
};

