/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifdef DMP_X_BROADCOM_COM_DPOE_1

/* params for Device.X_BROADCOM_COM_DPoE.DPoE_FirmwareInfo. */
/* in profile X_BROADCOM_COM_DPOE:1 */
MdmParamNode dPoEFirmwareInfoParamArray[] = {
   { "BootVersion",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 64}  /* validator data */
   },
   { "BootCrc32",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 64}  /* validator data */
   },
   { "AppVersion",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 64}  /* validator data */
   },
   { "AppCrc32",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 64}  /* validator data */
   },
};

/* params for Device.X_BROADCOM_COM_DPoE.DPoE_ChipInfo. */
/* in profile X_BROADCOM_COM_DPOE:1 */
MdmParamNode dPoEChipInfoParamArray[] = {
   { "JedecId",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 65535}  /* validator data */
   },
   { "ChipModel",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 4294967295UL}  /* validator data */
   },
   { "ChipVersion",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 4294967295UL}  /* validator data */
   },
};

/* params for Device.X_BROADCOM_COM_DPoE.DPoE_OnuLinkStatistics.{i}. */
/* in profile X_BROADCOM_COM_DPOE:1 */
MdmParamNode dPoEOnuLinkStatisticsParamArray[] = {
   { "link",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     0, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 255}  /* validator data */
   },
   { "RxUnicastFrames",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxUnicastFrames",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrameTooShort",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame64",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame65_127",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame128_255",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame256_511",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame512_1023",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame1024_1518",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "RxFrame1519_Plus",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame64",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame65_127",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame128_255",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame256_511",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame512_1023",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame_1024_1518",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "TxFrame_1519_Plus",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "FramesDropped",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "BytesDropped",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_LONG64,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "OpticalMonVcc",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "OpticalMonTxBiasCurrent",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "OpticalMonTxPower",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "OpticalMonRxPower",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_DENY_ACTIVE_NOTIFICATION, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};


/* child objects of Device.X_BROADCOM_COM_DPoE. */
/* in profile X_BROADCOM_COM_DPOE:1 */
MdmObjectNode dPoEChildObjArray[] = { 
   { 2021, /* Device.X_BROADCOM_COM_DPoE.DPoE_FirmwareInfo. */
     9, /* lockZone */
     "DPoE_FirmwareInfo", /* object name */
     "Device.X_BROADCOM_COM_DPoE.DPoE_FirmwareInfo.", /* generic fullpath */
     "X_BROADCOM_COM_DPOE:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(dPoEFirmwareInfoParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     dPoEFirmwareInfoParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
   { 2022, /* Device.X_BROADCOM_COM_DPoE.DPoE_ChipInfo. */
     9, /* lockZone */
     "DPoE_ChipInfo", /* object name */
     "Device.X_BROADCOM_COM_DPoE.DPoE_ChipInfo.", /* generic fullpath */
     "X_BROADCOM_COM_DPOE:1", /* profile name */
     0, 0, 0,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(dPoEChipInfoParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     dPoEChipInfoParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   },
   { 2023, /* Device.X_BROADCOM_COM_DPoE.DPoE_OnuLinkStatistics.{i}. */
     9, /* lockZone */
     "DPoE_OnuLinkStatistics", /* object name */
     "Device.X_BROADCOM_COM_DPoE.DPoE_OnuLinkStatistics.{i}.", /* generic fullpath */
     "X_BROADCOM_COM_DPOE:1", /* profile name */
     0, OBN_INSTANCE_NODE | OBN_DYNAMIC_INSTANCES | OBN_PRUNE_WRITE_TO_CONFIG_FILE, 1,/* oidInfoIdx, node flags, instance depth */
     NULL,        /* parent objNode ptr */
     {0, DEFAULT_ACCESS_BIT_MASK, 0, DEFAULT_NOTIFICATION_VALUE, 0, 0, 0, 0, DEFAULT_ALTNOTIFICATION_VALUE, 0}, /* nodeattr value of this objNode */
     NULL, /* pointer to instances of nodeattr values for parameter nodes */
     sizeof(dPoEOnuLinkStatisticsParamArray)/sizeof(MdmParamNode), /* num param nodes */
     0, /* num obj nodes */
     dPoEOnuLinkStatisticsParamArray, /* param nodes array */
     NULL, /* child obj array */
     0, /* lastWritePid */
     {0, 0}, /* lastWriteTs */
     NULL  /* obj data */
   }
};



#endif
