/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifdef DMP_X_BROADCOM_COM_EPON_1

/* params for Device.X_BROADCOM_COM_AppCfg.EponappCfg. */
/* in profile X_BROADCOM_COM_Epon:1 */
MdmParamNode eponappCfgParamArray[] = {
   { "LoggingLevel",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "Error", /* default val */
     NULL, /* suggested val */
     { LoggingLevelValues, (void *) 0}  /* validator data */
   },
   { "LoggingDestination",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "Standard Error", /* default val */
     NULL, /* suggested val */
     { LoggingDestinationValues, (void *) 0}  /* validator data */
   },
};



#endif
