/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifdef DMP_X_BROADCOM_COM_EPON_1

/* params for Device.X_BROADCOM_COM_AppCfg.EponMdCfg. */
/* in profile X_BROADCOM_COM_EPON:1 */
MdmParamNode eponMdCfgParamArray[] = {
   { "LoggingLevel",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "Error", /* default val */
     NULL, /* suggested val */
     { LoggingLevelValues, (void *) 0}  /* validator data */
   },
   { "LoggingDestinationMask",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "1", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};

/* params for Device.X_BROADCOM_COM_AppCfg.EponHalThreadCfg. */
/* in profile X_BROADCOM_COM_EPON:1 */
MdmParamNode eponHalThreadCfgParamArray[] = {
   { "LoggingLevel",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "Error", /* default val */
     NULL, /* suggested val */
     { LoggingLevelValues, (void *) 0}  /* validator data */
   },
   { "LoggingDestinationMask",
     "Unspecified", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "1", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
};

/* params for Device.X_BROADCOM_COM_EPON. */
/* in profile X_BROADCOM_COM_EPON:1 */
MdmParamNode eponParamArray[] = {
   { "AuthenticationId",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "AuthenticationPassword",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "OamSelection",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "ImageCrc",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "ImageCrcBeforeCommit",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "Date",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_HEX_BINARY,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 8}  /* validator data */
   },
   { "MaxLinkNum",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "1", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "DpoeFileName",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 128}  /* validator data */
   },
   { "DpoeMfgTime",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_HEX_BINARY,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 26}  /* validator data */
   },
   { "EponSchMode",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "EponIdleTimeOffset",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "ExtendedId",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "EponTxLaserPowerOff",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_BOOLEAN,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "FailSafe",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_BOOLEAN,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "CucCfgCnt",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_UNSIGNED_INTEGER,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     "0", /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 0}  /* validator data */
   },
   { "DpoeCosignerName",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_STRING,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 8}  /* validator data */
   },
   { "DpoeCosignerTime",
     "X_BROADCOM_COM_EPON:1", /* profile name */
     NULL, /* parent ptr */
     MPT_HEX_BINARY,
     PRN_WRITABLE, 0, /* node flags, offset in obj */
     NULL, /* default val */
     NULL, /* suggested val */
     {(void *) 0, (void *) 26}  /* validator data */
   },
};



#endif
