/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard
    
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as published by
    the Free Software Foundation (the "GPL").
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    
    A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
    writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
    
:>
*/



/* This is an automated file. Do not edit its contents. */


#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xc00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xe00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_IMG0_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_IMG0_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IMG0_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1800,
	0xc00,
	0x800,
	0xc00,
	0xe00,
};
/* <<<RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1980,
	0xd80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1a00,
	0x1800,
	0xa00,
	0xe00,
	0x2200,
};
/* <<<RDD_VPORT_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b80,
	0x28c0,
	0xb40,
	0x3c0,
	0xdc0,
};
/* <<<RDD_VPORT_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR */
uint32_t RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bc0,
	0x2980,
	0xb80,
	0xa40,
	0x2340,
};
/* <<<RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_CBS_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_CBS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FW_POLICER_CBS_ADDRESS_ARR */


/* >>>RDD_NATC_COUNTERS_GENERIC_CONTEXT_ADDRESS_ARR */
uint32_t RDD_NATC_COUNTERS_GENERIC_CONTEXT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d40,
	0x2a80,
	0x2080,
	0x2780,
	0x2380,
};
/* <<<RDD_NATC_COUNTERS_GENERIC_CONTEXT_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1f00,
	0x2800,
	0xf00,
	0x2200,
	0x2700,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_MUTEX_TABLE_ADDRESS_ARR */
uint32_t RDD_MUTEX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1fb4,
	0x28b4,
	0xfb4,
	0x22b4,
	0x27b4,
};
/* <<<RDD_MUTEX_TABLE_ADDRESS_ARR */


/* >>>RDD_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1fb8,
	0x28b8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1fc0,
	0x2d00,
	0xbc0,
	0x26c0,
	0x2cc0,
};
/* <<<RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_TM_1_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_TM_1_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1fe8,
	0x2d28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_1_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1ff0,
	0x2c70,
	0x22b0,
	0x29b0,
	0x2bf0,
};
/* <<<RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_BUDGET_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_BUDGET_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FW_POLICER_BUDGET_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_BUDGET_REMAINDER_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_BUDGET_REMAINDER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x28a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FW_POLICER_BUDGET_REMAINDER_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x28f0,
	0x2cb0,
	0x22f0,
	0x29f0,
	0x2cf0,
};
/* <<<RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2900,
	0x2900,
	0x2000,
	0x2600,
	0x2c00,
};
/* <<<RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2980,
	0x2b60,
	0x2180,
	0x2860,
	0x2a40,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a00,
	0x2a00,
	0x2100,
	0x2700,
	0x2d00,
};
/* <<<RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a7c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a80,
	0x2d40,
	0xfc0,
	0x2940,
	0x2e80,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2aa4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2aa8,
	0x2d68,
	0xbe8,
	0x22b8,
	0x21c8,
};
/* <<<RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ab0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_CFG_FW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2abc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */


/* >>>RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ac0,
	0x2d80,
	0x2280,
	0x29c0,
	0x2ec0,
};
/* <<<RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae2,
	0x2da2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */


/* >>>RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae8,
	0x2da8,
	0xfb8,
	0x2398,
	0x27b8,
};
/* <<<RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_VECTOR_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2af0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FW_POLICER_VECTOR_ADDRESS_ARR */


/* >>>RDD_SPDTEST_GEN_PARAM_ADDRESS_ARR */
uint32_t RDD_SPDTEST_GEN_PARAM_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2afc,
	0x2d7c,
	0xfe4,
	0x277c,
	0x2bec,
};
/* <<<RDD_SPDTEST_GEN_PARAM_ADDRESS_ARR */


/* >>>RDD_NATC_TBL_CFG_ADDRESS_ARR */
uint32_t RDD_NATC_TBL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b00,
	0x2b00,
	0x2200,
	0x2800,
	0x2e00,
};
/* <<<RDD_NATC_TBL_CFG_ADDRESS_ARR */


/* >>>RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b60,
	0xf60,
	0x2260,
	0xa20,
	0xfe0,
};
/* <<<RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ba2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_TIMER_COMMON_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_TIMER_COMMON_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ba4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TIMER_COMMON_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ba6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ba8,
	0x2de8,
	0xfe8,
	0x25f8,
	0x2ce8,
};
/* <<<RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bb0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bbc,
	0x2dbc,
	0x217c,
	0x2aa4,
	0x2d7c,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bc0,
	0x2e00,
	0x22c0,
	0x2a40,
	0x2f80,
};
/* <<<RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_FORCE_DSCP_ADDRESS_ARR */
uint32_t RDD_FORCE_DSCP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be2,
	0x2de3,
	0x22a2,
	0x2a2d,
	0x2dbe,
};
/* <<<RDD_FORCE_DSCP_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be3,
	0x2de4,
	0x22a3,
	0x2a2e,
	0x2dbf,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be5,
	0x2e26,
	0x22a6,
	0x2a2f,
	0x2dfe,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be6,
	0x2e22,
	0x22a4,
	0x2af4,
	0x2dfc,
};
/* <<<RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_NULL_BUFFER_ADDRESS_ARR */
uint32_t RDD_NULL_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be8,
	0x2e28,
	0x22a8,
	0x26e8,
	0x2de8,
};
/* <<<RDD_NULL_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bf0,
	0x2db0,
	0x23e0,
	0x2c70,
	0x2db0,
};
/* <<<RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */


/* >>>RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */
uint32_t RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bfc,
	0x2e27,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bfd,
	0x2e3c,
	0x22a7,
	0x2af6,
	0x2dff,
};
/* <<<RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bfe,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_MULTI_FLOW_FLAG_TABLE_ADDRESS_ARR */
uint32_t RDD_MULTI_FLOW_FLAG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bff,
	0x2e9d,
	0x22e3,
	0x2b34,
	0x2ea4,
};
/* <<<RDD_MULTI_FLOW_FLAG_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c20,
	0xfe0,
	0x2300,
	0x23a0,
	0x21e0,
};
/* <<<RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c40,
	0x2e40,
	INVALID_TABLE_ADDRESS,
	0x2ac0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */
uint32_t RDD_CPU_REDIRECT_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c74,
	0x2e9e,
	0x22e4,
	0x2b36,
	0x2ea5,
};
/* <<<RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c75,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DEBUG_PRINT_CORE_LOCK_ADDRESS_ARR */
uint32_t RDD_DEBUG_PRINT_CORE_LOCK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c76,
	0x2e9f,
	0x22e5,
	0x2c6c,
	0x2ea6,
};
/* <<<RDD_DEBUG_PRINT_CORE_LOCK_ADDRESS_ARR */


/* >>>RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c77,
	0x2eb4,
	0x22e6,
	0x2c6d,
	0x2ea7,
};
/* <<<RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_TIMER_COMMON_CTR_REP_ADDRESS_ARR */
uint32_t RDD_TIMER_COMMON_CTR_REP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c78,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TIMER_COMMON_CTR_REP_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ca0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cb4,
	0x2eb5,
	0x22e7,
	0x2c6e,
	0x2ebc,
};
/* <<<RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cb5,
	0x2eb6,
	0x237c,
	0x2c6f,
	0x2ebd,
};
/* <<<RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */


/* >>>RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cb8,
	0x2ef8,
	0x2448,
	0x2a28,
	0x3030,
};
/* <<<RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DEBUG_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_DEBUG_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ce0,
	0x2e60,
	0x2320,
	0x2c98,
	0x2b90,
};
/* <<<RDD_DEBUG_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_SPDSVC_BBH_TX_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_BBH_TX_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d10,
	0x2f50,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_BBH_TX_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_BUDGET_REMAINDER_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_BUDGET_REMAINDER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d38,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EMAC_FLOW_CTRL_BUDGET_REMAINDER_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d50,
	0x2f80,
	0x23f0,
	0x2cd0,
	0x2f60,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d60,
	0x2f20,
	0x23a0,
	0x2b60,
	0x2e60,
};
/* <<<RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_BITS_CALC_MASKS_TABLE_ADDRESS_ARR */
uint32_t RDD_BITS_CALC_MASKS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d80,
	0x2f00,
	0x23c0,
	0x2d40,
	0x30c0,
};
/* <<<RDD_BITS_CALC_MASKS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d90,
	0x2f90,
	0x2430,
	0x2d50,
	0x2f70,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2da0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DEBUG_PRINT_TABLE_ADDRESS_ARR */
uint32_t RDD_DEBUG_PRINT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2db0,
	0x2fa0,
	0x2460,
	0x2da0,
	0x2ff0,
};
/* <<<RDD_DEBUG_PRINT_TABLE_ADDRESS_ARR */


/* >>>RDD_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2dc0,
	0x2fc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2dc8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */
uint32_t RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2dd0,
	0x2fb0,
	0x2478,
	0x2af8,
	0x3038,
};
/* <<<RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */


/* >>>RDD_IPTV_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2dd8,
	0x2fb8,
	0x2488,
	0x2b38,
	0x3068,
};
/* <<<RDD_IPTV_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_MULTICAST_KEY_MASK_ADDRESS_ARR */
uint32_t RDD_MULTICAST_KEY_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2de0,
	0x2fe0,
	0x2480,
	0x2dc0,
	0x3060,
};
/* <<<RDD_MULTICAST_KEY_MASK_ADDRESS_ARR */


/* >>>RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */
uint32_t RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2de8,
	0x2fc8,
	0x2490,
	0x2cc8,
	0x3070,
};
/* <<<RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_CFG_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2df0,
	0x2fd0,
	0x2498,
	0x2d28,
	0x3078,
};
/* <<<RDD_NAT_CACHE_CFG_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2df8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_TM_BBH_TX_ABS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_TM_BBH_TX_ABS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e00,
	0x3040,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_BBH_TX_ABS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e08,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e10,
	0x2fe8,
	0x24b8,
	0x2db8,
	0x30a0,
};
/* <<<RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */


/* >>>RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e18,
	0x2ff0,
	0x24c0,
	0x2dc8,
	0x30a8,
};
/* <<<RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e20,
	0x2ff8,
	0x24c8,
	0x2dd0,
	0x30b0,
};
/* <<<RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */


/* >>>RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_TOS_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e28,
	0x3020,
	0x24d0,
	0x2dd8,
	0x30b8,
};
/* <<<RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */


/* >>>RDD_TM_1_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_TM_1_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e40,
	0x3080,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_1_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_TM_1_BBH_TX_ABS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_TM_1_BBH_TX_ABS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e80,
	0x30c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_1_BBH_TX_ABS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR */
uint32_t RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3d00,
	0x3d00,
	0x3d00,
	0x3d00,
	0x3d00,
};
/* <<<RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xa00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xe00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xf50,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0xf80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_IMG1_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_IMG1_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IMG1_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1940,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1980,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_PFC_TX_STATUS_TABLE_ADDRESS_ARR */
uint32_t RDD_PFC_TX_STATUS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x19e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PFC_TX_STATUS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_TASK_0_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_TASK_0_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_TASK_0_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_TASK_1_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_TASK_1_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_TASK_1_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_TASK_2_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_TASK_2_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_TASK_2_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_TASK_0_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_TASK_0_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_TASK_0_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_TASK_1_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_TASK_1_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_TASK_1_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_TASK_2_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_TASK_2_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1f00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_TASK_2_STACK_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_PFC_FRAME_ADDRESS_ARR */
uint32_t RDD_PFC_FRAME_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x29c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PFC_FRAME_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2a7c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */


/* >>>RDD_PFC_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_PFC_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2be0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PFC_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d80,
};
/* <<<RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_HW_CFG_ADDRESS_ARR */
uint32_t RDD_DHD_HW_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2c30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x21d0,
};
/* <<<RDD_DHD_HW_CFG_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2c40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2c80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2cc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2cf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2d30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2d3c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2d64,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */


/* >>>RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2d70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2da4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_PFC_PENDING_QUEUE_MAP_ADDRESS_ARR */
uint32_t RDD_PFC_PENDING_QUEUE_MAP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2da6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PFC_PENDING_QUEUE_MAP_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2de2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */


/* >>>RDD_PFC_TX_ENABLE_ADDRESS_ARR */
uint32_t RDD_PFC_TX_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2de5,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PFC_TX_ENABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2de6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2df0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2dfc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2dfe,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e24,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_US_TM_ETH_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_US_TM_ETH_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e3d,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_ETH_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_ETH_1_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_US_TM_ETH_1_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e3e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_ETH_1_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e3f,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e9c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ea0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2eb8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ee8,
};
/* <<<RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ec0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_MIRRORING_SCRATCH_ADDRESS_ARR */
uint32_t RDD_MIRRORING_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ed8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ea8,
};
/* <<<RDD_MIRRORING_SCRATCH_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_INT_ID_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_INT_ID_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2df0,
};
/* <<<RDD_DHD_CPU_INT_ID_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_WLAN_GEN_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_WLAN_GEN_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_WLAN_GEN_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2fd8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_TX_DBG_CNTRS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_DBG_CNTRS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x980,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_DBG_CNTRS_TABLE_ADDRESS_ARR */


/* >>>RDD_BUFFER_ALLOC_REPLY_ADDRESS_ARR */
uint32_t RDD_BUFFER_ALLOC_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUFFER_ALLOC_REPLY_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xc00,
	0x2000,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_QM_QUEUE_TO_TX_FLOW_TABLE_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_QM_QUEUE_TO_TX_FLOW_TABLE_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xd00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_QM_QUEUE_TO_TX_FLOW_TABLE_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_TASK_STACK_ADDRESS_ARR */
uint32_t RDD_CPU_TX_TASK_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_TASK_STACK_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xff0,
	0x2490,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_IMG2_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_IMG2_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IMG2_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22e2,
	0x2af7,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22e8,
	0x2968,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2350,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2370,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_RING_CPU_TX_DESCRIPTOR_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_RING_CPU_TX_DESCRIPTOR_DATA_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RING_CPU_TX_DESCRIPTOR_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23d0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SYNC_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SYNC_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_SYNC_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2410,
	0x2ce0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2420,
	0x2cf0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2440,
	0x29e8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2450,
	0x2d60,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2458,
	0x2a68,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RING_INDICES_VALUES_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RING_INDICES_VALUES_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2470,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_RING_INDICES_VALUES_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x24a0,
	0x2d88,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x24a8,
	0x2d98,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_NEXT_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_NEXT_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x24b0,
	0x2db0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_NEXT_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_STREAM_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_STREAM_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_STREAM_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_PKTGEN_TX_STREAM_TABLE_ADDRESS_ARR */
uint32_t RDD_PKTGEN_TX_STREAM_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x800,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_TX_STREAM_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_CACHE_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_CACHE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_CACHE_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_TASK_STACK_ADDRESS_ARR */
uint32_t RDD_CPU_RX_TASK_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_TASK_STACK_ADDRESS_ARR */


/* >>>RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xd80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf40,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_IMG3_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_IMG3_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IMG3_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_TASK_STACK_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_TASK_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2100,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_TASK_STACK_ADDRESS_ARR */


/* >>>RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */
uint32_t RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2300,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x24a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x24c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_NO_SBPM_HDRS_CNTR_ADDRESS_ARR */
uint32_t RDD_PKTGEN_NO_SBPM_HDRS_CNTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x24fc,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_NO_SBPM_HDRS_CNTR_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2500,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2580,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_COMMON_REPROCESSING_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_COMMON_REPROCESSING_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2680,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMMON_REPROCESSING_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_INT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_INT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x26f0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_INT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x28e0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SBPM_HDR_BNS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SBPM_HDR_BNS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2900,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SBPM_HDR_BNS_ADDRESS_ARR */


/* >>>RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR */
uint32_t RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2938,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2964,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2970,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_UDPSPDTEST_STREAM_RX_STAT_TABLE_ADDRESS_ARR */
uint32_t RDD_UDPSPDTEST_STREAM_RX_STAT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2980,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UDPSPDTEST_STREAM_RX_STAT_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_CURR_SBPM_HDR_PTR_ADDRESS_ARR */
uint32_t RDD_PKTGEN_CURR_SBPM_HDR_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29e2,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_CURR_SBPM_HDR_PTR_ADDRESS_ARR */


/* >>>RDD_PKTGEN_NUM_OF_AVAIL_SBPM_HDRS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_NUM_OF_AVAIL_SBPM_HDRS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29e4,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_NUM_OF_AVAIL_SBPM_HDRS_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SBPM_END_PTR_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SBPM_END_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29e6,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SBPM_END_PTR_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a30,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_BAD_GET_NEXT_ADDRESS_ARR */
uint32_t RDD_PKTGEN_BAD_GET_NEXT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a3c,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_BAD_GET_NEXT_ADDRESS_ARR */


/* >>>RDD_SPDSVC_TCPSPDTEST_COMMON_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_TCPSPDTEST_COMMON_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a62,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_TCPSPDTEST_COMMON_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_MAX_UT_PKTS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_MAX_UT_PKTS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a64,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_MAX_UT_PKTS_ADDRESS_ARR */


/* >>>RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a70,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_UT_TRIGGER_ADDRESS_ARR */
uint32_t RDD_PKTGEN_UT_TRIGGER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a7c,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_UT_TRIGGER_ADDRESS_ARR */


/* >>>RDD_UDPSPDTEST_STREAM_TX_STAT_TABLE_ADDRESS_ARR */
uint32_t RDD_UDPSPDTEST_STREAM_TX_STAT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UDPSPDTEST_STREAM_TX_STAT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2aa8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_COMMON_REPROCESSING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_COMMON_REPROCESSING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ab0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMMON_REPROCESSING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2abc,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2abe,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */


/* >>>RDD_PKTGEN_FPM_UG_MGMT_ADDRESS_ARR */
uint32_t RDD_PKTGEN_FPM_UG_MGMT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ae0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_FPM_UG_MGMT_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_ENGINE_GLOBAL_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_ENGINE_GLOBAL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b20,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_ENGINE_GLOBAL_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_CACHE_OFFSET_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_CACHE_OFFSET_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b35,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_CACHE_OFFSET_ADDRESS_ARR */


/* >>>RDD_CSO_DISABLE_ADDRESS_ARR */
uint32_t RDD_CSO_DISABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b37,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CSO_DISABLE_ADDRESS_ARR */


/* >>>RDD_COMMON_REPROCESSING_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_COMMON_REPROCESSING_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b40,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMMON_REPROCESSING_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ba0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2be0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c20,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_BCM_SPDSVC_STREAM_RX_TS_TABLE_ADDRESS_ARR */
uint32_t RDD_BCM_SPDSVC_STREAM_RX_TS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c60,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BCM_SPDSVC_STREAM_RX_TS_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SESSION_DATA_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SESSION_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SESSION_DATA_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d30,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d68,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SBPM_EXTS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SBPM_EXTS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d78,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SBPM_EXTS_ADDRESS_ARR */


/* >>>RDD_PKTGEN_BBMSG_REPLY_SCRATCH_ADDRESS_ARR */
uint32_t RDD_PKTGEN_BBMSG_REPLY_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d90,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_BBMSG_REPLY_SCRATCH_ADDRESS_ARR */


/* >>>RDD_PKTGEN_TX_STREAM_SCRATCH_TABLE_ADDRESS_ARR */
uint32_t RDD_PKTGEN_TX_STREAM_SCRATCH_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_TX_STREAM_SCRATCH_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TIMER_TASK_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TIMER_TASK_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x300,
};
/* <<<RDD_DHD_TIMER_TASK_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_AUX_INFO_CACHE_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_AUX_INFO_CACHE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
};
/* <<<RDD_DHD_AUX_INFO_CACHE_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_TASK_0_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_TASK_0_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x700,
};
/* <<<RDD_DHD_TX_POST_TASK_0_STACK_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x800,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa00,
};
/* <<<RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xc00,
};
/* <<<RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xdb0,
};
/* <<<RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf80,
};
/* <<<RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */


/* >>>RDD_IMG4_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_IMG4_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
};
/* <<<RDD_IMG4_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2000,
};
/* <<<RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_L2_HEADER_ADDRESS_ARR */
uint32_t RDD_DHD_L2_HEADER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2180,
};
/* <<<RDD_DHD_L2_HEADER_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_TASK_1_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_TASK_1_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
};
/* <<<RDD_DHD_TX_POST_TASK_1_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_TASK_2_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_TASK_2_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2500,
};
/* <<<RDD_DHD_TX_POST_TASK_2_STACK_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_UPDATE_FIFO_TASK_STACK_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_UPDATE_FIFO_TASK_STACK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2600,
};
/* <<<RDD_DHD_TX_POST_UPDATE_FIFO_TASK_STACK_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27c0,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2800,
};
/* <<<RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x28c0,
};
/* <<<RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ac0,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b00,
};
/* <<<RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
};
/* <<<RDD_DHD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c80,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_WLAN_TXPOST_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_WLAN_TXPOST_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2dbc,
};
/* <<<RDD_SPDSVC_WLAN_TXPOST_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2dc0,
};
/* <<<RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2eb0,
};
/* <<<RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ef0,
};
/* <<<RDD_DHD_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f00,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fa8,
};
/* <<<RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
};
/* <<<RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3020,
};
/* <<<RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3028,
};
/* <<<RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3040,
};
/* <<<RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3080,
};
/* <<<RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */

