/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_start_task_initialization_task        (0x388)
#define image_0_initialization_task        (0x388)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0x3130)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0x3130)
#define image_0_start_task_processing_wakeup_request        (0x4c0)
#define image_0_processing_wakeup_request        (0x4c0)
#define image_0_start_task_tx_task_1st_wakeup_request        (0x35b8)
#define image_0_tx_task_1st_wakeup_request        (0x35b8)
#define image_0_start_task_timer_common_task_wakeup_request        (0x3e10)
#define image_0_timer_common_task_wakeup_request        (0x3e10)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x3998)
#define image_0_budget_allocator_1st_wakeup_request        (0x3998)
#define image_0_start_task_debug_routine        (0x3f4)
#define image_0_debug_routine        (0x3f4)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x3f70)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0x3f70)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x41b8)
#define image_0_service_queues_tx_task_wakeup_request        (0x41b8)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x4380)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x4380)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dynamic_code_section        (0x8)
#define image_0_dynamic_code_section_proc0        (0x8)
#define image_0_dynamic_code_section_proc1        (0x78)
#define image_0_dynamic_code_section_proc2        (0xe8)
#define image_0_dynamic_code_section_proc3        (0x158)
#define image_0_dynamic_code_section_proc4        (0x1c8)
#define image_0_dynamic_code_section_proc5        (0x238)
#define image_0_dynamic_code_section_proc6        (0x2a8)
#define image_0_dynamic_code_section_proc7        (0x318)
#define image_0_processing_check_wlan_llcsnap        (0xd98)
#define image_0_processing_write_header_done        (0xd98)
#define image_0_processing_done        (0xdf4)
#define image_0_action_gpe        (0x2228)
#define image_0_action_exception        (0x2230)
#define image_0_gpe_sop_push_replace_ddr_sram_32        (0x2268)
#define image_0_gpe_sop_push_replace_sram_32_64        (0x22b0)
#define image_0_gpe_sop_push_replace_sram_64        (0x22c8)
#define image_0_gpe_sop_push_replace_sram_64_32        (0x22e0)
#define image_0_gpe_sop_pull_replace_ddr_sram_32        (0x22f8)
#define image_0_gpe_sop_pull_replace_sram_32_64        (0x2340)
#define image_0_gpe_sop_pull_replace_sram_64        (0x2388)
#define image_0_gpe_sop_pull_replace_sram_64_32        (0x23c8)
#define image_0_gpe_replace_pointer_32_sram        (0x2410)
#define image_0_gpe_replace_pointer_64_sram        (0x2438)
#define image_0_gpe_replace_16        (0x2460)
#define image_0_gpe_replace_32        (0x2498)
#define image_0_gpe_replace_bits_16        (0x24c0)
#define image_0_gpe_copy_add_16_cl        (0x24f0)
#define image_0_gpe_copy_add_16_sram        (0x2500)
#define image_0_gpe_copy_bits_16_cl        (0x2548)
#define image_0_gpe_copy_bits_16_sram        (0x2558)
#define image_0_gpe_insert_16        (0x25a0)
#define image_0_gpe_delete_16        (0x2608)
#define image_0_gpe_decrement_8        (0x2648)
#define image_0_gpe_apply_icsum_16        (0x2668)
#define image_0_gpe_apply_icsum_nz_16        (0x2688)
#define image_0_gpe_compute_csum_16_cl        (0x26b8)
#define image_0_gpe_compute_csum_16_sram        (0x26c8)
#define image_0_gpe_buffer_copy_16_sram        (0x2708)
#define image_0_gpe_buffer_copy_16_ddr        (0x2738)
#define image_0_gpe_replace_add_packet_length_cl        (0x2760)
#define image_0_tcam_cmd_ic_submit        (0x27a4)

#else

#define image_0_start_task_initialization_task        (0xe2)
#define image_0_initialization_task        (0xe2)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request        (0xc4c)
#define image_0_update_fifo_us_read_1st_wakeup_request        (0xc4c)
#define image_0_start_task_processing_wakeup_request        (0x130)
#define image_0_processing_wakeup_request        (0x130)
#define image_0_start_task_tx_task_1st_wakeup_request        (0xd6e)
#define image_0_tx_task_1st_wakeup_request        (0xd6e)
#define image_0_start_task_timer_common_task_wakeup_request        (0xf84)
#define image_0_timer_common_task_wakeup_request        (0xf84)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0xe66)
#define image_0_budget_allocator_1st_wakeup_request        (0xe66)
#define image_0_start_task_debug_routine        (0xfd)
#define image_0_debug_routine        (0xfd)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0xfdc)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request        (0xfdc)
#define image_0_start_task_service_queues_tx_task_wakeup_request        (0x106e)
#define image_0_service_queues_tx_task_wakeup_request        (0x106e)
#define image_0_start_task_budget_allocator_sq_1st_wakeup_request        (0x10e0)
#define image_0_budget_allocator_sq_1st_wakeup_request        (0x10e0)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dynamic_code_section        (0x2)
#define image_0_dynamic_code_section_proc0        (0x2)
#define image_0_dynamic_code_section_proc1        (0x1e)
#define image_0_dynamic_code_section_proc2        (0x3a)
#define image_0_dynamic_code_section_proc3        (0x56)
#define image_0_dynamic_code_section_proc4        (0x72)
#define image_0_dynamic_code_section_proc5        (0x8e)
#define image_0_dynamic_code_section_proc6        (0xaa)
#define image_0_dynamic_code_section_proc7        (0xc6)
#define image_0_processing_check_wlan_llcsnap        (0x366)
#define image_0_processing_write_header_done        (0x366)
#define image_0_processing_done        (0x37d)
#define image_0_action_gpe        (0x88a)
#define image_0_action_exception        (0x88c)
#define image_0_gpe_sop_push_replace_ddr_sram_32        (0x89a)
#define image_0_gpe_sop_push_replace_sram_32_64        (0x8ac)
#define image_0_gpe_sop_push_replace_sram_64        (0x8b2)
#define image_0_gpe_sop_push_replace_sram_64_32        (0x8b8)
#define image_0_gpe_sop_pull_replace_ddr_sram_32        (0x8be)
#define image_0_gpe_sop_pull_replace_sram_32_64        (0x8d0)
#define image_0_gpe_sop_pull_replace_sram_64        (0x8e2)
#define image_0_gpe_sop_pull_replace_sram_64_32        (0x8f2)
#define image_0_gpe_replace_pointer_32_sram        (0x904)
#define image_0_gpe_replace_pointer_64_sram        (0x90e)
#define image_0_gpe_replace_16        (0x918)
#define image_0_gpe_replace_32        (0x926)
#define image_0_gpe_replace_bits_16        (0x930)
#define image_0_gpe_copy_add_16_cl        (0x93c)
#define image_0_gpe_copy_add_16_sram        (0x940)
#define image_0_gpe_copy_bits_16_cl        (0x952)
#define image_0_gpe_copy_bits_16_sram        (0x956)
#define image_0_gpe_insert_16        (0x968)
#define image_0_gpe_delete_16        (0x982)
#define image_0_gpe_decrement_8        (0x992)
#define image_0_gpe_apply_icsum_16        (0x99a)
#define image_0_gpe_apply_icsum_nz_16        (0x9a2)
#define image_0_gpe_compute_csum_16_cl        (0x9ae)
#define image_0_gpe_compute_csum_16_sram        (0x9b2)
#define image_0_gpe_buffer_copy_16_sram        (0x9c2)
#define image_0_gpe_buffer_copy_16_ddr        (0x9ce)
#define image_0_gpe_replace_add_packet_length_cl        (0x9d8)
#define image_0_tcam_cmd_ic_submit        (0x9e9)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_start_task_initialization_task        (0x388)
#define image_1_initialization_task        (0x388)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x4480)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x4480)
#define image_1_start_task_processing_wakeup_request        (0x4c0)
#define image_1_processing_wakeup_request        (0x4c0)
#define image_1_start_task_tx_task_1st_wakeup_request        (0x3a30)
#define image_1_tx_task_1st_wakeup_request        (0x3a30)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x4028)
#define image_1_budget_allocator_1st_wakeup_request        (0x4028)
#define image_1_start_task_debug_routine        (0x3b0)
#define image_1_debug_routine        (0x3b0)
#define image_1_start_task_pfc_direct_wakeup_request        (0x3790)
#define image_1_pfc_direct_wakeup_request        (0x3790)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x4368)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x4368)
#define image_1_start_task_dhd_tx_complete_wakeup_request        (0x3138)
#define image_1_dhd_tx_complete_wakeup_request        (0x3138)
#define image_1_start_task_dhd_rx_complete_wakeup_request        (0x3450)
#define image_1_dhd_rx_complete_wakeup_request        (0x3450)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dynamic_code_section        (0x8)
#define image_1_dynamic_code_section_proc0        (0x8)
#define image_1_dynamic_code_section_proc1        (0x78)
#define image_1_dynamic_code_section_proc2        (0xe8)
#define image_1_dynamic_code_section_proc3        (0x158)
#define image_1_dynamic_code_section_proc4        (0x1c8)
#define image_1_dynamic_code_section_proc5        (0x238)
#define image_1_dynamic_code_section_proc6        (0x2a8)
#define image_1_dynamic_code_section_proc7        (0x318)
#define image_1_processing_check_wlan_llcsnap        (0xd98)
#define image_1_processing_write_header_done        (0xd98)
#define image_1_processing_done        (0xdf4)
#define image_1_action_gpe        (0x2230)
#define image_1_action_exception        (0x2238)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x2270)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x22b8)
#define image_1_gpe_sop_push_replace_sram_64        (0x22d0)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x22e8)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x2300)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x2348)
#define image_1_gpe_sop_pull_replace_sram_64        (0x2390)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x23d0)
#define image_1_gpe_replace_pointer_32_sram        (0x2418)
#define image_1_gpe_replace_pointer_64_sram        (0x2440)
#define image_1_gpe_replace_16        (0x2468)
#define image_1_gpe_replace_32        (0x24a0)
#define image_1_gpe_replace_bits_16        (0x24c8)
#define image_1_gpe_copy_add_16_cl        (0x24f8)
#define image_1_gpe_copy_add_16_sram        (0x2508)
#define image_1_gpe_copy_bits_16_cl        (0x2550)
#define image_1_gpe_copy_bits_16_sram        (0x2560)
#define image_1_gpe_insert_16        (0x25a8)
#define image_1_gpe_delete_16        (0x2610)
#define image_1_gpe_decrement_8        (0x2650)
#define image_1_gpe_apply_icsum_16        (0x2670)
#define image_1_gpe_apply_icsum_nz_16        (0x2690)
#define image_1_gpe_compute_csum_16_cl        (0x26c0)
#define image_1_gpe_compute_csum_16_sram        (0x26d0)
#define image_1_gpe_buffer_copy_16_sram        (0x2710)
#define image_1_gpe_buffer_copy_16_ddr        (0x2740)
#define image_1_gpe_replace_add_packet_length_cl        (0x2768)
#define image_1_tcam_cmd_ic_submit        (0x27ac)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x479c)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x479c)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x4abc)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x4abc)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x46d8)
#define image_1_dhd_send_entry_to_cpu_ring        (0x46d8)

#else

#define image_1_start_task_initialization_task        (0xe2)
#define image_1_initialization_task        (0xe2)
#define image_1_start_task_update_fifo_us_read_1st_wakeup_request        (0x1120)
#define image_1_update_fifo_us_read_1st_wakeup_request        (0x1120)
#define image_1_start_task_processing_wakeup_request        (0x130)
#define image_1_processing_wakeup_request        (0x130)
#define image_1_start_task_tx_task_1st_wakeup_request        (0xe8c)
#define image_1_tx_task_1st_wakeup_request        (0xe8c)
#define image_1_start_task_budget_allocator_1st_wakeup_request        (0x100a)
#define image_1_budget_allocator_1st_wakeup_request        (0x100a)
#define image_1_start_task_debug_routine        (0xec)
#define image_1_debug_routine        (0xec)
#define image_1_start_task_pfc_direct_wakeup_request        (0xde4)
#define image_1_pfc_direct_wakeup_request        (0xde4)
#define image_1_start_task_ovl_budget_allocator_1st_wakeup_request        (0x10da)
#define image_1_ovl_budget_allocator_1st_wakeup_request        (0x10da)
#define image_1_start_task_dhd_tx_complete_wakeup_request        (0xc4e)
#define image_1_dhd_tx_complete_wakeup_request        (0xc4e)
#define image_1_start_task_dhd_rx_complete_wakeup_request        (0xd14)
#define image_1_dhd_rx_complete_wakeup_request        (0xd14)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dynamic_code_section        (0x2)
#define image_1_dynamic_code_section_proc0        (0x2)
#define image_1_dynamic_code_section_proc1        (0x1e)
#define image_1_dynamic_code_section_proc2        (0x3a)
#define image_1_dynamic_code_section_proc3        (0x56)
#define image_1_dynamic_code_section_proc4        (0x72)
#define image_1_dynamic_code_section_proc5        (0x8e)
#define image_1_dynamic_code_section_proc6        (0xaa)
#define image_1_dynamic_code_section_proc7        (0xc6)
#define image_1_processing_check_wlan_llcsnap        (0x366)
#define image_1_processing_write_header_done        (0x366)
#define image_1_processing_done        (0x37d)
#define image_1_action_gpe        (0x88c)
#define image_1_action_exception        (0x88e)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x89c)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x8ae)
#define image_1_gpe_sop_push_replace_sram_64        (0x8b4)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x8ba)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x8c0)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x8d2)
#define image_1_gpe_sop_pull_replace_sram_64        (0x8e4)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x8f4)
#define image_1_gpe_replace_pointer_32_sram        (0x906)
#define image_1_gpe_replace_pointer_64_sram        (0x910)
#define image_1_gpe_replace_16        (0x91a)
#define image_1_gpe_replace_32        (0x928)
#define image_1_gpe_replace_bits_16        (0x932)
#define image_1_gpe_copy_add_16_cl        (0x93e)
#define image_1_gpe_copy_add_16_sram        (0x942)
#define image_1_gpe_copy_bits_16_cl        (0x954)
#define image_1_gpe_copy_bits_16_sram        (0x958)
#define image_1_gpe_insert_16        (0x96a)
#define image_1_gpe_delete_16        (0x984)
#define image_1_gpe_decrement_8        (0x994)
#define image_1_gpe_apply_icsum_16        (0x99c)
#define image_1_gpe_apply_icsum_nz_16        (0x9a4)
#define image_1_gpe_compute_csum_16_cl        (0x9b0)
#define image_1_gpe_compute_csum_16_sram        (0x9b4)
#define image_1_gpe_buffer_copy_16_sram        (0x9c4)
#define image_1_gpe_buffer_copy_16_ddr        (0x9d0)
#define image_1_gpe_replace_add_packet_length_cl        (0x9da)
#define image_1_tcam_cmd_ic_submit        (0x9eb)
#define image_1_start_task_c_dhd_rx_complete_wakeup_request        (0x11e7)
#define image_1_c_dhd_rx_complete_wakeup_request        (0x11e7)
#define image_1_start_task_c_dhd_tx_complete_wakeup_request        (0x12af)
#define image_1_c_dhd_tx_complete_wakeup_request        (0x12af)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x11b6)
#define image_1_dhd_send_entry_to_cpu_ring        (0x11b6)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_start_task_initialization_task        (0x388)
#define image_2_initialization_task        (0x388)
#define image_2_start_task_processing_wakeup_request        (0x4c0)
#define image_2_processing_wakeup_request        (0x4c0)
#define image_2_start_task_cpu_tx_wakeup_request        (0x3130)
#define image_2_cpu_tx_wakeup_request        (0x3130)
#define image_2_cpu_tx_read_ring_indices        (0x3130)
#define image_2_start_task_debug_routine        (0x3b0)
#define image_2_debug_routine        (0x3b0)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x37c0)
#define image_2_cpu_recycle_wakeup_request        (0x37c0)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x3910)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x3910)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dynamic_code_section        (0x8)
#define image_2_dynamic_code_section_proc0        (0x8)
#define image_2_dynamic_code_section_proc1        (0x78)
#define image_2_dynamic_code_section_proc2        (0xe8)
#define image_2_dynamic_code_section_proc3        (0x158)
#define image_2_dynamic_code_section_proc4        (0x1c8)
#define image_2_dynamic_code_section_proc5        (0x238)
#define image_2_dynamic_code_section_proc6        (0x2a8)
#define image_2_dynamic_code_section_proc7        (0x318)
#define image_2_processing_check_wlan_llcsnap        (0xd98)
#define image_2_processing_write_header_done        (0xd98)
#define image_2_processing_done        (0xdf4)
#define image_2_action_gpe        (0x2228)
#define image_2_action_exception        (0x2230)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x2268)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x22b0)
#define image_2_gpe_sop_push_replace_sram_64        (0x22c8)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x22e0)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x22f8)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x2340)
#define image_2_gpe_sop_pull_replace_sram_64        (0x2388)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x23c8)
#define image_2_gpe_replace_pointer_32_sram        (0x2410)
#define image_2_gpe_replace_pointer_64_sram        (0x2438)
#define image_2_gpe_replace_16        (0x2460)
#define image_2_gpe_replace_32        (0x2498)
#define image_2_gpe_replace_bits_16        (0x24c0)
#define image_2_gpe_copy_add_16_cl        (0x24f0)
#define image_2_gpe_copy_add_16_sram        (0x2500)
#define image_2_gpe_copy_bits_16_cl        (0x2548)
#define image_2_gpe_copy_bits_16_sram        (0x2558)
#define image_2_gpe_insert_16        (0x25a0)
#define image_2_gpe_delete_16        (0x2608)
#define image_2_gpe_decrement_8        (0x2648)
#define image_2_gpe_apply_icsum_16        (0x2668)
#define image_2_gpe_apply_icsum_nz_16        (0x2688)
#define image_2_gpe_compute_csum_16_cl        (0x26b8)
#define image_2_gpe_compute_csum_16_sram        (0x26c8)
#define image_2_gpe_buffer_copy_16_sram        (0x2708)
#define image_2_gpe_buffer_copy_16_ddr        (0x2738)
#define image_2_gpe_replace_add_packet_length_cl        (0x2760)
#define image_2_tcam_cmd_ic_submit        (0x27a4)

#else

#define image_2_start_task_initialization_task        (0xe2)
#define image_2_initialization_task        (0xe2)
#define image_2_start_task_processing_wakeup_request        (0x130)
#define image_2_processing_wakeup_request        (0x130)
#define image_2_start_task_cpu_tx_wakeup_request        (0xc4c)
#define image_2_cpu_tx_wakeup_request        (0xc4c)
#define image_2_cpu_tx_read_ring_indices        (0xc4c)
#define image_2_start_task_debug_routine        (0xec)
#define image_2_debug_routine        (0xec)
#define image_2_start_task_cpu_recycle_wakeup_request        (0xdf0)
#define image_2_cpu_recycle_wakeup_request        (0xdf0)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0xe44)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0xe44)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dynamic_code_section        (0x2)
#define image_2_dynamic_code_section_proc0        (0x2)
#define image_2_dynamic_code_section_proc1        (0x1e)
#define image_2_dynamic_code_section_proc2        (0x3a)
#define image_2_dynamic_code_section_proc3        (0x56)
#define image_2_dynamic_code_section_proc4        (0x72)
#define image_2_dynamic_code_section_proc5        (0x8e)
#define image_2_dynamic_code_section_proc6        (0xaa)
#define image_2_dynamic_code_section_proc7        (0xc6)
#define image_2_processing_check_wlan_llcsnap        (0x366)
#define image_2_processing_write_header_done        (0x366)
#define image_2_processing_done        (0x37d)
#define image_2_action_gpe        (0x88a)
#define image_2_action_exception        (0x88c)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x89a)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x8ac)
#define image_2_gpe_sop_push_replace_sram_64        (0x8b2)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x8b8)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x8be)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x8d0)
#define image_2_gpe_sop_pull_replace_sram_64        (0x8e2)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x8f2)
#define image_2_gpe_replace_pointer_32_sram        (0x904)
#define image_2_gpe_replace_pointer_64_sram        (0x90e)
#define image_2_gpe_replace_16        (0x918)
#define image_2_gpe_replace_32        (0x926)
#define image_2_gpe_replace_bits_16        (0x930)
#define image_2_gpe_copy_add_16_cl        (0x93c)
#define image_2_gpe_copy_add_16_sram        (0x940)
#define image_2_gpe_copy_bits_16_cl        (0x952)
#define image_2_gpe_copy_bits_16_sram        (0x956)
#define image_2_gpe_insert_16        (0x968)
#define image_2_gpe_delete_16        (0x982)
#define image_2_gpe_decrement_8        (0x992)
#define image_2_gpe_apply_icsum_16        (0x99a)
#define image_2_gpe_apply_icsum_nz_16        (0x9a2)
#define image_2_gpe_compute_csum_16_cl        (0x9ae)
#define image_2_gpe_compute_csum_16_sram        (0x9b2)
#define image_2_gpe_buffer_copy_16_sram        (0x9c2)
#define image_2_gpe_buffer_copy_16_ddr        (0x9ce)
#define image_2_gpe_replace_add_packet_length_cl        (0x9d8)
#define image_2_tcam_cmd_ic_submit        (0x9e9)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_start_task_initialization_task        (0x388)
#define image_3_initialization_task        (0x388)
#define image_3_start_task_processing_wakeup_request        (0x3b0)
#define image_3_processing_wakeup_request        (0x3b0)
#define image_3_start_task_debug_routine        (0x3028)
#define image_3_debug_routine        (0x3028)
#define image_3_start_task_cpu_rx_wakeup_request        (0x3e50)
#define image_3_cpu_rx_wakeup_request        (0x3e50)
#define image_3_start_task_cpu_recycle_wakeup_request        (0x4230)
#define image_3_cpu_recycle_wakeup_request        (0x4230)
#define image_3_start_task_interrupt_coalescing_1st_wakeup_request        (0x4380)
#define image_3_interrupt_coalescing_1st_wakeup_request        (0x4380)
#define image_3_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4180)
#define image_3_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4180)
#define image_3_start_task_cpu_rx_copy_wakeup_request        (0x30f4)
#define image_3_cpu_rx_copy_wakeup_request        (0x30f4)
#define image_3_start_task_spdsvc_gen_wakeup_request        (0x5300)
#define image_3_spdsvc_gen_wakeup_request        (0x5300)
#define image_3_start_task_common_reprocessing_wakeup_request        (0x5560)
#define image_3_common_reprocessing_wakeup_request        (0x5560)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dynamic_code_section        (0x8)
#define image_3_dynamic_code_section_proc0        (0x8)
#define image_3_dynamic_code_section_proc1        (0x78)
#define image_3_dynamic_code_section_proc2        (0xe8)
#define image_3_dynamic_code_section_proc3        (0x158)
#define image_3_dynamic_code_section_proc4        (0x1c8)
#define image_3_dynamic_code_section_proc5        (0x238)
#define image_3_dynamic_code_section_proc6        (0x2a8)
#define image_3_dynamic_code_section_proc7        (0x318)
#define image_3_processing_check_wlan_llcsnap        (0xc88)
#define image_3_processing_write_header_done        (0xc88)
#define image_3_processing_done        (0xce4)
#define image_3_action_gpe        (0x2120)
#define image_3_action_exception        (0x2128)
#define image_3_gpe_sop_push_replace_ddr_sram_32        (0x2160)
#define image_3_gpe_sop_push_replace_sram_32_64        (0x21a8)
#define image_3_gpe_sop_push_replace_sram_64        (0x21c0)
#define image_3_gpe_sop_push_replace_sram_64_32        (0x21d8)
#define image_3_gpe_sop_pull_replace_ddr_sram_32        (0x21f0)
#define image_3_gpe_sop_pull_replace_sram_32_64        (0x2238)
#define image_3_gpe_sop_pull_replace_sram_64        (0x2280)
#define image_3_gpe_sop_pull_replace_sram_64_32        (0x22c0)
#define image_3_gpe_replace_pointer_32_sram        (0x2308)
#define image_3_gpe_replace_pointer_64_sram        (0x2330)
#define image_3_gpe_replace_16        (0x2358)
#define image_3_gpe_replace_32        (0x2390)
#define image_3_gpe_replace_bits_16        (0x23b8)
#define image_3_gpe_copy_add_16_cl        (0x23e8)
#define image_3_gpe_copy_add_16_sram        (0x23f8)
#define image_3_gpe_copy_bits_16_cl        (0x2440)
#define image_3_gpe_copy_bits_16_sram        (0x2450)
#define image_3_gpe_insert_16        (0x2498)
#define image_3_gpe_delete_16        (0x2500)
#define image_3_gpe_decrement_8        (0x2540)
#define image_3_gpe_apply_icsum_16        (0x2560)
#define image_3_gpe_apply_icsum_nz_16        (0x2580)
#define image_3_gpe_compute_csum_16_cl        (0x25b0)
#define image_3_gpe_compute_csum_16_sram        (0x25c0)
#define image_3_gpe_buffer_copy_16_sram        (0x2600)
#define image_3_gpe_buffer_copy_16_ddr        (0x2630)
#define image_3_gpe_replace_add_packet_length_cl        (0x2658)
#define image_3_tcam_cmd_ic_submit        (0x269c)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x5a68)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x5a68)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x56f4)
#define image_3_c_cpu_rx_wakeup_request        (0x56f4)

#else

#define image_3_start_task_initialization_task        (0xe2)
#define image_3_initialization_task        (0xe2)
#define image_3_start_task_processing_wakeup_request        (0xec)
#define image_3_processing_wakeup_request        (0xec)
#define image_3_start_task_debug_routine        (0xc0a)
#define image_3_debug_routine        (0xc0a)
#define image_3_start_task_cpu_rx_wakeup_request        (0xf94)
#define image_3_cpu_rx_wakeup_request        (0xf94)
#define image_3_start_task_cpu_recycle_wakeup_request        (0x108c)
#define image_3_cpu_recycle_wakeup_request        (0x108c)
#define image_3_start_task_interrupt_coalescing_1st_wakeup_request        (0x10e0)
#define image_3_interrupt_coalescing_1st_wakeup_request        (0x10e0)
#define image_3_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x1060)
#define image_3_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x1060)
#define image_3_start_task_cpu_rx_copy_wakeup_request        (0xc3d)
#define image_3_cpu_rx_copy_wakeup_request        (0xc3d)
#define image_3_start_task_spdsvc_gen_wakeup_request        (0x14c0)
#define image_3_spdsvc_gen_wakeup_request        (0x14c0)
#define image_3_start_task_common_reprocessing_wakeup_request        (0x1558)
#define image_3_common_reprocessing_wakeup_request        (0x1558)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dynamic_code_section        (0x2)
#define image_3_dynamic_code_section_proc0        (0x2)
#define image_3_dynamic_code_section_proc1        (0x1e)
#define image_3_dynamic_code_section_proc2        (0x3a)
#define image_3_dynamic_code_section_proc3        (0x56)
#define image_3_dynamic_code_section_proc4        (0x72)
#define image_3_dynamic_code_section_proc5        (0x8e)
#define image_3_dynamic_code_section_proc6        (0xaa)
#define image_3_dynamic_code_section_proc7        (0xc6)
#define image_3_processing_check_wlan_llcsnap        (0x322)
#define image_3_processing_write_header_done        (0x322)
#define image_3_processing_done        (0x339)
#define image_3_action_gpe        (0x848)
#define image_3_action_exception        (0x84a)
#define image_3_gpe_sop_push_replace_ddr_sram_32        (0x858)
#define image_3_gpe_sop_push_replace_sram_32_64        (0x86a)
#define image_3_gpe_sop_push_replace_sram_64        (0x870)
#define image_3_gpe_sop_push_replace_sram_64_32        (0x876)
#define image_3_gpe_sop_pull_replace_ddr_sram_32        (0x87c)
#define image_3_gpe_sop_pull_replace_sram_32_64        (0x88e)
#define image_3_gpe_sop_pull_replace_sram_64        (0x8a0)
#define image_3_gpe_sop_pull_replace_sram_64_32        (0x8b0)
#define image_3_gpe_replace_pointer_32_sram        (0x8c2)
#define image_3_gpe_replace_pointer_64_sram        (0x8cc)
#define image_3_gpe_replace_16        (0x8d6)
#define image_3_gpe_replace_32        (0x8e4)
#define image_3_gpe_replace_bits_16        (0x8ee)
#define image_3_gpe_copy_add_16_cl        (0x8fa)
#define image_3_gpe_copy_add_16_sram        (0x8fe)
#define image_3_gpe_copy_bits_16_cl        (0x910)
#define image_3_gpe_copy_bits_16_sram        (0x914)
#define image_3_gpe_insert_16        (0x926)
#define image_3_gpe_delete_16        (0x940)
#define image_3_gpe_decrement_8        (0x950)
#define image_3_gpe_apply_icsum_16        (0x958)
#define image_3_gpe_apply_icsum_nz_16        (0x960)
#define image_3_gpe_compute_csum_16_cl        (0x96c)
#define image_3_gpe_compute_csum_16_sram        (0x970)
#define image_3_gpe_buffer_copy_16_sram        (0x980)
#define image_3_gpe_buffer_copy_16_ddr        (0x98c)
#define image_3_gpe_replace_add_packet_length_cl        (0x996)
#define image_3_tcam_cmd_ic_submit        (0x9a7)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x169a)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x169a)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x15bd)
#define image_3_c_cpu_rx_wakeup_request        (0x15bd)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_start_task_initialization_task        (0x388)
#define image_4_initialization_task        (0x388)
#define image_4_start_task_processing_wakeup_request        (0x3b0)
#define image_4_processing_wakeup_request        (0x3b0)
#define image_4_start_task_debug_routine        (0x3020)
#define image_4_debug_routine        (0x3020)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0x3b90)
#define image_4_dhd_tx_post_wakeup_request        (0x3b90)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x3b40)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0x3b40)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0x39c8)
#define image_4_dhd_timer_1st_wakeup_request        (0x39c8)
#define image_4_start_task_dhd_mcast_wakeup_request        (0x33d0)
#define image_4_dhd_mcast_wakeup_request        (0x33d0)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dynamic_code_section        (0x8)
#define image_4_dynamic_code_section_proc0        (0x8)
#define image_4_dynamic_code_section_proc1        (0x78)
#define image_4_dynamic_code_section_proc2        (0xe8)
#define image_4_dynamic_code_section_proc3        (0x158)
#define image_4_dynamic_code_section_proc4        (0x1c8)
#define image_4_dynamic_code_section_proc5        (0x238)
#define image_4_dynamic_code_section_proc6        (0x2a8)
#define image_4_dynamic_code_section_proc7        (0x318)
#define image_4_processing_check_wlan_llcsnap        (0xc88)
#define image_4_processing_write_header_done        (0xc88)
#define image_4_processing_done        (0xce4)
#define image_4_action_gpe        (0x2118)
#define image_4_action_exception        (0x2120)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x2158)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x21a0)
#define image_4_gpe_sop_push_replace_sram_64        (0x21b8)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x21d0)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x21e8)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x2230)
#define image_4_gpe_sop_pull_replace_sram_64        (0x2278)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x22b8)
#define image_4_gpe_replace_pointer_32_sram        (0x2300)
#define image_4_gpe_replace_pointer_64_sram        (0x2328)
#define image_4_gpe_replace_16        (0x2350)
#define image_4_gpe_replace_32        (0x2388)
#define image_4_gpe_replace_bits_16        (0x23b0)
#define image_4_gpe_copy_add_16_cl        (0x23e0)
#define image_4_gpe_copy_add_16_sram        (0x23f0)
#define image_4_gpe_copy_bits_16_cl        (0x2438)
#define image_4_gpe_copy_bits_16_sram        (0x2448)
#define image_4_gpe_insert_16        (0x2490)
#define image_4_gpe_delete_16        (0x24f8)
#define image_4_gpe_decrement_8        (0x2538)
#define image_4_gpe_apply_icsum_16        (0x2558)
#define image_4_gpe_apply_icsum_nz_16        (0x2578)
#define image_4_gpe_compute_csum_16_cl        (0x25a8)
#define image_4_gpe_compute_csum_16_sram        (0x25b8)
#define image_4_gpe_buffer_copy_16_sram        (0x25f8)
#define image_4_gpe_buffer_copy_16_ddr        (0x2628)
#define image_4_gpe_replace_add_packet_length_cl        (0x2650)
#define image_4_tcam_cmd_ic_submit        (0x2694)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x49f0)
#define image_4_c_dhd_timer_wakeup_request        (0x49f0)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x4b44)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x4b44)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x4b8c)
#define image_4_c_dhd_tx_post_wakeup_request        (0x4b8c)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x492c)
#define image_4_dhd_send_entry_to_cpu_ring        (0x492c)
#define image_4_start_task_dhd_tx_get_bq_index        (0x58d4)
#define image_4_dhd_tx_get_bq_index        (0x58d4)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x57f0)
#define image_4_dhd_tx_post_drop_packet        (0x57f0)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x5634)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x5634)
#define image_4_start_task_dhd_tx_put_bq_index        (0x5948)
#define image_4_dhd_tx_put_bq_index        (0x5948)

#else

#define image_4_start_task_initialization_task        (0xe2)
#define image_4_initialization_task        (0xe2)
#define image_4_start_task_processing_wakeup_request        (0xec)
#define image_4_processing_wakeup_request        (0xec)
#define image_4_start_task_debug_routine        (0xc08)
#define image_4_debug_routine        (0xc08)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0xee4)
#define image_4_dhd_tx_post_wakeup_request        (0xee4)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0xed0)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0xed0)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0xe72)
#define image_4_dhd_timer_1st_wakeup_request        (0xe72)
#define image_4_start_task_dhd_mcast_wakeup_request        (0xcf4)
#define image_4_dhd_mcast_wakeup_request        (0xcf4)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dynamic_code_section        (0x2)
#define image_4_dynamic_code_section_proc0        (0x2)
#define image_4_dynamic_code_section_proc1        (0x1e)
#define image_4_dynamic_code_section_proc2        (0x3a)
#define image_4_dynamic_code_section_proc3        (0x56)
#define image_4_dynamic_code_section_proc4        (0x72)
#define image_4_dynamic_code_section_proc5        (0x8e)
#define image_4_dynamic_code_section_proc6        (0xaa)
#define image_4_dynamic_code_section_proc7        (0xc6)
#define image_4_processing_check_wlan_llcsnap        (0x322)
#define image_4_processing_write_header_done        (0x322)
#define image_4_processing_done        (0x339)
#define image_4_action_gpe        (0x846)
#define image_4_action_exception        (0x848)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x856)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x868)
#define image_4_gpe_sop_push_replace_sram_64        (0x86e)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x874)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x87a)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x88c)
#define image_4_gpe_sop_pull_replace_sram_64        (0x89e)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x8ae)
#define image_4_gpe_replace_pointer_32_sram        (0x8c0)
#define image_4_gpe_replace_pointer_64_sram        (0x8ca)
#define image_4_gpe_replace_16        (0x8d4)
#define image_4_gpe_replace_32        (0x8e2)
#define image_4_gpe_replace_bits_16        (0x8ec)
#define image_4_gpe_copy_add_16_cl        (0x8f8)
#define image_4_gpe_copy_add_16_sram        (0x8fc)
#define image_4_gpe_copy_bits_16_cl        (0x90e)
#define image_4_gpe_copy_bits_16_sram        (0x912)
#define image_4_gpe_insert_16        (0x924)
#define image_4_gpe_delete_16        (0x93e)
#define image_4_gpe_decrement_8        (0x94e)
#define image_4_gpe_apply_icsum_16        (0x956)
#define image_4_gpe_apply_icsum_nz_16        (0x95e)
#define image_4_gpe_compute_csum_16_cl        (0x96a)
#define image_4_gpe_compute_csum_16_sram        (0x96e)
#define image_4_gpe_buffer_copy_16_sram        (0x97e)
#define image_4_gpe_buffer_copy_16_ddr        (0x98a)
#define image_4_gpe_replace_add_packet_length_cl        (0x994)
#define image_4_tcam_cmd_ic_submit        (0x9a5)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x127c)
#define image_4_c_dhd_timer_wakeup_request        (0x127c)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x12d1)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x12d1)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x12e3)
#define image_4_c_dhd_tx_post_wakeup_request        (0x12e3)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x124b)
#define image_4_dhd_send_entry_to_cpu_ring        (0x124b)
#define image_4_start_task_dhd_tx_get_bq_index        (0x1635)
#define image_4_dhd_tx_get_bq_index        (0x1635)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x15fc)
#define image_4_dhd_tx_post_drop_packet        (0x15fc)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x158d)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x158d)
#define image_4_start_task_dhd_tx_put_bq_index        (0x1652)
#define image_4_dhd_tx_put_bq_index        (0x1652)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND

#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {0x27a4, 0x27ac, 0x27a4, 0x269c, 0x2694}

#else

#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {0x9e9, 0x9eb, 0x9e9, 0x9a7, 0x9a5}

#endif


#endif

